### ISSUE TITLE
Persist docker cache in docker-in-docker devcontainer

### ISSUE THREAD

**Issue by mr-bjerre** [microsoft/vscode-dev-containers#1004]
In the remove devcontainer docs - it is explained how to [persist bash history between runs](https://code.visualstudio.com/docs/remote/containers-advanced#_persist-bash-history-between-runs)

In the `docker-in-docker` devcontainer it would be great with documentation on how to persist docker cache between runs so you don't have to rebuild all the containers in the devcontainer between runs. I assume it can be done similarly - I just don't know enough about the docker internals to do it

**Comment by Chuxel** [comment]
This line in devcontainer.json should make that happen: `"mounts": ["source=dind-var-lib-docker,target=/var/lib/docker,type=volume"],`

However, if you are switching between containers, be sure to give the source a unique name.

**Comment by mr-bjerre** [comment]
Oh my bad. For some reason I didn't see that in the docs. 

Thanks for your help!
