### ISSUE TITLE
How to preinstall dependencies for remote containers?

### ISSUE THREAD

**Issue by pourmand2010** [microsoft/vscode-dev-containers#1017]
I know that I can use the `extensions` property of the `devcontainers.json` file to tell VS Code about the extensions I want to be there when I start my remote container session.

I also develop .NET and I know that these components are needed:

Installing C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=18.04

Downloading package 'OmniSharp for Linux (x64)' (36011 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Linux (x64)'

Downloading package '.NET Core Debugger (Linux / x64)' (3411 KB).................... Done!
Installing package '.NET Core Debugger (linux / x64)'

Downloading package 'Razor Language Server (Linux / x64)' (61682 KB).................... Done!
Installing package 'Razor Language Server (Linux / x64)'

Finished

So as you can see, each time I start the container the list of extensions have to be installed and these dependencies also should be installed.

Is there a way that I embed these dependencies and extensions once inside my docker image so that they are there always?

Because we have an infrastructure that deletes containers randomly (chaos engineering), the current behaviour is extremely inefficient. Each time a container comes up we have to wait a lot to see these being installed

Relates to: Remote - Containers

**Comment by Chuxel** [comment]
@pourmand2010 Unfortunately, this is related to the .NET extension and is not something we control. I don't know if this is currently possible.  The C++ extension has offline VSIX packages that could be used, but I don't believe the C# extension does.  Please raise a feature request at https://github.com/OmniSharp/omnisharp-vscode if you need something here.
