### ISSUE TITLE
Can we use env variables in devcontainer json?

### ISSUE THREAD

**Issue by brianignacio5** [microsoft/vscode-dev-containers#1024]
Can we use environment variables in `devcontainer.json` like we do in settings.json (i.e. ${env:VAR_NAME}) ?

I try using it on Windows opening a folder in a Debian container by defining a configuration setting in `devcontainer.json` without success. 

In case is not feasible, is there a workaround ?

**Comment by Chuxel** [comment]
See "Variables in devcontainer.json" at https://aka.ms/devcontainer.json for what is available here.
