### ISSUE TITLE
python-3-anaconda does not build

### ISSUE THREAD

**Issue by cscholle1** [microsoft/vscode-dev-containers#104]
- VSCode Version:  1.36.1
- Local OS Version:  Windows 10 Pro 1809
- Name of Dev Container Definition with Issue: [python-3-anaconda](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3-anaconda)

Steps to Reproduce:

1. In vscode, open new empty folder
2. `ctrl+shift+p` -> `Remote-Containers: Open Folder in Container...`
3. Select `python-3-anaconda` from the list

Error when building dev container:

```sh
!!!previous output omitted!!!

Processing triggers for mime-support (3.62) ...
/bin/sh: 1: pip: not found
The command '/bin/sh -c apt-get update     && apt-get -y install --no-install-recommends apt-utils 2>&1     && apt-get -y install git procps lsb-release     && pip install pylint     && if [ -f "/tmp/conda-tmp/environment.yml" ]; then conda env update -n base -f /tmp/conda-tmp/environment.yml; fi     && rm -rf /tmp/conda-tmp     && apt-get autoremove -y     && apt-get clean -y     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 127
```

Possibly related to base image `continuumio/anaconda3` making breaking changes to follow Docker best practices and trim their images: https://github.com/ContinuumIO/docker-images/issues/120#issuecomment-480953522

**Comment by Chuxel** [comment]
@cscholle1 Yes, this is a base image issue. For some reason, /bin/sh can't find pip in the latest image which cases the failure.  To fix, just update the pylint install line in the Dockerfile.

Change...
```
&& pip install pylint 
```

... to ...

```
&& /opt/conda/bin/pip install pylint 
```

The definition in this repo has the fix in it and will go with the next release of the containers extension.  Thanks for reporting it!
