### ISSUE TITLE
Error with image not found for SalesForce definition

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#1045]
As outlined in this [StackExchange  post](https://salesforce.stackexchange.com/questions/354209/manifest-for-salesforce-salesforcedxlatest-not-found-manifest-unknown-manifes), automated CI is reporting that the SalesForce [spdx-project definition](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/sfdx-project) is failing with an error `manifest for salesforce/salesforcedx:latest not found: manifest unknown: manifest unknown`.

The suggestion in the post is to do use `salesforce/salesforcedx:latest-rc-full` instead.

@dehru - Given this was a definition you contributed, should it be updated?  (Or if its not something Salesforce intends for folks to use, should we remove the definition?)

**Comment by dehru** [comment]
@Chuxel - Thanks for reporting.  Update is in this [PR](https://github.com/microsoft/vscode-dev-containers/pull/1047)
