### ISSUE TITLE
Add Alpine Linux arm64 support

### ISSUE THREAD

**Issue by richbecks** [microsoft/vscode-dev-containers#1067]
All our dev containers are alpine-based (e.g. mcr.microsoft.com/vscode/devcontainers/base:0-alpine), it would be great if we could re-use these for our ARM-based build systems, and for devs using Apple M1 macs.

**Comment by Chuxel** [comment]
VS Code Insiders does support arm64 Alpine now, but stable does not yet.  We can do this once VS Code 1.61 is released next week. In the mean time, we'd break users.

**Comment by Chuxel** [comment]
Development versions of these images are now available. For example:

`mcr.microsoft.com/vscode/devcontainers/base:dev-alpine-3.14`

**Comment by Chuxel** [comment]
This was released with 0.202.2!
