### ISSUE TITLE
Base image of dart dev container is deprecated

### ISSUE THREAD

**Issue by fkromer** [microsoft/vscode-dev-containers#1072]
- Name of Dev Container Definition with Issue: dart

[google/dart](https://hub.docker.com/r/google/dart/) is deprecated. The [image `dart`](https://hub.docker.com/_/dart) should be used instead.

**Comment by Chuxel** [comment]
Updated!  Thanks for letting us know.

**Comment by fkromer** [comment]
@Chuxel Thanks for fixing.
