### ISSUE TITLE
docker-in-docker-debian.sh curl: (22) The requested URL returned error: 404

### ISSUE THREAD

**Issue by metaskills** [microsoft/vscode-dev-containers#1075]
We are using this script in our VS Code images that do not have Docker installed.https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docker-in-docker-debian.sh

Today I noticed an error happening at this line. https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docker-in-docker-debian.sh#L141 and it happens on all the images. The local variable here would be:

```
https://github.com/docker/compose/releases/download/v2.0.0/docker-compose-Linux-x86_64
```

Seems the issue is the v2.0.0 release has `linux` vs `Linux`. Fun stuff :(

## Steps to Reproduce:

```
$ docker run --interactive --tty --rm --entrypoint "/bin/bash" mcr.microsoft.com/vscode/devcontainers/javascript-node
> URL="https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/docker-in-docker-debian.sh"
> curl -s $URL | sudo bash
```

**Comment by Chuxel** [comment]
@metaskills Thanks for raising visiblity.  We'll work on a fix.  //cc @chrmarti @joshspicer

**Comment by metaskills** [comment]
Thank you! All of our new dev containers which use this as a postCreate command are a little broken now. Such an odd problem. Not sure what the fix would be. Again, thanks!!!

**Comment by Chuxel** [comment]
Yeah it looks like v2 came out, went to the same repo, but is completely different and incompatible.  Very odd decision.  We'll pin to v1 to resolve.

**Comment by Chuxel** [comment]
Resolved in the latest version of the scripts.  Grab the latest `docker-in-docker-debian.sh` or `docker-debian.sh` from the [`script-library` folder](https://github.com/microsoft/vscode-dev-containers/tree/main/script-library) to fix.

**Comment by metaskills** [comment]
I can confirm things work again. Thanks!!!

**Comment by Chuxel** [comment]
0.197.1 will have the fix for insiders for new definitions added via VS Code UX.  0.194.3 is a back port of this one issue for stable.

**Comment by davetapley** [comment]
Thanks for rapid fix 🙏🏻 

This makes me wonder:
Is having `docker-debian.sh` copied in to each repo at `.devcontainer/library-scripts` (still) the correct/preferred way to use it? That's how I have it configured per [these docs](https://github.com/microsoft/vscode-dev-containers/blob/v0.197.1/script-library/docs/docker.md#usage), but it does mean I need to manually update all repos in cases like this 🤔

**Comment by Chuxel** [comment]
Yeah the flip side is that you can download from main, but this can cause unexpected breaks. Pinning to a release tag instead removes that problem, but still creates this issue.

We're looking at a capability where for our base images you can reference a feature in devcontainer.json to have this installed so you won't need to copy scripts to get a better balancing act. See https://github.com/microsoft/vscode-remote-release/issues/5442

Decouples the repository from getting the feature and its backing implementation.

**Comment by metaskills** [comment]
@Chuxel Bit out of context... but has there been any requests to add Docker & Docker Compose to most other images since it seems like a common dev tool?

**Comment by Chuxel** [comment]
@metaskills The concept I mention above will let you add a devcontainer.json reference to include it and the "Add Development Container Configuration Files..." UX will show it and other options you can pick from. That also allows the script to get rev'd in cases like this without everyone having to update their definitions.

**Comment by davetapley** [comment]
@Chuxel and @chrmarti forgive the `@`, but I just had to tell you that `features` is **amazing** and has been the clincher for me to fully switch to devcontainers / Codespaces. Thank you and good work! 🙏🏻 🙏🏻 🙏🏻

I wanted to share on https://github.com/microsoft/vscode-remote-release/issues/5442 but it's locked 🤪
