### ISSUE TITLE
Add "system" version to python-debian.sh and git-debian.sh

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#1077]
With the new features work being planned (https://github.com/microsoft/vscode-remote-release/issues/5442, #1044), users may be perfectly happy to install the OS version of python or git. 

The original intent of the scripts were to deal with situations where you want the latest and greatest. This drives doing a build in most cases - so it's slow.

With the features UX, giving developers the option to just fall back on system would be a nice convenience.

**Comment by joshspicer** [comment]
Does system essential mean, "if <tool> detected, don't do anything"?

**Comment by Chuxel** [comment]
@joshspicer More that we'd install the distribution version if missing.

As @2percentsilk and I were talking about it, maybe the script should accept either `os-provided` or `system` as values to get into this mode.  We're thinking `os-provided` might be more descriptive.

For Python though, we should install a bit more than just python3-minimal, however. The kitchen sink has a number of python things we install, most notably `build-essential` `libssl-dev` `libffi-dev` `python3-dev`.  

We may just want to move this like to be general requirements:

```
    check_packages curl ca-certificates gnupg2 tar make gcc libssl-dev zlib1g-dev libncurses5-dev \
                libbz2-dev libreadline-dev libxml2-dev xz-utils libgdbm-dev tk-dev dirmngr \
                libxmlsec1-dev libsqlite3-dev libffi-dev liblzma-dev uuid-dev 
```

and then separately install `python3`, `python3-doc`, `python3-pip`, `python3-venv`, `python3-dev`, `python3-tk`

@2percentsilk  @bamurtaugh - Any thoughts on the name?

**Comment by 2percentsilk** [comment]
I'm in favor of `os-provided` in the UX and aligned with accepting `os-provided` or `system`.

**Comment by bamurtaugh** [comment]
Is "OS version" or "OS provided" standard Docker/Linux terminology? I'm not sure I've standardly seen it, so was trying to find an example somewhere/see if it would resonate with users. Are we just meaning that the version of a package that comes with that OS, like how Linux distros come with Python by default?

**Comment by Chuxel** [comment]
@bamurtaugh Correct. We don't know what that version is up front. Right now we've got it set up as `os-provided`.

**Comment by bamurtaugh** [comment]
I think `os-provided` makes sense. Describing it in docs would also probably be helpful in case folks have any confusion.

**Comment by Chuxel** [comment]
Ok - we merged in this PR, so given we agree on naming, I think we're good! Closing.
