### ISSUE TITLE
Codespaces not logging to a Microsoft Account for Sync Settings

### ISSUE THREAD

**Issue by valfrid-ly** [microsoft/vscode-dev-containers#1086]
When trying to sign in with a Microsoft account in Sync Settings it fails to log in with message "Error while turning on Settings Sync. Unable to login"

- VSCode Version: 1.60.2
- Local OS Version: 1.60.2
- Reproduces in: Codespaces
- Name of Dev Container Definition with Issue: tmsmith/Dapper-Extensions

Steps to Reproduce:

1. Setup both accounts on your local VSCode, github and microsoft
2. Open github.dev
3. In accounts button, sign in (if not signed yet) to your github account
4. In accounts button click on "Turn on Settings Sync..."
5. Click in "Sign in & Turn on" button
6. Select "Sign in with Microsoft"
7. Log in to your Microsoft account in the new opened tab
8. Error while turning on Settings Sync. Unable to login should appear on codespaces tab in the bottom right corner

**Comment by Chuxel** [comment]
@valfrid-ly Thanks for raising the issue.  This repository is about issues with images or dev container definitions found in this repository.  Please raise issues specifically related to GitHub Codespaces in their feedback forum: https://github.com/github/feedback/discussions/categories/codespaces-feedback I unfortunately can't transfer.

**Comment by valfrid-ly** [comment]
Thanks
