### ISSUE TITLE
Node & Typescript always uses 16-bullseye in Dockerfile

### ISSUE THREAD

**Issue by danthegoodman1** [microsoft/vscode-dev-containers#1099]
- VSCode Version: 1.61
- Local OS Version: macOS 11.6
- Reproduces in: Local
- Name of Dev Container Definition with Issue: Node.js & Typescript

Steps to Reproduce:

1. Use the `Remote-Containers: Add Development Container Configuration Files...` command
2. Create a new Node.js & Typescript, any version
3. See the line `ARG VARIANT="16-bullseye"` in the generated `Dockerfile`

TL;DR No matter what version you select, the `ARG VARIANT="16-bullseye"` always appears in the generated Dockerfile. In the `devcontainer.json` the correct version is used.

**Comment by Chuxel** [comment]
Thanks for raising, but this is expected. That is the default value, not the value used during build. The actual argument is set in devcontainer.json or docker-compose.yml if Docker Compsoe is used.  In your example above, it's in devcontainer.json:

```
		"args": { 
			"VARIANT": "14"
		}
```
