### ISSUE TITLE
Add phoenix 1.6, remove node dependency

### ISSUE THREAD

**Issue by matthewisabel** [microsoft/vscode-dev-containers#1105]
From Codespaces discussions from @krainboltgreene: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/elixir-phoenix-postgres

Looks like with 1.6 of Phoenix out we can upgrade and also potentially remove the node dependency

Relates to: Both

**Comment by Chuxel** [comment]
Closing since this has been merged!
