### ISSUE TITLE
Seems that the python-3-miniconda example is not working

### ISSUE THREAD

**Issue by lecerd** [microsoft/vscode-dev-containers#1141]
- VSCode Version: 1.61.2
- Local OS Version: macOS - Catalina 10.15.7
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: python-3-miniconda (@main)

Steps to Reproduce:

1. Follow steps `1` to `6` described in ["Testing the definition"](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/python-3-miniconda/README.md#testing-the-definition).
2. Watch terminal output `ModuleNotFoundError: No module named 'matplotlib'`

**Screenshot**
<img width="1792" alt="Screen Shot 2021-10-29 at 12 52 04" src="https://user-images.githubusercontent.com/778291/139465388-4eaf4c0e-ad5f-4e34-82b2-0dcf880dcf52.png">

**Comment by Chuxel** [comment]
Neither matplotlab nor numpy would be there by default so the instructions need to be updated to install them.

**Comment by lecerd** [comment]
@Chuxel, thanks for the quick response.

I don't follow, `jupyter`,  `matplotlib` and `numpy` are listed as dependencies in [environment.yaml](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/python-3-miniconda/test-project/environment.yml) and the screenshot is from the output of the run within the remote container. Shouldn't those dependencies be installed in. that environment?

**Comment by Chuxel** [comment]
@lecrd No, the environment.yml file is in a sub folder so it won't be in the image.

**Comment by Chuxel** [comment]
Resolved the test in #1143, though not that the image is not yet released.

**Comment by lecerd** [comment]
>  No, the environment.yml file is in a sub folder so it won't be in the image.
But in the presented [Dockerfile](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/python-3-miniconda/.devcontainer/Dockerfile#L9) is getting copied into the image and using it to execute a `conda env update`, that's what confused.

Note: This is my first time trying to use remote containers so I'm not to aware of what will be available in the container image and what not. Is there documentation on this?

> though not that the image is not yet released.
Any idea when this will be released to use as base image?

Cheers!

**Comment by Chuxel** [comment]
> But in the presented Dockerfile is getting copied into the image and using it to execute a conda env update, that's what confused. This is my first time trying to use remote containers so I'm not to aware of what will be available in the container image and what not. Is there documentation on this?

@lecerd https://github.com/microsoft/vscode-dev-containers/tree/main/containers/python-3-miniconda#optional-adding-the-contents-of-environmentyml-to-the-image describes what this is for. The way you add this to your project is to use the **Add Development Container Configuration Files** command which will omit `base.Dockerfile`.  Otherwise this is straight miniconda.  The [history](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/python-3-miniconda/history) files describe other contents. There's an anaconda image if you want things like Jupyter without having a custom envornment.yaml in the root of your project.

> Any idea when this will be released to use as base image?

Today or tomorrow.

**Comment by Chuxel** [comment]
Updated image is out.
