### ISSUE TITLE
update bazel. Currently at 3.4.1 and buster. Latest version is 4.2.1

### ISSUE THREAD

**Issue by pratikpc** [microsoft/vscode-dev-containers#1153]
Bazel latest version:- https://github.com/bazelbuild/bazel/releases/tag/4.2.1

Also update to bullseye.

File: https://github.com/microsoft/vscode-dev-containers/blob/main/containers/bazel/.devcontainer/Dockerfile

**Comment by pratikpc** [comment]
I would be okay with helping and creating a PR for the same but I am not sure what the test process for the update would look like?

Any docs I can refer to.

Thanks a ton!

**Comment by danmx** [comment]
why not just use `bazelisk` instead?

**Comment by pratikpc** [comment]
That would definitely be a nice idea.

**Comment by Chuxel** [comment]
//cc: @Shikanime who contributed this community definition.  Thoughts on the above?

**Comment by Shikanime** [comment]
Afaik, Bazelisk is sort of the de facto standard for Bazel version management in single binary format, so it may be a better option.
That said, in recent years I haven't really used Bazel outside of a few open source Google projects.

**Comment by Shikanime** [comment]
Here we go, glad to make your day better 🌈
