### ISSUE TITLE
Unable to start dev conatiner

### ISSUE THREAD

**Issue by Flyffies** [microsoft/vscode-dev-containers#118]
- VSCode Version: 1.13.1
- Local OS Version: Windows 7
- Name of Dev Container Definition with Issue:

My windows 7 is unable to run dev containers using Docker Toolbox.
The Problem is a trivial one, docker does not recognise the paths to mount.

Docker just can't handle the additional : in the path.
I copied the command and replaced the "c:\Users\..." with "\c\Users\..." and it worked.

![image](https://user-images.githubusercontent.com/6882791/63157161-97cb3000-c016-11e9-9165-d1ecca51b1d3.png)

Would it be possible to create a workaround?

**Comment by Flyffies** [comment]
Sorry, Wrong repository...

**Comment by DominikJaniec** [comment]
> 
> 
> Sorry, Wrong repository...

I'm looking for solution, as I've got similar situation. @Flyffies, do you have any link to that?

**Comment by Flyffies** [comment]
Hi @DominikJaniec, sorry havent seen your comment.

Here is the other issue I opend:
https://github.com/microsoft/vscode-remote-release/issues/1179
