### ISSUE TITLE
.net 6 ARM

### ISSUE THREAD

**Issue by clcl0n** [microsoft/vscode-dev-containers#1180]
omnisharp will be soon running on arm https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.18-beta1

**Comment by juzuluag** [comment]
Adding reference to https://github.com/OmniSharp/omnisharp-vscode/issues/4955 to see if there is support for dev containers too.

**Comment by Chuxel** [comment]
The following images should now have .NET arm support!

- mcr.microsoft.com/vscode/devcontainers/dotnet:6.0-bullseye
- mcr.microsoft.com/vscode/devcontainers/dotnet:5.0-bullseye
- mcr.microsoft.com/vscode/devcontainers/dotnet:3.1-bullseye
