### ISSUE TITLE
Please add to the readme how to run standalone with just an ssh server

### ISSUE THREAD

**Issue by krasi-georgiev** [microsoft/vscode-dev-containers#1186]
I am running balena OS and it has a modified version of docker so I am not able to connect to the docker daemon remotely. 
Instead, I am thinking to just start a development container with ssh and using the vs-code remote ssh extension to develop on the balena device remotely.

I looked through the docs and tried few commands, but couldn't figure out how to start a ssh server so that vs-code can connect to it remotely.

Also looked at this video, but the sshd service doesn't exist in the images I tried - `base:0-debian11`, `base:0-buster`
https://www.youtube.com/watch?v=KuSNpZgDYDs
	
```
docker run -it --init --rm mcr.microsoft.com/vscode/devcontainers/base:0-buster
```

**Comment by Chuxel** [comment]
SSH is not in any of these images by default. We have a script you can use to add it. https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/sshd.md
the
The main thing you'll need to do in this scenario that you do not with VS Code is expose the SSH server port.  By default that is on 2222.  

```
docker run -it -p 2222:2222 --init --rm mcr.microsoft.com/vscode/devcontainers/base:0-buster
```

You may also be interested in the upcoming support for using VS Code Remote - SSH and Remote - Containers together.
