### ISSUE TITLE
Rvm default gid conflicts with user gid syncing

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-dev-containers#1192]
- VSCode Version: 1.63.0-insider (user setup)
- Local OS Version: Windows_NT x64 10.0.19043
- Remote OS Version: 🤷‍♂️ it's a dev container
- Remote Extension/Connection Type: WSL I think 🤷‍♂️
- Logs:

>Version: 1.63.0-insider (user setup)
Commit: 1e473b624f088fc05269891170a8ffa1c84a35a6
Date: 2021-11-25T09:04:34.615Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. clone this repo in WSL: https://github.com/dapr/quickstarts
2. new VS code WSL window 
3. open cloned repo through remote 
![image](https://user-images.githubusercontent.com/14079228/143532649-cb371f85-06ed-40d1-bc2c-76b46e6e86f5.png)
4. vs code recognizes it, say `Reopen in Container`
![image](https://user-images.githubusercontent.com/14079228/143532136-77eea6a6-a305-40ed-bd15-a5cac32946fa.png)
5. open this path `/workspaces/quickstarts/hello-world`
![image](https://user-images.githubusercontent.com/14079228/143532287-ba0c4586-1a0e-4c90-a558-46622a471563.png)
7. try to update _launch.json_
>Failed to save 'launch.json': Unable to write file 'vscode-remote://dev-container+5c5c77736c245c7562756e74755c686f6d655c6d6465706f75775c717569636b737461727473/workspaces/quickstarts/hello-world/.vscode/launch.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/workspaces/quickstarts/hello-world/.vscode/launch.json')

Does this issue occur when you try this locally?: haven't tried but probably not
Does this issue occur when you try this locally and all extensions are disabled?: don't know

**Comment by Chuxel** [comment]
@spottedmahn Oops! Got my version numbers messed up.  1.63 is the VS Code release - 1.6.9 is what this image version will be once released. 😅  They were a bit too close.

**Comment by Chuxel** [comment]
1.6.9 was released!

**Comment by spottedmahn** [comment]
>1.6.9 was released!

I'm confused...

1. I don't see a VS Code release for 1.6.9 (reference: [releases](https://github.com/microsoft/vscode/releases)), the latest one is 1.62.3
2. Isn't this a change in the extension & not VS Code? 🤔

---

appreciate the quick turnaround on this issue btw, thanks!! ⚡

**Comment by Chuxel** [comment]
This is the image version.  See https://github.com/dapr/quickstarts/blob/a7f82eeda51f4907ba4da27c461b37d89fdead9b/.devcontainer/Dockerfile#L6

```
FROM mcr.microsoft.com/vscode/devcontainers/universal:1.4.0-focal
```

becomes

```
FROM mcr.microsoft.com/vscode/devcontainers/universal:1.6.9-focal
```

**Comment by spottedmahn** [comment]
ah, I see, thanks @Chuxel!
