### ISSUE TITLE
Add support for "dotnet" dev container feature

### ISSUE THREAD

**Issue by anthony-c-martin** [microsoft/vscode-dev-containers#1199]
It would be nice to be able to install the `dotnet` CLI via "Dev container features" (https://code.visualstudio.com/docs/remote/containers#_dev-container-features-preview). Functionally, I imagine this would be similar to the install options for Node: https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/node.md.

Is there a reason not to support this, or are you just waiting for a contribution? With some pointers, I'd be happy to contribute!

Relates to: Codespaces & Remote - Containers

**Comment by Chuxel** [comment]
I believe @bderusha was looking into this one as well.

We also have a preview of support for referencing external features based on the work @joshspicer is doing.  See https://github.com/microsoft/dev-container-features-template

The scripts in this repository make up a feature set and we're working towards externalizing those as well.

**Comment by bderusha** [comment]
@anthony-c-martin @Chuxel   Indeed @Kpopovs1 and I are working on this and have made significant progress.  We are expecting a PR to be ready next week.

**Comment by joshspicer** [comment]
> We also have a preview of support for referencing external features based on the work @joshspicer is doing that was released in Remote - Containers v0.209.3 (with VS Code 1.63). See https://github.com/microsoft/dev-container-features-template

If you do explore this and have questions I am happy to walk through it anytime! @bderusha

**Comment by anthony-c-martin** [comment]
Thanks all for the detailed updates. Looking forward to it!

**Comment by bderusha** [comment]
@anthony-c-martin this has merged! 🎉

**Comment by anthony-c-martin** [comment]
Awesome, thanks so much for implementing this 😄
