### ISSUE TITLE
Option to specify which services from docker-compose to launch.

### ISSUE THREAD

**Issue by mxdmedia** [microsoft/vscode-dev-containers#121]
In a current project repo, we have a fairly deep docker-compose file, with multiple optional services that can be launched for our developers.  For example- our `docker-compose.yml` contains (among other things):

1. backend api service  (`service: api`)
2. frontend client web app  (`service: client`)
3. database for api  (`service: db`)
4. web-based db admin tool (`service dbadmin`)
5. redis server for backend tasks (`service: redis`)

We've then set up `devcontainer.json` files in both the backend and client directories, so that a developer can easily fire a container up for debugging, etc.  The web-based db admin tool, for example, is rarely used by the front-end developers, and the redis server is almost never used locally (it is there for when we deploy).  It would be nice to have an option in the `devcontainer.json` file for specific services to fire up.  E.g. for the backend:

```
{
  ... 
  "launch": ["db", "api"],
  ...
}
```
while the frontend file might look like:
```
{
  ...
  "launch": ["client"]
  ...
}
```
This would keep unnecessary containers from spinning up.  Then if a dev needed the redis server or dbadmin, they could manually launch those containers themselves.

**Comment by Chuxel** [comment]
@mxdmedia Great suggestion!  Would you mind upvoting https://github.com/microsoft/vscode-remote-release/issues/211?  I'm closing this as a duplicate since that issue covers the same scenario.  Happy to take any feedback on the solution there as well.

**Comment by mxdmedia** [comment]
Absolutely.  Upvoted that issue (I assume by upvote, you mean to add a thumbs up to the first issue post).  Sorry about posting the dupe.
