### ISSUE TITLE
Add "Default Mounts" and "Default Environment Variables"

### ISSUE THREAD

**Issue by freund17** [microsoft/vscode-dev-containers#1221]
Similar to the "Default Extensions" setting, I'd like there to be "Default Mounts" and "Default Environment Variables" settings for specifying additional mount points and environment variables for all devcontainers.

The main use-case (for me, at least) is in linking my devcontainer to WSLg or another X11 server to support GUI apps - either when developing one or when running one as a tool. I'd prefer to use a setting over specifying this within the `.devcontainer.json` in the repository, since this configuration may differ between workstations.

Relates to: Remote - Containers

**Comment by Chuxel** [comment]
As with #1227, this sounds like microsoft/vscode-remote-release#3279 - let's keep the conversation in this issue for consistency. Thanks!!
