### ISSUE TITLE
Ruby 3.1.0

### ISSUE THREAD

**Issue by doerfli** [microsoft/vscode-dev-containers#1226]
Ruby 3.1.0 was released on December 25th 2021. I would like to use it within the ruby devcontainer. I could not figure out how to where the ruby version is defined in the devcontainer config, so i could not create a PR directly. 

Relates to: Both

**Comment by Chuxel** [comment]
Right now, it looks like installing `debase` is failing on Ruby 3.1 (but not 3.0 and below).

```
ERROR:  Error installing debase:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/debase-0.2.4.1/ext
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r ./siteconf20220104-24554-3kl4oy.rb extconf.rb
checking for vm_core.h... no
checking for vm_core.h... no
checking for vm_core.h... yes
checking for iseq.h... yes
checking for version.h... yes
checking for vm_core.h... yes
checking for vm_insnhelper.h... no
Makefile creation failed
```

It looks like installing `ruby-debug-ide` results in debase being installed anyway, so we may be able to just drop the explicit `debase` install.

**Comment by doerfli** [comment]
Is there some task i could be helping out with here? I am not really familiar with the devcontainers themselves (except for usage 😏 ), but i know my way around shell script, containers and ruby.

**Comment by Chuxel** [comment]
PR to add this has been merged, so this should go out with the next release for this repository.
