### ISSUE TITLE
Extend devcontainer.json for user customization

### ISSUE THREAD

**Issue by dariodip** [microsoft/vscode-dev-containers#1227]
It would be great if everyone could customize its editor by using a custom `devcontainer.json` file to extend the default one.

For example, let's suppose that a project has its  `devcontainer.json` including some extensions, but some users would like to use a brand new extension.  Those users would need to install manually all the extensions they want inside that Dev Container, losing all the changes as soon as they rebuild the container.

It makes sense to have another file, maybe inside the `.vscode` folder, containing all the customization of the single user that would extend the default one. 

Relates to: Remote - Containers

**Comment by Chuxel** [comment]
This sounds like https://github.com/microsoft/vscode-remote-release/issues/3279 - let's keep the conversation in this issue for consistency.  Thanks!!
