### ISSUE TITLE
dotnet ARM64 support

### ISSUE THREAD

**Issue by juzuluag** [microsoft/vscode-dev-containers#1232]
Current dotnet containers are only supporting x86. Based on some work done, `dotnet` images can be build to support arm64, but still there some dependency on Omnisharp Extension in order to have a complete user experience.
This issue was opened to track the OmniSharp dependency.

------
Testing with [Omnisharp 1.24.0-beta1](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.24.0-beta1) with various images, it was possible to debug inside the dotnet arm64 container.

```sh
Starting OmniSharp server at 1/4/2022, 9:17:03 PM
    Target: /root

OmniSharp server started with .NET 6.0.101
.
    Path: /root/.vscode-server/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0-net6.0/OmniSharp.dll
    PID: 5473

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
....
```
**Images**:
- 6.0-bullseye-slim-arm64v8 
- 5.0-bullseye-slim-arm64v8
- 3.1-bullseye-arm64v8

In case of dotnet 6.0, changes need to be added to the container's vscode settings to use 6.0 features.
```text
.vscode-server/data/Machine/settings.json
```

```json
{
	"omnisharp.useModernNet": true
}
```

Relates to: <Codespaces | Remote - Containers | Both>

**Comment by juzuluag** [comment]
Reference: https://github.com/microsoft/vscode-dev-containers/issues/558

**Comment by tksrc** [comment]
Since OmniSharp 1.24 is now released - do we expect the dotnet vscode images to be released for ARM as well?

**Comment by Chuxel** [comment]
@juzuluag I know you hit some problems with 1.24 and arm64 Linux here (which is what the container would run), correct?  Or has that been resolved since the beta?

**Comment by juzuluag** [comment]
> @juzuluag I know you hit some problems with 1.24 and arm64 Linux here (which is what the container would run), correct? Or has that been resolved since the beta?

Hi @Chuxel. I faced issues using 1.23.18-beta2 and not with 1.24.0-beta1. I haven't try the latest ([1.24.0](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.24.0))
