### ISSUE TITLE
Installation failure for latest Ruby container feature

### ISSUE THREAD

**Issue by bderusha** [microsoft/vscode-dev-containers#1235]
- VSCode Version: 1.63.2
- Local OS Version: Windows 11
- Reproduces in: Both
- Name of Dev Container Definition with Issue: script-library/ruby-debian.sh 

Steps to Reproduce:

1. Start with any Debian devcontainer.json definition
2. Add `"ruby": "latest"` to the `features` definition.
3. Build container.
4. Observe build error `ERROR:  Error installing debase`

Notes:
- The `debase` gem is made for debugging ruby 2.x
- For ruby 3.x it may be better to use the native debug https://github.com/ruby/debug and possibly this VSCode extention https://marketplace.visualstudio.com/items?itemName=KoichiSasada.vscode-rdbg

**Comment by Chuxel** [comment]
Related to #1226 

@rebornix What is your sense for what we should be doing about debugging in Ruby 3.x dev containers given the state of Ruby extensions for VS Code?

ruby-debug-ide seems to support Ruby 3.0 even though docs haven't really been updated.  Right now we're getting a bomb for 3.1.0 because explicitly installing debase fails with the stable version (while 0.2.5.beta2 works).  Installing ruby-debug-ide also installs debase so we could just do that without explicitly installing debase.

As @bderusha mentions though, 3.1.0 has the "debug" package pre-installed and the new rdbg... but there's a separate really green extension for that.

Any thoughts?

**Comment by bderusha** [comment]
@Chuxel Rails 7 has also adopted this debugger [per this PR](https://github.com/rails/rails/pull/43187).  So it does seem prudent to start to include pathways that leverage the new debugger even if it's not the default.  Could we make debugger selection a top-level argument with a note about using a different extension?

**Comment by Chuxel** [comment]
@bderusha We need to focus on the VS Code developer experience here. It is pretty common for us not to adopt something new until it is stabilized. It you look at community commentary, that extension is considered new and therefore experimental.  The base Ruby extension does not support rdbg/debug as far as I can tell at the moment.

 @rebornix was the creator of the Ruby extension, so looking for expert advice.

**Comment by rebornix** [comment]
I haven't watched up with `ruby/debug` thus didn't put up a plan to have it supported, it would require adoption and testing. Currently not on my radar but we can explore.

**Comment by Chuxel** [comment]
@rebornix Sounds good.  Sounds like for now, we should just install `ruby-debug-ide` and call it good until the alternative matures.  I don't think an explicit debase install is needed given what I saw which avoids the failure.

**Comment by quangtran-sked** [comment]
Hello @Chuxel . I tried ruby latest feature but it's still failed now. 
My devcontainer.json 
{
	"name": "Java",
	"image": "mcr.microsoft.com/devcontainers/java:0-17",

	"features": {
		"ghcr.io/devcontainers/features/java:1": {
			"version": "none",
			"installMaven": "false",
			"installGradle": "false"
		},
		"ghcr.io/devcontainers/features/node:1": {},
		"ghcr.io/devcontainers/features/ruby:1": {}
	}
}
<img width="916" alt="image" src="https://user-images.githubusercontent.com/89000266/224538559-aa5074bd-b57f-427e-acea-943d3a4d7ad1.png">
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/89000266/224538583-a0a95e17-2960-4480-90b5-5251a26f63bb.png">

Please take a look on this. 

Thanks.
