### ISSUE TITLE
Mistake in Python feature Script Use section

### ISSUE THREAD

**Issue by korompaiistvan** [microsoft/vscode-dev-containers#1242]
- VSCode Version: 1.63.2
- Local OS Version: Windows Version 10.0.18363 Build 18363
- Reproduces in: Remote - Containers (potentially codespaces as well, I don't have access)
- Name of Dev Container Definition with Issue: none

I believe there is a small error in [this section](https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/python.md#script-use).

Steps to Reproduce:

1. Open a new folder in VSCode (e.g. c:\Users\myuser\Documents\fav_project)
2. Create a .devcontainer folder within that parent folder
3. Create a minimal devcontainer.json file in the .devcontainer folder with the following content:  
```json  
{
  "name": "Ubuntu",
  "build": {
    "dockerfile": "Dockerfile",
  },
  "settings": {},
  "extensions": [
    "ms-python.python",
    "eamodio.gitlens",
    "yzhang.markdown-all-in-one"
  ],
  "remoteUser": "vscode",
  "features": {}
```
4. Create a Dockerfile in the .devcontainer folder with the following content (as instructed by the section linked above):
```Dockerfile  
FROM mcr.microsoft.com/vscode/devcontainers/base:0-focal
ARG PYTHON_PATH=/usr/local/python
ENV PIPX_HOME=/usr/local/py-utils \
    PIPX_BIN_DIR=/usr/local/py-utils/bin
ENV PATH=${PYTHON_PATH}/bin:${PATH}:${PIPX_BIN_DIR}
COPY .devcontainer/library-scripts/python-debian.sh /tmp/library-scripts/
RUN apt-get update && bash /tmp/library-scripts/python-debian.sh "3.8.3" "${PYTHON_PATH}" "${PIPX_HOME}"
```
5. Open the Command Palette of VSCode and Re/build the container.
6. See it fail with "/.devcontainer/library-scripts: no such file or directory"

The issue is that VSCode issues this build command as part of the build step
```PowerShell
docker build -f c:\Users\myuser\Documents\fav_project\.devcontainer\Dockerfile -t vsc-fav_project-somehash c:\Users\myuser\Documents\fav_project\.devcontainer
```
This sets the build context as the .devcontainer folder itself, which makes the COPY command fail, as it's looking for the .devcontainer subfolder of the .devcontainer folder which doesn't exist. 

The solution is to change the COPY command from:
```Dockerfile
COPY .devcontainer/library-scripts/python-debian.sh /tmp/library-scripts/
```
To:
```Dockerfile  
COPY library-scripts/python-debian.sh /tmp/library-scripts/
```

**Comment by Chuxel** [comment]
The default build context is `.` which resolves to the dev container as. described in https://code.visualstudio.com/docs/remote/devcontainerjson-reference.  If you prefer a different folder, add `"context": ".."` to your devcontainer.json.  Those details a preoject specific so we won't want to modify it.  This is what the [python definition does](https://github.com/microsoft/vscode-dev-containers/blob/7c52f6119adefa19c514d14a053c26239cb681d5/containers/python-3/.devcontainer/devcontainer.json#L5).

**Comment by Chuxel** [comment]
Oh wait - you're talking about the doc for the script.  Misssed that on first read.  Thanks!  Corrected.

**Comment by korompaiistvan** [comment]
cool, thank you! I closed the PR then
