### ISSUE TITLE
docker-in-docker feature /var/lib/docker mountpoint discrepancy

### ISSUE THREAD

**Issue by OhMyMndy** [microsoft/vscode-dev-containers#1249]
In commit https://github.com/microsoft/vscode-dev-containers/commit/a7f65a4b59904457629ff6a0ab64a2579c1025e2#diff-12ba14a18f0e48a55cce12c757412fd05073b26aa6cbd7af572ebbdd5d333ff7 the mounts to `/var/lib/docker` have been added to the docker-in-docker and other features. For me that is unworkable with multiple devcontainer setups which now use the same `dind-var-lib-docker` Docker volume on the host, the effect being that only the first devcontainer will run Docker successfully... The second container gets this message in `/tmp/dockerd.log`

```
time="2022-01-13T17:05:27.403834623Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
```

However, the documentation states that you need to explicitly add the volume to allow persistence of `/var/lib/docker` 
> You should update dind-var-lib-docker with a unique name for your container to avoid corruption when multiple containers write to it at the same time.

https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/docker-in-docker.md

The solution would be to remove the fixed mounts and explicitly mention in the documentation that a volume needs to be added to make it persistent.

I tried adding a new mount which uses a unique volume name, but that obviously didn't work because Docker complained about a duplicate mount point...
```json
{
"mounts": [
		"source=${localWorkspaceFolderBasename}-dind-var-lib-docker,target=/var/lib/docker,type=volume"
	],
}
``` 

Devcontainer config used:

```js
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.202.3/containers/ubuntu
{
	"name": "Ubuntu (${localWorkspaceFolder})",
	"runArgs": [
		"--init",
		"--privileged"
	],
	"build": {
		"dockerfile": "Dockerfile",
		// Update 'VARIANT' to pick an Ubuntu version: hirsute, focal, bionic
		// Use hirsute or bionic on local arm64/Apple Silicon.
		"args": {
			"VARIANT": "focal"
		}
	},
	"remoteUser": "vscode",
	"features": {
		"docker-in-docker": "stable",
		"git": "os-provided",
		"node": "lts"
	}
}

```

- VSCode Version: 1.63.2
- Local OS Version: Ubuntu 20.04
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: docker-in-docker

Steps to Reproduce:

1. Run instance vscode instance with feature docker-in-docker
2. Run another instance of a different project with feature docker-in-docker

**Comment by Chuxel** [comment]
@joshspicer @chrmarti This is due to https://github.com/microsoft/vscode-remote-release/issues/5679 not being implemented.

@OhMyMndy The extension and Codespaces need a new capability to solve this so closing this as a dupe in favor of the other issue.
