### ISSUE TITLE
SQLTools extension went "archived", should remove references to it in definitions

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#1253]
The popular https://github.com/mtxr/vscode-sqltools extension apparently is not being maintained right now (see https://github.com/mtxr/vscode-sqltools/issues/896). Its flipped its repo to "archived" and they are looking for maintainers.  Given that, we should probably remove references to it and related extensions until the situation is resolved. 😦  Unfortunatley, there does not appear to be an adequately maintained alternative today.

Instead, we can emphasize the use of port forwarding as a way to access the database.  The Mongo extension is also not in this same situation.

Remove from:
- [ ] java-postgres
- [ ] javascript-node-postgres
- [ ] python-3-postgres
- [ ] ruby-rails-postgres
- [ ] elixr-pheonix-postgres

//cc @2percentsilk @joshspicer @chrmarti

**Comment by KanishkT123** [comment]
I think this can be closed as PR #1273 ?

**Comment by Chuxel** [comment]
Yep! Closing.
