### ISSUE TITLE
$HOME as workspace

### ISSUE THREAD

**Issue by lifeiscontent** [microsoft/vscode-dev-containers#127]
I work in NodeJS a lot,

I usually use the nodejs docker image which contains the `node` user.

I usually set my projects repo pointed to the home directory of `node` e.g. `/home/node`

this allows me to forward my own .ssh credentials that I store locally in the repo directly to the home folder.

Is there a way to do this? Because I'm currently running into a ton of issues around getting a dev container setup.

**Comment by Chuxel** [comment]
Closing given it's been a few weeks and I answered above.  Please reopen if required.

**Comment by lifeiscontent** [comment]
@Chuxel could you provide some example code? I'm not familiar with the terms you're describing. I've tried setting the `workspaceFolder` and `workspaceMount` and can't seem to figure it out.

**Comment by lifeiscontent** [comment]
ping @Chuxel

**Comment by Chuxel** [comment]
@lifeiscontent The docs above cover setting the properties -- that's really all there is to it. To get more specific, I'd need to know more like what directory structure looks like in more detail and your devcontainer.json.

**Comment by Chuxel** [comment]
@lifeiscontent Also, posting any errors you are seeing would be helpful along with the OS you are on.  There are some "gotchas" for Windows with SSH keys due to how permissions work, for example.
