### ISSUE TITLE
[Announcement] State of vscode-dev-containers contributions

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-dev-containers#1291]
Hi folks! We wanted to give you the latest update on this repository.

We're currently thinking about how to best scale the growth of dev container definitions, as there's increasing interest in new definitions and configurations. This includes how to best manage existing and future community contributions. We'll be having open discussions on this in [an issue](https://github.com/microsoft/dev-container-spec/issues/7) in the new [dev container spec repo](https://github.com/microsoft/dev-container-spec/issues).

We are also evolving the idea of a dev container feature, with the goal of being better able to mix, match, and share config that can be acquired remotely. You can view and join the discussion in [this issue](https://github.com/microsoft/dev-container-spec/issues/8), and read more about features in [this doc](https://code.visualstudio.com/docs/remote/containers#_dev-container-features-preview).

Please know that we tremendously value your contributions to and usage of dev containers and their definitions! In the near-term, we'll look to accept changes in this repo with a high-priority user impact/need. For the long term, we're still discussing the best process to accept and manage contributions. Since there may be fewer responses in this repository as we figure out this plan, we wanted to make you all aware and assure you that we see and appreciate your work.

Thank you for your patience and engagement!

**Comment by bamurtaugh** [comment]
Hi folks,

Thank you again for your contributions and patience. We wanted to share the latest plans for dev container contributions.

The configuration files you see in this repo are moving over to a repo in our new `devcontainers` org, which will likely be https://github.com/devcontainers/templates. In this repo, you'll find a markdown file that lists community-contributed templates. If you'd like to add a new template, you can open a PR to this markdown file and add your repo containing a dev container configuration to the list. As there is a growing number of potential community contributions, this model provides more community autonomy and scalability.

Similar to [vscode-dev-containers](https://github.com/microsoft/vscode-dev-containers), you may also open issues and PRs to contribute to the templates that are directly managed within this new repo.

We look forward to continue making dev containers a top-notch experience, and we value your continued contributions and support. Thank you!

**Comment by samruddhikhandale** [comment]
Closing this in favor of a latest update mentioned in https://github.com/microsoft/vscode-dev-containers/issues/1589
