### ISSUE TITLE
postCreateCommand hangs when user interaction is needed

### ISSUE THREAD

**Issue by wobeng** [microsoft/vscode-dev-containers#1293]
- Version: 1.64.0 (Universal)
- Commit: 5554b12acf27056905806867f251c859323ff7e9
- Date: 2022-02-03T04:20:17.224Z
- Electron: 13.5.2
- Chromium: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Darwin x64 19.6.0
- Reproduces in: Codespaces
- Name of Dev Container Definition with Issue: mcr.microsoft.com/vscode/devcontainers/python:3.10

I have a script I added in `Dockerfile` in location `/usr/local/bin/workspace-one-time-setup.sh`. The script has a header of `#!/bin/bash -i`

In my devcontainer.json file I have `"postCreateCommand": "bash -i /usr/local/bin/workspace-one-time-setup.sh",`

In the `/usr/local/bin/workspace-one-time-setup.sh`, it auto starts sso sign-in that requires user interaction. Because of that, it keeps the script running indefinitely 

![Screen Shot 2022-02-06 at 10 42 53 AM](https://user-images.githubusercontent.com/11966846/152688774-339aa92a-b6b4-4774-987d-7a58fad6cb2e.png)

I have to view creation logs to see it's waiting for my interaction to sign me in. Is there a way I can bring it to the foreground when my interaction is needed? or better yet execute the script in the foreground

**Comment by jkeech** [comment]
There's a way to add finer-grained progress/output to that terminal output by having your `postCreateCommand` script output some specially-formatted lines to stdout with a `::step::` prefix. Would this help you out? The `View Creation Logs` is the proper way to see the full script output while it is running, but the shorter status update could be used to let the user know that they need to take some action to proceed.

Example:
```bash
echo "::step::Waiting for SSO at <url>"
```

![image](https://user-images.githubusercontent.com/746020/152704614-f0049591-be1e-4ffc-800f-95b5bf9036c2.png)

**Comment by Chuxel** [comment]
Right now user interaction during any of the automated commands is not available, so this is not related to the images in this repository.

With that in mind, for Remote - Containers I'd move it to https://github.com/microsoft/vscode-remote-release as a feature request. However, given this is related to Codespaces, I'd suggest raising a feature request at https://github.com/github/feedback/discussions/categories/codespaces-feedback

**Comment by wobeng** [comment]
@jkeech ah, I will try that..Is there any documentation for that?

@Chuxel  good point...I guess it will be better to move it to vscode remote release as a feature request

**Comment by Chuxel** [comment]
@wobeng Codespaces and Remote - Containers generally have similar capabilities, but the UX here is one area they differ. Remote - Containers does not cover up the details of the execution like Codespaces does, like Codespaces it does not allow user interaction either.

That said, in checking, there's an existing feature request for this in Remote - Containers you can up-vote here: https://github.com/microsoft/vscode-remote-release/issues/5225

It would be worth opening one in the codespaces feedback channel to track the request there. Unfortunately, I can't transfer this there myself.

Closing as a dupe - but understand the request.
