### ISSUE TITLE
PHP throwing error in the default codespaces image

### ISSUE THREAD

**Issue by Largo** [microsoft/vscode-dev-containers#1295]
PHP does not run at all in the default codespaces image. It's throwing an error in the default codespaces image.

- VSCode Version: 1.63.2
- Local OS Version:  Win 10
- Local chip architecture: x86
- Reproduces in: <Codespaces | Remote - Containers | Both> Codespaces 
- Name of Dev Container Definition with Issue: codespaces-linux

Steps to Reproduce:

1. $ php
php: error while loading shared libraries: libonig.so.4: cannot open shared object file: No such file or directory

**Comment by Chuxel** [comment]
//cc: @joshspicer

**Comment by joshspicer** [comment]
Thanks for creating an issue. Looks like similar behavior we've had in the past with python, the fix was ensure that in the upstream oryx image we had the shared libraries present at compile-time (eg: https://github.com/microsoft/Oryx/pull/1117)

Will bring this up at our next oryx sync.

**Comment by joshspicer** [comment]
context:
https://github.com/microsoft/vscode-dev-containers/issues/1006
https://github.com/github/codespaces/issues/5545

**Comment by joshspicer** [comment]
This is on oryx's and our radar, but in the meantime please feel free to use the `php` definition template we have in this repo for any php-related work in Codespaces or Remote-Containers.

**Comment by jkeech** [comment]
Closing as fixed in the latest versions of the universal image (now hosted at https://github.com/devcontainers/images/tree/main/src/universal).
