### ISSUE TITLE
docker-in-docker -> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by jsburckhardt** [microsoft/vscode-dev-containers#1298]
- VSCode Version: 1.64.1
- Local OS Version: Ubuntu 20.04.3 LTS
- Local chip architecture: x86
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: Ubuntu - feature "docker-in-docker"

Steps to Reproduce:
1. In a repo, add new devcontainer
2. Select ubuntu 
![image](https://user-images.githubusercontent.com/18494471/153109773-222f834f-15fc-40f3-8dcf-b64c45200949.png)
3. Select focal
![image](https://user-images.githubusercontent.com/18494471/153109812-a20858d7-d9df-4083-bbd7-216075205dad.png)
4. Enable docker-in-docker
![image](https://user-images.githubusercontent.com/18494471/153109854-60516ce1-43bf-4621-ba5b-3a2d25eb98aa.png)
5. Latest
![image](https://user-images.githubusercontent.com/18494471/153109887-8db1c493-e282-48ec-9a57-76fa7995c16c.png)
6. Reopen in container
![image](https://user-images.githubusercontent.com/18494471/153109938-630061b1-a53c-4afd-a7ea-689cb9d4c5dc.png)
7. In the terminal run `docker ps`
![image](https://user-images.githubusercontent.com/18494471/153110143-55f041de-8716-4d16-8b35-b86a18d789f3.png)

Note: I had the same issue with different devcontainers sources, not just Ubuntu.

**Comment by jsburckhardt** [comment]
quick update, if I set the version of the feature to `20.10` it works

**Comment by jsburckhardt** [comment]
A big old reboot fixed the issue :D. Sorry for the noise ;)

**Comment by mjpolak** [comment]
Hey, what exactly I need to reboot to make it work?
I tried to rebuild container, reconnect - but with same result.

**Comment by nick-youngblut** [comment]
I have the same issue. Rebuilding the container did not help

**Comment by Chuxel** [comment]
Hey folks - this Dev Container Feature is now maintained at https://github.com/devcontainers/features as a part of opening up the dev container spec. Please raise an issue there if you're running into challenges - there's a few there now that may or may not be related. Thanks!
