### ISSUE TITLE
Regression: go 1.17 feature breaks ubuntu focal images now that 1.17.7 released

### ISSUE THREAD

**Issue by awmcclain** [microsoft/vscode-dev-containers#1300]
- Local chip architecture: amd64
- Reproduces in: Codespaces
- Name of Dev Container Definition with Issue: ubuntu 20.04

Apparently the go version got bumped this morning -- selecting go  as a feature causes new images/rebuilds to fail.

creation log:
```
[2022-02-09T18:46:15.309Z] #6 70.36 GO_GPG_KEY_URI=https://dl.google.com/linux/linux_signing_key.pub
2022-02-09T18:46:18: #6 70.42 Downloading Go 1.17.7...
[2022-02-09T18:46:16.361Z] #6 71.36 gpg: no valid OpenPGP data found.
2022-02-09T18:46:18: #6 71.36 gpg: the signature could not be verified.
2022-02-09T18:46:18: #6 71.36 Please remember that the signature file (.sig or .asc)
2022-02-09T18:46:18: #6 71.36 should be the first file given on the command line.
[2022-02-09T18:46:18.016Z] #6 ERROR: executor failed running [/bin/sh -c cd /tmp/build-features/local-cache && chmod +x ./install.sh && ./install.sh]: exit code: 2
2
```

devcontainer.json
```

	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile",
		// Update 'VARIANT' to pick an Ubuntu version: hirsute, focal, bionic
		// Use hirsute or bionic on local arm64/Apple Silicon.
		"args": { "VARIANT": "focal" }
	},

	// Set *default* container specific settings.json values on container create.
	"settings": {},


	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [],

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	//"postCreateCommand": ".devcontainer/postcreate.sh",

	// Comment out connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "vscode",
	"features": 
		"golang": "1.17"
	}
}
```
Changing the golang version to 1.17.6 fixes.

**Comment by aidan-melen** [comment]
Same deal

**Comment by woehrl01** [comment]
Pinning it to `1.17.6` using the go-debian.sh script causes the following error:

```bash
> [linux/amd64 stage-3  6/19] RUN apt-get update && bash /tmp/library-scripts/go-debian.sh "1.17.6" "/usr/local/go" "/go" && apt-get clean -y:
#15 46.97 github.com/golangci/golangci-lint/pkg/result/processors
#15 47.12 github.com/golangci/golangci-lint/pkg/lint
#15 47.18 github.com/golangci/golangci-lint/pkg/commands
#15 47.32 github.com/golangci/golangci-lint/cmd/golangci-lint
#15 50.57 go: downloading github.com/go-delve/delve v1.8.2-0.20220210175055-dee4437bd088
#15 51.13 go install: github.com/go-delve/delve/cmd/dlv@master (in github.com/go-delve/delve@v1.8.2-0.20220210175055-dee4437bd088):
#15 51.13 	The go.mod file for the module providing named packages contains one or
#15 51.13 	more replace directives. It must not contain directives that would cause
#15 51.13 	it to be interpreted differently than if it were the main module.
#15 51.13 mv: cannot stat '/tmp/gotools/bin/dlv': No such file or directory
------
Dockerfile_Baseline:45
--------------------
  43 |       GOPATH=/go
  44 |     ENV PATH=${GOPATH}/bin:${GOROOT}/bin:${PATH}
  45 | >>> RUN apt-get update && bash /tmp/library-scripts/go-debian.sh "1.17.6" "${GOROOT}" "${GOPATH}" && apt-get clean -y
  46 |     
  47 |     #see: [microsoft/vscode-dev-containers@main/script-library/docs/sshd.md](https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/sshd.md)
--------------------
error: failed to solve: process "/bin/sh -c apt-get update && bash /tmp/library-scripts/go-debian.sh \"1.17.6\" \"${GOROOT}\" \"${GOPATH}\" && apt-get clean -y" did not complete successfully: exit code: 1
```

**Comment by aidan-melen** [comment]
> Pinning it to `1.17.6` using the go-debian.sh script causes the following error: I am uncertain if this should be tracked in a separate issue.
> 
> ```shell
> > [linux/amd64 stage-3  6/19] RUN apt-get update && bash /tmp/library-scripts/go-debian.sh "1.17.6" "/usr/local/go" "/go" && apt-get clean -y:
> #15 46.97 github.com/golangci/golangci-lint/pkg/result/processors
> #15 47.12 github.com/golangci/golangci-lint/pkg/lint
> #15 47.18 github.com/golangci/golangci-lint/pkg/commands
> #15 47.32 github.com/golangci/golangci-lint/cmd/golangci-lint
> #15 50.57 go: downloading github.com/go-delve/delve v1.8.2-0.20220210175055-dee4437bd088
> #15 51.13 go install: github.com/go-delve/delve/cmd/dlv@master (in github.com/go-delve/delve@v1.8.2-0.20220210175055-dee4437bd088):
> #15 51.13 	The go.mod file for the module providing named packages contains one or
> #15 51.13 	more replace directives. It must not contain directives that would cause
> #15 51.13 	it to be interpreted differently than if it were the main module.
> #15 51.13 mv: cannot stat '/tmp/gotools/bin/dlv': No such file or directory
> ------
> Dockerfile_Baseline:45
> --------------------
>   43 |       GOPATH=/go
>   44 |     ENV PATH=${GOPATH}/bin:${GOROOT}/bin:${PATH}
>   45 | >>> RUN apt-get update && bash /tmp/library-scripts/go-debian.sh "1.17.6" "${GOROOT}" "${GOPATH}" && apt-get clean -y
>   46 |     
>   47 |     #see: [microsoft/vscode-dev-containers@main/script-library/docs/sshd.md](https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/sshd.md)
> --------------------
> error: failed to solve: process "/bin/sh -c apt-get update && bash /tmp/library-scripts/go-debian.sh \"1.17.6\" \"${GOROOT}\" \"${GOPATH}\" && apt-get clean -y" did not complete successfully: exit code: 1
> ```

literally the same...

```
go install: github.com/go-delve/delve/cmd/dlv@master (in github.com/go-delve/delve@v1.8.2-0.20220210175055-dee4437bd088):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
mv: cannot stat '/tmp/gotools/bin/dlv': No such file or directory
The command '/bin/sh -c /bin/bash /tmp/library-scripts/go-debian.sh "${GO_VERSION}" "${GOROOT}" "${GOPATH}"' returned a non-zero code: 1
make: *** [Makefile:12: build-universal] Error 1
```

**Comment by Chuxel** [comment]
@hyangah - We're hitting a bit of a problem with a half-released version of go, but the other note here is that we've now we've now seen the github.com/go-delve/delve/cmd/dlv@master install fail a couple times with a break.  Is that still needed with the latest version of the Go extension?

**Comment by hyangah** [comment]
@Chuxel The latest vscode-go extension no longer depends on `dlv-dap` (dlv@master) so, you can remove it from the script. Thanks for handling the issue.

**Comment by Chuxel** [comment]
@awmcclain You can add a reference to the script in your Dockerfile instead until this is deployed in Codespaces. @joshspicer is working on that.  See https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/go.md

**Comment by joshspicer** [comment]
(Additionally to what Chuck has suggested, if you're using devcontainer `features`)

The cached version of this script is currently tied to a slightly slower release schedule - it should be deployed in the next day or two.  (And we're actively working on decoupling to prevent situations like this in the future!)

In the meantime you may want to try our preview functionality we're dubbing "remote feature", by changing your `features` reference from the shorthand `golang` to:
```
	"features": {
		"microsoft/vscode-dev-containers/golang": "latest"
	},
```

This will dynamically pull the very latest [`devcontainer-features.tgz` release artifact](https://github.com/microsoft/vscode-dev-containers/releases) from the vscode-dev-containers repo.

Please note this functionality is in preview and we're actively moving bits of this functionality around.  Long-term, we hope to _stop_ pre-packaging these scripts and dynamically fetch them, to alleviate situations where codespaces gets out of sync (especially when an upstream change breaks us and we want to push out fixes fast!)

![image](https://user-images.githubusercontent.com/23246594/153889287-b71d44e4-92e4-4654-bd58-3f3c5b37d9c4.png)

Example repo: https://github.com/joshspicer/codespace-features-example/tree/go
Discussions regarding features (if you want to add your thoughts): https://github.com/microsoft/dev-container-spec/issues/8

**Comment by hyangah** [comment]
fyi dlv@master build is fixed.

**Comment by Chuxel** [comment]
Closing since the core situation has been resolved and we've got updated scripts to handle something happening down the road. Thanks!
