### ISSUE TITLE
Using "features": { "golang": "1.16" } fails with "no valid OpenPGP data found"

### ISSUE THREAD

**Issue by brianmhunt** [microsoft/vscode-dev-containers#1301]
- VSCode Version: 1.64.1
<img width="991" alt="image" src="https://user-images.githubusercontent.com/135528/153472665-98becadc-5020-4829-87d8-01f791450b0a.png">
- Reproduces in: Codespaces
- Name of Dev Container Definition with Issue: features.golang

Steps to Reproduce:

The fastest reproduction is as follows:

1. wget https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/go-debian.sh
2. sudo bash ./go-debian.sh "1.16" "/usr/local/go" "/go"

The easiest reproduction is to include `"golang": "1.16"` in the code.

Both error with:

```
...
Preparing to unpack .../pkg-config_0.29.1-0ubuntu4_amd64.deb ...
Unpacking pkg-config (0.29.1-0ubuntu4) ...
Setting up libdpkg-perl (1.19.7ubuntu3) ...
Setting up pkg-config (0.29.1-0ubuntu4) ...
Processing triggers for man-db (2.9.1-1) ...
TARGET_GO_VERSION=1.16.14
GO_GPG_KEY_URI=https://dl.google.com/linux/linux_signing_key.pub
Downloading Go 1.16.14...
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
```

This occurs with this vanilla devcontainer:

```docker
FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu-20.04
```

Removing `"golang"` from the `features` section and the container builds correctly.  Golang can then be installed in a usual way.

**Comment by woehrl01** [comment]
I have the same issue for "latest". See also here: https://github.com/github/feedback/discussions/11262

**Comment by chrmarti** [comment]
Publishing Remote-Containers 0.221.0-pre-release including this fix and the one for #1300. Not sure if we expect this to be fixed upstream soon. Let me know if we need this in a regular release and the CLI for Codespaces too.

**Comment by joshspicer** [comment]
As codespaces depends on the pre-packaged scripts right now, would be nice to get a CLI update out @chrmarti

**Comment by Chuxel** [comment]
@chrmarti @joshspicer We still seem to be seeing the problem with `dlv-dap` 24 hrs later, so I think it is probably worth doing a release to resolve that issue given the Go extension no longer requires it.  1.17.7 and 1.16.14 are out now, but we got hit with two upstream problems on the same day. 🙁

I noticed an issue with the updated script that I just fixed. So ideally we'd do another rev of the vscode-dev-containers repos and do a release.  Agreed.

**Comment by brianmhunt** [comment]
> Change to 1.16.13 for the version. This looks like the same problem as https://github.com/microsoft/vscode-dev-containers/issues/1300. There appears to be a rough release getting out for these latest updates.

@Chuxel  I'm sure this is known/obvious, but just confirming that using `"golang": "1.16.13"` yields a different error from the one reported here (i.e. the problem reported in #1300):

> [2022-02-11T17:42:45.151Z] #7 116.3 mv: cannot stat '/tmp/gotools/bin/dlv': No such file or directory

Great to see the quick attention to this, thanks to all.  I'm curious what the ordinary turnaround time is for this sort of issue, but don't want to pester (or hold anyone to anything). 😁

**Comment by Chuxel** [comment]
@brianmhunt Yes, that's the second issue I mention with `dlv-dap`. It also broke yesterday.  If you're using the script directly, you can just remove this section per https://github.com/microsoft/vscode-dev-containers/issues/1300#issuecomment-1035595700

Remove:
```bash
go ${go_install_command} -v github.com/go-delve/delve/cmd/dlv@master 2>&1 | tee -a /usr/local/etc/vscode-dev-containers/go.log
mv /tmp/gotools/bin/dlv ${TARGET_GOPATH}/bin/dlv-dap
```

We're currently working on getting a release out despite being an upstream problem given its disruptive. Remote - Containers should update quickly. @joshspicer is working with the Codespaces team as well to get updates there without disrupting anything.

**Comment by brianmhunt** [comment]
I can confirm that this appears to be fixed i.e. codespaces now rebuild as expected.

**Comment by Chuxel** [comment]
Excellent! Closing.
