### ISSUE TITLE
"New Class" from "C# Extensions" doesn't work in a container.

### ISSUE THREAD

**Issue by turowicz** [microsoft/vscode-dev-containers#131]
I know this repository is only meant for the containers definition issues, but I can't find a repo for the actual extension.

Version: 1.39.0-insider
Commit: 9f6a745027fc7b2a12495970f64625e24f410224
Date: 2019-09-24T05:24:32.949Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Start VS
2. Open a folder with a tree-like structure of subfolders with code files in them.
3. Try adding "New C# File" to a subfolder.

Expected: New file with correct namespace and name.
Result: Nothing happens.

Cheers

**Comment by turowicz** [comment]
PS the extension works fine without the container context.

**Comment by Chuxel** [comment]
@turowicz Is this about VS or VS Code? For VS, please use the "Report a Problem" feature as these issues are not tracked in GitHub.

![image](https://user-images.githubusercontent.com/312252/65783684-239ba600-e105-11e9-9c16-c2c002804828.png)

**Comment by Chuxel** [comment]
Also - If you are referring to the "C# Extensions" extension and your mention of "VS" above was an errort, it's repo is here: https://github.com/jchannon/csharpextensions

However, the author seems to have abandoned it.

This variant seems to be a fork of it: https://marketplace.visualstudio.com/items?itemName=mavis.csharpextensions

Repo: https://github.com/Venipa/csharpextensions

I'd try raising an issue there.

**Comment by turowicz** [comment]
@Chuxel yes I refer to the VS Code extension. I understand it was discontinued but it is still being used by plenty of people and there is no alternative. The problem is that the original C# extension doesn't give this functionality and we have to look somewhere else.

Regardless, it doesn't work in containers. Please understand that it impacts the use of your extension.
