### ISSUE TITLE
NPM versus YARN - please move to yarn

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-dev-containers#1311]
The devcontainer.json for Node and Node + Mongo still has yarn as the commented out install step. When can this change to NPM?

**Comment by Chuxel** [comment]
Yarn and npm are both are in the image.  That is just illustrating one thing you can do.

**Comment by bamurtaugh** [comment]
Thanks for opening @diberry. Closing out this issue as it's still labeled `needs-more-info`, but please let us know if you have other thoughts on the above, and happy to reopen.
