### ISSUE TITLE
Difference in behavior between string and array syntax for lifecycle scripts

### ISSUE THREAD

**Issue by D1no** [microsoft/vscode-dev-containers#1315]
Hi

the [documentation](https://code.visualstudio.com/docs/remote/devcontainerjson-reference) states that an array can be used.
![image](https://user-images.githubusercontent.com/2397125/154939784-e1e399da-4ac7-4715-9506-5df046f4bbcc.png)

So this works as a `string`
```js
	// devcontainer.json
	"postCreateCommand": "npm install --global nx && yarn install",
```

But fails as an `array`
```js
	// devcontainer.json
	"postCreateCommand": [
		"npm install --global nx",
		"yarn install"
	],
```

with `not found in $PATH`
```bash
[9074 ms] Start: Run in container: npm install --global nx yarn install
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "npm install --global nx": executable file not found in $PATH: unknown
[9449 ms] postCreateCommand failed with exit code 126. Skipping any further user-provided commands.
```

- VSCode Version: 1.64.2 (Universal), Commit: f80445acd5a3dadef24aa209168452a3d97cc326
- Local OS Version: MacOS Monterey 12.2.1
- Local chip architecture: Apple Silicon
- Reproduces in: Remote - Containers (v0.217.4)
- Name of Dev Container Definition with Issue: All / Node.js & TypeScript

Steps to Reproduce:

1. Create an empty folder
2. Add a `.devcontainer/devcontainer.json`
3. With the content:

```js
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.217.4/containers/typescript-node
{
	"name": "Node.js & TypeScript",
	"build": {
		"dockerfile": "Dockerfile",
		"args": {
			"VARIANT": "16-bullseye"
		}
	},
	// Use 'postCreateCommand' to run commands after the container is created.
	"postCreateCommand": [
		"npm install",
		"yarn install"
	],
	// Comment out to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "node"
}
```
4. And a `.devcontainer/Dockerfile`
5. With the content:

```dockerfile
# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.217.4/containers/typescript-node/.devcontainer/base.Dockerfile

# [Choice] Node.js version (use -bullseye variants on local arm64/Apple Silicon): 16, 14, 12, 16-bullseye, 14-bullseye, 12-bullseye, 16-buster, 14-buster, 12-buster
ARG VARIANT="16-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-${VARIANT}
```

6. Open the folder with VS Code Remote Dev Container

**Comment by Chuxel** [comment]
The array syntax executes without a shell. That does not appear to work for npm, which is what is causing the error.

https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_formatting-string-vs-array-properties

> An array is passed to the OS for execution without going through a shell, whereas a string goes through a shell (it needs to be parsed into command and arguments).

**Comment by D1no** [comment]
Ehm, maybe document that in the API sheet? RTFM is a pretty poor reason if string and array are listed next to each other but have different behavior. Thanks

**Comment by bamurtaugh** [comment]
Thanks for looping me in! I opened https://github.com/microsoft/vscode-docs/pull/5197.
