### ISSUE TITLE
Go: cannot install packages with "go get" in dev container

### ISSUE THREAD

**Issue by ItalyPaleAle** [microsoft/vscode-dev-containers#1319]
The Dockerfile for Go has an example for installing other packages with "go get" (which, by the way, should probably be replaced with "go install" now): https://github.com/microsoft/vscode-dev-containers/blob/main/containers/go/.devcontainer/Dockerfile#L15

However, that doesn't seem to work and it always fails with an error `/bin/sh: 1: go: not found`

Investigating further, it seems that this is a complicated issue.

The `go-debian.sh` script installs the required environmental variables (`$GOROOT`, `$GOPATH`, and updating `$PATH`) in the file `/etc/bash.bashrc`, at the end.

However, at the beginning of the file (at least in Debian 11) there's this line:

```sh
# If not running interactively, don't do anything
[ -z "$PS1" ] && return
```

When running a "docker build" environment, it's a non-interactive shell, so the rc file exists before setting the variables required to run go commands. And that's why we can't add more Go packages in the Dockerfile.

**Comment by Chuxel** [comment]
@ItalyPaleAle We'll have to look - those were historically set via `ENV` in the upstream base go image.
