### ISSUE TITLE
azure-functions-dotnetcore-latest does not build

### ISSUE THREAD

**Issue by allanwright** [microsoft/vscode-dev-containers#132]
azure-functions-dotnetcore-latest fails to build with the following error:

**Unable to locate package azure-functions-core-tools**

[build image.txt](https://github.com/microsoft/vscode-dev-containers/files/3660406/build.image.txt)

- VSCode Version:1.38.1 and 1.39.0-insider
- Local OS Version: Windows 10 version 1903 (OS Build 18362.356)
- Name of Dev Container Definition with Issue: azure-functions-dotnetcore-latest

Steps to Reproduce:

Prereqs - remote (containers) extension and docker.

1. Open an empty folder in vscode.
2. Run 'Remote Containers: Add Development Container Configuration Files...' command and select 'Azure Functions and C# (.Net Core Latest)'.
3.  Reopen folder in container.

I've compared the Dockerfile and devcontainer.json between azure-functions-dotnetcore-2.1 and azure-functions-dotnetcore-latest and the only difference is the base image referenced in each Dockerfile.  Could this be related to [.NET Core `latest` Docker tags updated to 3.0](https://github.com/dotnet/dotnet-docker/issues/1337) given that azure functions doesn't yet support .Net core 3.0?

**Comment by Chuxel** [comment]
Good catch - in the case of the Azure functions containers, we may need drop the "Latest" versions of the .NET ones and just go with specific versions as they're supported.

**Comment by Chuxel** [comment]
@allanwright If you update the FROM statement in the Dockerfile to reference `2.2` instead of `latest`, does it work for you?

**Comment by Chuxel** [comment]
Fixed with https://github.com/microsoft/vscode-dev-containers/commit/c415c961f7d9d303f994e974250153a483bf7a8f

//cc @chrmarti

**Comment by allanwright** [comment]
Thanks @Chuxel, builds just fine now!
