### ISSUE TITLE
dart: command not found

### ISSUE THREAD

**Issue by weenzeel** [microsoft/vscode-dev-containers#1336]
- VSCode Version: 1.65.0
- Local OS Version: MacOS 12.1
- Local chip architecture: x86
- Reproduces in: Only tried Remote - Containers
- Name of Dev Container Definition with Issue: Dart

Steps to Reproduce:

1. Open a new folder in remote container.
2. Run terminal command "dart" inside container.

Result:
"dart: command not found"

**Comment by Chuxel** [comment]
This appears to be an upsteam bug with the dart image. https://github.com/dart-lang/dart-docker/pull/65#issuecomment-1009557777 and https://github.com/dart-lang/sdk/issues/47093

I pushed an update to the Dockerfile to fix the privs in the mean time. 

For an existing Dockerfile, just add this:

`RUN chmod 755 "$DART_SDK" "$DART_SDK/bin"`

**Comment by weenzeel** [comment]
Question. The fix works if I implement it manually in a docker file. But when I pull templates via the native option in Visual Studio Code to create a new developer env I get the old version without the fix. Shouldn't your changed file be pulled in per default by Visual Studio Code? Ping @Chuxel

**Comment by Chuxel** [comment]
Yep this will go with the next release.

**Comment by weenzeel** [comment]
Ah ok. Thought changes were live as soon as landed in this repo. Thanks.

**Comment by weenzeel** [comment]
@Chuxel The conversation above solved the problem of running the Dart executable in the dart dev container.

To create an application with hot reload capabilities I also needed to add permissions to the $DART_SDK/bin/resources folder. Perhaps this is something that should be included in the base image in this repository.

The Dart dev tools are in the resources folder.
