### ISSUE TITLE
Question about LXC in docker-in-docker-debian.sh

### ISSUE THREAD

**Issue by Hazmi35** [microsoft/vscode-dev-containers#1338]
Sorry if this isn't the right place to ask this, because `SUPPORT.md` doesn't mention any questions like this.

https://github.com/microsoft/vscode-dev-containers/blob/73ebc9dd15686790e75fe6346204e580466f711b/script-library/docker-in-docker-debian.sh#L115

Isn't LXC not needed anymore for Docker? especially newer Docker versions which moves to runC (formerly libcontainers). Or is there something I missed in this script?

**Comment by Chuxel** [comment]
We can take a look. This script has been around for a while so it may no longer be required.
