### ISSUE TITLE
Go 1.18 release broke fallback logic for go script

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#1339]
The go script does not properly handle a scenario where a version number for a Go release does not include a breakfix version number - e.g. the release here is 1.18, not 1.18.0.

As a workaround, set the version number to `1.17.8` for now.

**Comment by Chuxel** [comment]
Fixed in https://github.com/microsoft/vscode-dev-containers/commit/c694b3cfe0551cc4da2315ba9ffbd8aa78d1db6e

Leaving open until release.

**Comment by jbreiding** [comment]
I am using a copy of the script from main at the moment.

As of today there is a tag for `1.18.1` on the git repo, but no corresponding release.

The script is terminating with the 404 because the release binary does not exist.

I imagine there might be some latency between tagging the repo and release artifacts making it to the official downloads.

**Comment by Chuxel** [comment]
For some reason `((breakfix=breakfix-1))` is causing the script to exit with `set -e` in the fallback logic.  No idea why.  Will work on a fix.

**Comment by jbreiding** [comment]
> For some reason `((breakfix=breakfix-1))` is causing the script to exit with `set -e` in the fallback logic. No idea why. Will work on a fix.

I was about to start tinkering locally with this, happy to offer any help.

**Comment by jbreiding** [comment]
So maybe I am too quick here, your PR did work for me locally.

Thanks for being so responsive.

**Comment by Chuxel** [comment]
@jbreiding Perfect! Was just about to ask.  Will merge.

**Comment by Chuxel** [comment]
PR has been merged, so if you are using a copy of the script, you can grab the latest from "main".  https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/go-debian.sh

For use in features, you can reference this repository's copy of the feature while it is released in Remote - Containers and Codespaces.

```
"features": {
    "microsoft/vscode-dev-containers/golang@v0.231.6": "latest"
}
```

**Comment by Chuxel** [comment]
Resolved a while ago.
