### ISSUE TITLE
Consider switching F# definitions to use fsharp image instead of .NET Core

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#134]
Currently the F# dev containers start with the base .NET Core SDK image and then installs F#. While this works fine, it leads to longer build times with an unclear benefit.

We can investigate using https://hub.docker.com/_/fsharp image as a base instead to see if this provides a better starting point.  We'd need to change the versioning away from .NET Core's versions and to F# with this change.

**Comment by cartermp** [comment]
The `fsharp` image is a superset of the .NET Core image in a way - it bundles .NET Core and Mono. I think that it'd be better to just stick with the .NET Core images given that the F# community trending away from Mono.

**Comment by Chuxel** [comment]
Thanks for the feedback. I have been thinking the same thing as time has gone on. I’ll close this for now.
