### ISSUE TITLE
Consider including details on sharing SSH keys for Git in definitions

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#135]
While https://github.com/microsoft/vscode-remote-release/issues/106 is the real fix for this issue, we provide guidance on how to [copy SSH keys into your container for use with git here](https://code.visualstudio.com/docs/remote/containers#_sharing-git-credentials-with-your-container).

We could include a simple script in the base dev containers that execute these steps and a postCreateCommand and mount point in devcontainer.json either by default, or can be un-commented in the mean time.

**Comment by Chuxel** [comment]
This is no longer needed given we have first class support for SSH agent forwarding.

**Comment by PavelSosin-320** [comment]
@Chuxel Sorry! Could you explain in the details what is it First-class support? 
Do you mean that ssh client and git work via bridge network of the container host? So you have no problems with the host firewall. Is it really independent of the container's network driver? I tried it with the official alpine/git container and it was not too easy.
I also didn't find any documentation about how to inject credentials into the container in a secure manner. I familiar with this issue without storing it in the image and making it available for everybody who can access images or containers via plane docker -H host image/container inspect.

**Comment by Chuxel** [comment]
See https://code.visualstudio.com/docs/remote/containers#_using-ssh-keys

**Comment by zioalex** [comment]
Hi @Chuxel , I think this way is not good enough. Not everybody has Administrator access to run the agent on the Windows host.
Please can you provide a good way to copy the ssh key in the container?

At the moment trying to copy it with:
USER vscode 
COPY ./ssh_config_dir/id_rsa /home/vscode/.ssh/id_rsa

produce the follow error:
```
[37057 ms] /bin/sh: 35: cannot create /home/vscode/.ssh/known_hosts: Permission denied
[37057 ms] Exit code 2
[37063 ms] Command in container failed: # Copy C:\Users\S0VP8H\.ssh\known_hosts to /home/vscode/.ssh/known_hosts
(dd iflag=fullblock bs=8192 count=0 2>/dev/null; dd iflag=fullblock bs=7821 count=1 2>/dev/null) >/home/vscode/.ssh/known_hosts
```

**Comment by hpe-ykoehler** [comment]
What about ssh "known_hosts"?
