### ISSUE TITLE
Moby fails to install on ubuntu 21.04-based definitions

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode-dev-containers#1367]
To Repro:

1. In Remote-Containers or Codespaces, select the C++ definition based on ubuntu 21.04.
2. Add the `docker-in-docker` feature on `latest`.  Moby will == true by default
3. Rebuild, see error.

<img width="878" alt="image" src="https://user-images.githubusercontent.com/23246594/158597147-c555f34b-d5d4-4548-8698-3639ed81bf62.png">

If I set the base definition image to ubuntu 20.04, did not see this happen in codespaces.

**Comment by joshspicer** [comment]
line in script: https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docker-in-docker-debian.sh#L185

**Comment by Chuxel** [comment]
We should trap and provide a better error since this distro version is not supported. 22.04 is about to come out as well which is the new LTS so the same thing will happen for a while.

**Comment by joshspicer** [comment]
while it seems moby isn't offered by docker in 21.04, docker itself should be
https://docs.docker.com/engine/install/ubuntu/
![image](https://user-images.githubusercontent.com/23246594/158651015-9245fb61-d5f6-4a62-bd93-f2e5885361e6.png)

**Comment by Chuxel** [comment]
Cool - We can trap each separately then.  Automatically switching has licensing implications, so we should error and then suggest updating.

**Comment by joshspicer** [comment]
> Cool - We can trap each separately then. Automatically switching has licensing implications, so we should error and then suggest updating.

On it !

**Comment by Chuxel** [comment]
Just as a quick follow up. Ubuntu 22.04 Jammy is slated to release on April 22nd. Hopefully the MS feeds will have the latest by then -- it's apparently in progress.

We'll stop building "impish" at this point given its already out of support.  Latest is still set to `focal`, so this only applies if you're pinning to this OS version.
