### ISSUE TITLE
go: remove use of "go.goroot" setting and GOROOT env vars

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode-dev-containers#1368]
It seems like `go.goroot` setting is set to `/usr/local/go` or `GOROOT` env var is set when I start Codespace. 
Go usually chooses the appropriate `GOROOT`. Thus, nowadays, the best practice is not to touch `GOROOT` env var except some rare cases. For Go extension users, we recommend users to configure their `PATH` to include the path to the Go binary or use `"go.alternateTools": { "go": ... }` settings and avoid `"go.goroot"` that sets `GOROOT` env var if possible.

 
Is it possible to remove the use of "go.goroot" or GOROOT env setting that affects Codespace environment?

I don't know which one of the settings in https://github.com/microsoft/vscode-dev-containers/search?q=go.goroot is relevant to my Codespace experience.

**Comment by Chuxel** [comment]
//cc @joshspicer @jkeech - this would need to be updated to the settings applied to the default kitchen sink image in Codespaces.

We can remove it from all these other locations if that's best practice. Go should already be in the PATH in all cases.  I assume that its still appropriate to set GOPATH?

**Comment by joshspicer** [comment]
For codespaces that don't supply their own devcontainer.json, we supply a default set.  I've put up a PR to remove `go.goroot` 👍

**Comment by Chuxel** [comment]
Removed it from the other spots when I merged in 1.18.  @joshspicer do you want to keep this open for the codespaces change that's not in this repo?

**Comment by joshspicer** [comment]
PR has been merged on our end, will hit prod soon - we can close this.
