### ISSUE TITLE
Python 3.9 in the default Linux container

### ISSUE THREAD

**Issue by fwcd** [microsoft/vscode-dev-containers#1370]
It would be cool to have Python 3.9 or higher available in the [default Linux container](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/codespaces-linux) (currently it's 3.8).

Relates to: Codespaces

**Comment by Chuxel** [comment]
//cc @joshspicer

**Comment by joshspicer** [comment]
@samruddhikhandale @edgonmsft @bratsche - would one of you want to give this a go?  Might be a nice exercise for familiarizing for new-kitchensink

**Comment by joshspicer** [comment]
RIght now we pass `none` to the python-debian script, so looks like we just utilize what oryx is giving us.  We can strategically use the installation from our scripts, if we want.

- https://github.com/microsoft/vscode-dev-containers/blob/main/containers/codespaces-linux/.devcontainer/base.Dockerfile#L75
- https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/python-debian.sh#L288

**Comment by fwcd** [comment]
Looks like Python 3.10 is shipped now.
