### ISSUE TITLE
Solve containers hostname DNS out-the-box on operation sysem

### ISSUE THREAD

**Issue by felinto-dev** [microsoft/vscode-dev-containers#1374]
Hey there! 😁

Because Microsoft Edge is a Microsoft product, what do you think about giving support to resolve dev container hostnames out-of-the-box? Something like type the container hostname on Microsoft Edge and don't need need to do port binding on dev environment.

I guess could be interesting this works for other applications like Postman too.

Relates to: Remote - Containers

**Comment by bamurtaugh** [comment]
Going to close out this issue as it's still `needs-more-info`. 

@felinto-dev if you have any feedback based on the above, please just let us know, and happy to reopen. Thank you!
