### ISSUE TITLE
Create command for open project in dev container

### ISSUE THREAD

**Issue by felinto-dev** [microsoft/vscode-dev-containers#1375]
Today is possible to open a VS Code project with `code .` >> Rebuild in container

What about creating a new command to open the dev container directly?

Something like: `vsdev .`

Or another way to open a folder in dev container in 1-click, anyway

**Comment by Chuxel** [comment]
There's a dev container CLI that allows you to open VS Code already. https://code.visualstudio.com/docs/remote/devcontainer-cli#_install-using-vs-code

If you're thinking about using it directly from the command line, we're also looking into that.  See https://github.com/microsoft/dev-container-spec/issues/9

Out of curiosity, what is the scenario you're looking to solve?

**Comment by bamurtaugh** [comment]
Going to close out this issue as it's still labeled `needs-more-info`. 

@felinto-dev if you have any other questions or feedback based on the above, please let us know, and happy to reopen. Thank you!
