### ISSUE TITLE
Pulling the pre build docker images from private repository when building dev container

### ISSUE THREAD

**Issue by VikramAIS** [microsoft/vscode-dev-containers#1382]
Hi Team,

I am trying to build the dev container with images placed in Azure Container Registry ( Private Repository). Please let us know how to authenticate to pull the image from the private repo while building dev container.

I am using both ways to build the dev container

1.  Cloning locally and opening folder in dev container
2.  Cloning the repo in container volume.

Thanks,
Vikram

**Comment by Chuxel** [comment]
Assuming you are using Remote - Containers, use the docker CLI or Azure CLI to authenticate against the registry.  Or for Codespaces, see https://docs.github.com/en/codespaces/codespaces-reference/allowing-your-codespace-to-access-a-private-image-registry

**Comment by Chuxel** [comment]
@VikramAIS You do this from the command line as you would normally. See the Azure documentation for details. https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-login
