### ISSUE TITLE
Create devcontainers for popular repos

### ISSUE THREAD

**Issue by bowdenk7** [microsoft/vscode-dev-containers#14]
This issue is meant to be a hit list of repos that we want to have devcontainers for and any known issues associated with getting those setup. 

For the most part these are the most forked repos on GitHub as well as some other notable projects.

| Repo | Owner  | Done | Tested | Known Issues  |
|---|---|---|---|---|
| [Angular](https://github.com/angular/angular) | @bowdenk7 | Yes  | No  |   |
| [Bootstrap](https://github.com/twbs/bootstrap)  | @bowdenk7 |  No |   | Getting a headless browser setup in docker is hard |
| [three.js](https://github.com/mrdoob/three.js)  |   |   |   |
| [jekyll-now](https://github.com/barryclark/jekyll-now) | @mjbvz | Yes  |  |
| [TensorFlow-Examples](https://github.com/aymericdamien/TensorFlow-Examples)| @mjbvz | Yes  |  |  |
| [Learn OpenCV](https://github.com/spmallick/learnopencv)| @mjbvz | Yes |  |  |
| [TensorFlow-Tutorials](https://github.com/Hvass-Labs/TensorFlow-Tutorials)| |  |  | Requires jupyter notebooks  |
| [Jekyll](https://github.com/jekyll/jekyll)| @rebornix |  |  |  |
| [D3](https://github.com/d3/d3) |  |  |  |
| [Vue](https://github.com/vuejs/vue) |  |  |  |
| [Spark](https://github.com/apache/spark) |  |  |  | 
| [Animate.css](https://github.com/daneden/animate.css) |  |  |  | 
| [Lantern](https://github.com/getlantern/lantern) |  |  |  | 
| [Golang](https://github.com/golang/go) |  |  |  |  
| [Darknet](https://github.com/pjreddie/darknet) |  |  |  | 
| [Flask](https://github.com/pallets/flask) |  |  |  | 
| [ElasticSearch](https://github.com/elastic/elasticsearch) |  |  |  | 
| [Swift](https://github.com/apple/swift) |  |  |  | 
| [ASP.NET Core](https://github.com/aspnet/AspNetCore) |  |  |  | 
| [Redis](https://github.com/antirez/redis) |  |  |  | 
| [Ghost](https://github.com/TryGhost/Ghost) |  |  |  |

**Comment by bhack** [comment]
I want to add official tensorflow/addon devcontainer cause it is the main official entry point to extend Tensorflow for community contributions. 
I am waiting to better have an overview of a comprehensive Dockerfile receipt to code, build and run test for that repo. 
Check https://github.com/tensorflow/addons/issues/1305

**Comment by manandre** [comment]
Hello, I am working on devcontainer support in the [npgsql/npgsql](https://github.com/npgsql/npgsql) repo (the .NET data provider for PostgreSQL).
I would need some help to solve a port forwarding issue.
See npgsql/npgsql#2972 for details.

**Comment by AarynSmith** [comment]
I working on submitting a PR #395 for a Vue container now.

**Comment by Chuxel** [comment]
Closing this as we've been tracking elsewhere.
