### ISSUE TITLE
[Docs] Update Docker-in–Remote Containers bind mount instructions

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-dev-containers#1402]
I tried this: [Supporting bind mounts from the workspace folder](https://github.com/microsoft/vscode-dev-containers/blob/7bf963ae60851baf677e711db15f8493bd4a3d34/script-library/docs/docker.md#remote---containers)

> A common question that comes up is how you can use `bind` mounts from the Docker CLI from within the Codespace itself (e.g. via `-v`). The trick is that, since you're actually using Docker sitting outside of the container, the paths will be different than those in the container. You need to use the **host**'s paths instead.

> Add the following to `devcontainer.json`:
> 
> ```json
> "remoteEnv": { "LOCAL_WORKSPACE_FOLDER": "${localWorkspaceFolder}" }
> ```
> 
> Then reference the env var when running Docker commands from the terminal inside the container.
> 
> ```bash
> docker run -it --rm -v ${LOCAL_WORKSPACE_FOLDER}:/workspace debian bash
> ```

I tried this, and it didn't work - `LOCAL_WORKSPACE_FOLDER` was always empty.

Then I discovered this: https://github.com/microsoft/vscode-remote-release/issues/6160#issuecomment-1014701007

> There is no `${localWorkspaceFolder}` when using "Clone Repository in Container Volume".

Damn.

I don't want to mess around with named volumes, so I'm assuming based on that issue I just linked, I won't be able to bind mount from the workspace folder using Docker-in-Docker?

If so, the docs could probably benefit from that clarification; or, maybe there's some other solution.

**Comment by bamurtaugh** [comment]
Thanks @aaronadamsCA. I've opened https://github.com/microsoft/vscode-dev-containers/pull/1411 to update this.
