### ISSUE TITLE
Fish script is failing regression testing

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#1404]
Currently if you run the `fish-debian.sh` script on the `debian:buster` image it appears to fail with a key error. 

Example regression test run:  https://github.com/microsoft/vscode-dev-containers/runs/5998005119?check_suite_focus=true

```
#9 54.41 **** Testing /script-library/fish-debian.sh ****
#9 54.41 Using defaults...
#9 54.43 Installing fish shell...
#9 54.43 deb http://download.opensuse.org/repositories/shells:/fish/Debian_10/ /
#9 54.94 
#9 54.94 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#9 54.94 
#9 55.00 Hit:1 http://deb.debian.org/debian buster InRelease
#9 55.00 Hit:2 http://security.debian.org/debian-security buster/updates InRelease
#9 55.00 Hit:3 http://deb.debian.org/debian buster-updates InRelease
#9 55.02 Hit:4 https://packages.microsoft.com/repos/azure-cli buster InRelease
#9 55.25 Get:5 http://download.opensuse.org/repositories/shells:/fish/Debian_10  InRelease [1535 B]
#9 55.43 Err:5 http://download.opensuse.org/repositories/shells:/fish/Debian_10  InRelease
#9 55.43   The following signatures were invalid: EXPKEYSIG 2CE2AC08D880C8E4 shells:fish OBS Project <shells:fish@build.opensuse.org>
#9 55.44 Reading package lists...
#9 56.02 W: GPG error: http://download.opensuse.org/repositories/shells:/fish/Debian_10  InRelease: The following signatures were invalid: EXPKEYSIG 2CE2AC08D880C8E4 shells:fish OBS Project <shells:fish@build.opensuse.org>
#9 56.02 E: The repository 'http://download.opensuse.org/repositories/shells:/fish/Debian_10  InRelease' is not signed.
#9 ERROR: process "/bin/sh -c bash /script-library/test/regression/run-scripts.sh /script-library true ${USERNAME} ${RUN_COMMON_SCRIPT} ${UPGRADE_PACKAGES} ${RUN_ONE}" did not complete successfully: exit code: 100
```

I've commented this out of the regression test script to not block other updates, but @eitsupi @andreiborisov do you see this also?  If so could you contribute the right fix?

**Comment by andreiborisov** [comment]
@Chuxel It seems they've updated the links, thank you for bringing my attention to it! I will prepare a PR this week.

**Comment by eitsupi** [comment]
It appears that the problem is not with the script but with the expiration of the key.
See fish-shell/fish-shell#8869

**Comment by sarisia** [comment]
As I stated in https://github.com/fish-shell/fish-shell/issues/8869#issuecomment-1098694652,
the GPG key for `shells:fish:release:3` repo is updated, while `shells:fish` is not.

How about updating the install script to use `shells:fish:release:3`, which is a officially maintained repository
documented in fishshell.com, instead of the current `shells:fish`?

**Comment by eitsupi** [comment]
Yes, we used to use the fish release 3 addresses, but I changed them in #1222 without understanding the difference...
We need to change it back.

**Comment by eitsupi** [comment]
In the process of testing the script for #1409, I also noticed another bug and fixed it together.
(Installation fails with predefined ubuntu image)
This may be the problem that @andreiborisov was referring to in https://github.com/microsoft/vscode-dev-containers/pull/1263#issuecomment-1092889770.
