### ISSUE TITLE
NVS fails to install in codespaces-linux image

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#1405]
CI failed when trying to install "nvs" in the codespaces-linux image for some reason. 

See https://github.com/microsoft/vscode-dev-containers/runs/5999818611?check_suite_focus=true

I backed the version number down to what is already released (1.7.5) for v0.231.6.  (https://github.com/microsoft/vscode-dev-containers/commit/6a723ddef0f80dfcffdddff79efd05b657207485)

Bump back up to 1.7.6 when it's ready to go.

**Comment by joshspicer** [comment]
This is due to the new changes in `git`.  Should be fixed!
