### ISSUE TITLE
Codebug

### ISSUE THREAD

**Issue by Brad1980ford** [microsoft/vscode-dev-containers#1412]
- VSCode Version:
- Local OS Version:
- Local chip architecture: <x86, arm64, Apple Silicon>
- Reproduces in: <Codespaces | Remote - Containers | Both>
- Name of Dev Container Definition with Issue:

Steps to Reproduce:

1.
2.

**Comment by bamurtaugh** [comment]
If you have a bug or feature request, please let us know by completing the issue template. Thank you!
