### ISSUE TITLE
Proof 

### ISSUE THREAD

**Issue by Brad1980ford** [microsoft/vscode-dev-containers#1413]
https://github.com/microsoft/vscode-dev-containers/tree/main/containers%2Fcodespaces-linux%2Ftest-project

**Comment by bamurtaugh** [comment]
If you have a bug or feature request, please let us know. Thank you!

**Comment by Brad1980ford** [comment]
- - - [ ] # > ~~@~~

**Comment by Brad1980ford** [comment]
- - - [ ] # > ~~@~~

**Comment by Brad1980ford** [comment]
- - - [ ] # > ~~@~~

**Comment by Brad1980ford** [comment]
- - - [ ] # > ~~@~~

**Comment by Brad1980ford** [comment]
- - - [ ] # > ~~@~~ newsy
