### ISSUE TITLE
Missing `base:ubuntu-22.04` tag

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-dev-containers#1417]
While the [documentation](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/ubuntu#summary) mentions that it should be there.

The only tag available is the `dev-ubuntu-22.04` from what it seems.

**Comment by joshspicer** [comment]
Yep, we are in the process of testing/validating the new tags (with those `dev-*` you discovered).  Keep an eye on https://github.com/microsoft/vscode-dev-containers/releases to indicate when they the new tags are fully released.

**Comment by felipecrs** [comment]
Got it. Thank you!
