### ISSUE TITLE
http://174.250.176.75/

### ISSUE THREAD

**Issue by Brad1980ford** [microsoft/vscode-dev-containers#1419]
https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md

**Comment by bamurtaugh** [comment]
Please let us know if you have a specific bug or feature request. Thank you!

**Comment by Brad1980ford** [comment]
[Utility to build.docx](https://github.com/microsoft/vscode-dev-containers/files/8578018/Utility.to.build.docx)

**Comment by Brad1980ford** [comment]
[1486627.positions.xlsx](https://github.com/microsoft/vscode-dev-containers/files/8578023/1486627.positions.xlsx)

**Comment by Brad1980ford** [comment]
[code_to_translate.zip](https://github.com/microsoft/vscode-dev-containers/files/8578025/code_to_translate.zip)

**Comment by bamurtaugh** [comment]
If you have a specific issue, please write it out, rather than pasting new links. Thank you!
