### ISSUE TITLE
Desktop-lite under ubuntu (22.04) needs tigervnc-tools installed

### ISSUE THREAD

**Issue by apederse** [microsoft/vscode-dev-containers#1428]
During devcontainer build of the cpp devcontainer with desktop-lite feature enabled and using ubuntu 22.04, the desktop-lite-debian.sh script halts because vncpasswd is not found. It appears that the tigervnc-tools package is needed to get the vncpasswd tool installed under ubuntu (not sure if it is a 22.04 issue or a general ubuntu issue). Confirmed working when adding tigervnc-tools to package_list.

**Comment by bamurtaugh** [comment]
Thanks for filing @apederse. As it sounds like you found a fix, would you be able to open a PR with the change?

**Comment by apederse** [comment]
Hi @bamurtaugh 

My quick fix was just to add tigervnc-tools to the package_list. 
package_list="
    tigervnc-standalone-server \
    tigervnc-common \
    tigervnc-tools \
    fluxbox \

However this fix do is not compatible backwards with earlier ubuntu versions. A backwards compatible quick fix is to apt install tigervnc* however that will install other unnecessary packages. The best solution is perhaps to conditionally append tigervnc-common to the list of packages if ubuntu version is >22.04 or higher but in that case the script need to be aware of the version either by passing it as an argument or perhaps probing it via  /etc/os-release. I guess some more consideration is needed before opening a PR?

**Comment by joshspicer** [comment]
Thanks for doing the heavily lifting @apederse.  I'm going to do what you suggested above into https://github.com/microsoft/vscode-dev-containers/pull/1464
