### ISSUE TITLE
Pin feature/script-library version

### ISSUE THREAD

**Issue by tczhao** [microsoft/vscode-dev-containers#1442]
Can we have the capability to pin the feature/[script-library](https://github.com/microsoft/vscode-dev-containers/tree/main/script-library) version instead of pulling from main?

e.g.
```
"features": {
    "version": "v0.234.0",
    "python": "latest"
}
```

Happy to hear more thoughts and contribute

Relates to: dev-container

**Comment by joshspicer** [comment]
That is currently supported (although not well-documented yet).

You can do the following:
```
"features": {
    "microsoft/vscode-dev-containers/python@v0.234.0": "latest"
}
```

This will not pull from our local cache of the `latest` feature, and instead pull from [**this** repo's release at the specified tag](https://github.com/microsoft/vscode-dev-containers/releases/tag/v0.234.0).

**Comment by tczhao** [comment]
Thank you @joshspicer 
I also realized that its documented here https://code.visualstudio.com/docs/remote/containers#_dev-container-features-preview
