### ISSUE TITLE
Git LFS feature fails to build on Linux/ARM64 for version 3.2+

### ISSUE THREAD

**Issue by JamesHutchisonCarta** [microsoft/vscode-dev-containers#1473]
Steps to Reproduce:

1. Add `"git-lfs": "latest"` to the `features` definition
2. Build for `linux/arm64` using the `devcontainer` cli

Error message:
```
[19231 ms] ------
 > [stage-0 3/3] RUN cd /tmp/build-features/local-cache && chmod +x ./install.sh && ./install.sh:
...
#13 13.36 git-lfs-linux-arm64-v3.2.0.tar.gz: OK
#13 13.72 ./git-lfs-debian.sh: line 163: ./install.sh: No such file or directory
```

The underlying cause is that the tarball structure changed, everything is now in a subdirectory with a name that I _think_ changes based on the version (haven't checked).

If anyone comes across this and needs to work around it, use version 3.1.4:
`"features": { "git-lfs": "3.1.4" }`

**Comment by JamesHutchisonCarta** [comment]
This sounds like the issue, as mentioned in the linked issue for git-lfs:

> we now ship our tarballs such that all files are in a top-level directory, since the old way of doing things is called a tarbomb and is generally undesirable.

**Comment by JamesHutchisonCarta** [comment]
The workaround is to use the version prior

`"features": { "git-lfs": "3.1.4" }`

**Comment by jkeech** [comment]
@joshspicer, @samruddhikhandale

**Comment by joshspicer** [comment]
Thanks for the report!  What base docker image are you using (is it based on ubuntu 22.04 jammy)?

**Comment by joshspicer** [comment]
Reproduces with jammy (eg repo: https://github.com/codspace/git-lfs-jammy/tree/main)

**Comment by joshspicer** [comment]
Hey! This should be all fixed in the PR above - thanks for the report.  Note that it'll take a few days for the cached copies of this feature to land in CLI/Codespaces/Remote-Containers.

If you'd like to use this feature in the interim, you could try out our preview syntax to remotely reference the feature:

```json
"features": {
   "microsoft/vscode-dev-containers/git-lfs@v0.238.1": "latest"
}
```
