### ISSUE TITLE
Architecture aarch64 unsupported using homebrew feature for Node.js dev container 

### ISSUE THREAD

**Issue by souhailmerroun** [microsoft/vscode-dev-containers#1479]
- VSCode Version: Version: 1.67.2 (Universal)
- Local OS Version: macOS Monterrey 12.4
- Local chip architecture: Apple Silicon
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: Node.js

Steps to Reproduce:

1. Create a fresh container with Node.js
2. Add homebrew feature
```
"features": {
    "homebrew": "latest"
}
```

```
 > [3/3] RUN cd /tmp/build-features/local-cache && chmod +x ./install.sh && ./install.sh:
#5 0.682 (*) Script: homebrew-debian.sh automatic true false
#5 0.693 (!) Architecture aarch64 unsupported
```

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/8895242/170837872-e59c41b7-673c-47cf-b0f9-477d3b22f7a6.png">

**Comment by bamurtaugh** [comment]
cc @andreiborisov

**Comment by bamurtaugh** [comment]
Thanks @andreiborisov!

@souhailmerroun As this sounds like a Homebrew issues rather than dev container feature issue, I'm going to close this, but please let me know if there's something else to consider or discuss here. Thanks!

**Comment by souhailmerroun** [comment]
oh alright, thank you guys, amazing work btw i'm the biggest fan ❤️
