### ISSUE TITLE
Upgrade to Nodejs version 16

### ISSUE THREAD

**Issue by p4nu** [microsoft/vscode-dev-containers#1482]
https://github.com/microsoft/vscode-dev-containers/blob/30f4812b6552fbc1ca79ebd0a85ac6bd5ed2f80e/repository-containers/images/github.com/microsoft/vscode/.devcontainer/base.Dockerfile#L3

Yarn wants us to update to version 16 of node.js. Before that developing VS Code through at least Codespaces is blocked.

```bash
@p4nu ➜ /workspaces/vscode $ yarn
yarn install v1.22.19
$ node build/npm/preinstall.js
*** Please use node.js versions >=16.14.x and <17.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
@p4nu ➜ /workspaces/vscode $ node -v
v14.19.3
```

- VSCode Version: 1.67.2
- Local OS Version: Windows_NT x64 10.0.22000

- Local chip architecture: x86
- Reproduces in: Codespaces, possibly both
- Name of Dev Container Definition with Issue:

Steps to Reproduce:

1. Start a new Codespace for vscode repo
2. Run `yarn`

**Comment by Chuxel** [comment]
@joshspicer - @sbatten confirmed that it should be updated to 16, yes.
