### ISSUE TITLE
Update default Go Container to 1.18.3

### ISSUE THREAD

**Issue by treeder** [microsoft/vscode-dev-containers#1495]
Brand new build is still on Go 1.18 when using the `1-bullseye` VARIANT.

**Comment by joshspicer** [comment]
What environment are you using? Is this happening Codespaces/Remote-Containers?

Also, are you talking about the go definition, the codespace image, or something else we publish that includes go?

**Comment by treeder** [comment]
Codespaces in the browser, if I setup new devcontainer files via the built in commands (ctrl-shift-p), choose Go as the language (no other options chosen), it will build with 1.18.

**Comment by joshspicer** [comment]
Apologies for not following up - this should be all updated now 🚀.  

Note that in Codespaces we cache certain images (like this one).  It sometimes takes a couple days for us to rebuild that cache, so if you get a codespace with an older version, open the command palette in vscode and `> Codespaces: Rebuild Container` to get the latest image pulled.  Thanks!

<img width="845" alt="image" src="https://user-images.githubusercontent.com/23246594/176048852-f365cfb6-9f4d-4d45-9ccb-d00767091cb7.png">

**Comment by treeder** [comment]
Thanks!  And yes, I do rebuild often to get updates, but this one was stuck at 1.18. Is there a better process to get version updates or should I create an issue like this to get an update pushed out?

**Comment by joshspicer** [comment]
Generally we should be quicker to jump on breakfix updates like this, so I appreciate the issue - feel free to create an issue if we lag behind again :)

We provide all the source code for our images (go is here - https://github.com/microsoft/vscode-dev-containers/blob/main/containers/go/.devcontainer/base.Dockerfile), so if you found yourself immediately always needing the cutting edge, you could use our Dockerfile directly (but hopefully we're quick enough in the future that isn't necessary)

**Comment by treeder** [comment]
So just FYI, I rebuilt a project that uses the default Go configuration files and it is now 1.18.3. 👍  But the default Codespaces container (the kitchen sink one) is still 1.18 after a rebuild.

**Comment by joshspicer** [comment]
Good to know, I'll double check that.  They use the same script to install, so I would have expected them to both be updated

**Comment by treeder** [comment]
Not to be annoying, but could this get bumped to 1.18.4 now? It was released on July 12th.

**Comment by joshspicer** [comment]
Will do, thanks for the ping!

**Comment by joshspicer** [comment]
published! @treeder (Again, the codespaces cache will take a few days to update, but a rebuild will always pull the latest!)
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/23246594/181582772-cdbee069-0405-41ed-a134-595ff3a72458.png">
