### ISSUE TITLE
Docker won't start on node image with docker-in-docker

### ISSUE THREAD

**Issue by harrywithers** [microsoft/vscode-dev-containers#1517]
- VSCode Version: 1.68.1
- Local OS Version: macOS Monterey 12.3.1
- Local chip architecture: Intel Core i7
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: docker-in-docker

Steps to Reproduce:

1. Create a devcontainer file and docker file with the following configuration
```json
{
    "name": "name",
    "build": {
        "dockerfile": "./Dockerfile"
    },
    "remoteUser": "node",
    "features": {
        "docker-in-docker": "latest",
    }
}
```
```Dockerfile
FROM node:16.14.0

```
2. Reopen in dev container
3. Run `docker ps` in the dev container

Result:
```txt
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

But expected docker to be up and running in the container.

Docker container log:
```txt
Container started
/usr/local/share/docker-init.sh: 65: /usr/local/share/docker-init.sh: sudo: not found
```

Docker version output in dev container:
```txt
Client:
 Version:           20.10.17+azure-1
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c70180fde3601def79a59cc3e996aa553c9b9
 Built:             Mon Jun  6 21:36:39 UTC 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Docker version output locally
```txt
Client:
 Cloud integration: v1.0.25
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:20:34 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.9.1 (81317)
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:42 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Example repository:
https://github.com/harrywithers/broken-dind

Seemed to be working fine a week or so ago, I've got a few projects using this setup and all of them now fail to start docker.

Anyone know how to fix this? Thanks in advance!

**Comment by joshspicer** [comment]
The base image that you are using in your example doesn't have the `sudo` program installed, and the chosen remoteUser is not root.  The docker-in-docker script either needs an image with sudo installed, or to be run as root.

Some options (untested, in my order of preference 😄)

1. Are you able to use our published node image (`mcr.microsoft.com/vscode/devcontainers/typescript-node:16`) instead of the dockerhub `node` image?  That will work out of the box. 🚀

2. Selecting a base image with `sudo` installed (or install sudo in your Dockerfile)

3. Removing `remoteUser` from your devcontainer, which will run the container as root.

**Comment by Chuxel** [comment]
@joshspicer To clarify, only the default user in the Dockerfile would need to be root to get things to work without sudo. You can also force it to be root using `"containerUser": "root"`.

What likely is going on is the Dockerfile includes `USER <blah>`.

**Comment by Chuxel** [comment]
Yeah there is some sort of new bug here.  Commenting out `remoteUser` causes it to work, which indicates the entrypoint is incorrectly being executed as the `remoteUser`.

@joshspicer @edgonmsft @jkeech @chrmarti - This is a breaking bug which repo should we move this to to fix at this point?  Is this devcontainers/cli potentially?

**Comment by edgonmsft** [comment]
Not sure which one, maybe both for now?

**Comment by Chuxel** [comment]
Opened https://github.com/devcontainers/cli/issues/70. Closing this in favor of that issue.
