### ISSUE TITLE
Windows Dev Container Definitions

### ISSUE THREAD

**Issue by nashley** [microsoft/vscode-dev-containers#1531]
Surprisingly, there doesn't seem to be a dev container definition based on Windows. I'm particularly interested in one for Rust, since I'd like to be able to test changes to crates that depend on [`windows-rs`](https://github.com/microsoft/windows-rs) without having to install Windows.

I can `cargo build --target x86_64-pc-windows-gnu` easily, but I can't run tests.

Relates to: Both?

**Comment by eitsupi** [comment]
I don't think the VSCode Remote-Containers extension supports Windows containers in the first place.
See microsoft/vscode-remote-release#445

> Containers:
>
>    x86_64 / ARMv7l (AArch32) / ARMv8l (AArch64) Debian 9+, Ubuntu 16.04+, CentOS / RHEL 7+
>    x86_64 Alpine Linux 3.9+

https://code.visualstudio.com/docs/remote/containers

**Comment by nashley** [comment]
Thanks for the info!
I guess I'll look into setting up a development environment with [WINE](https://www.winehq.org/about) or [ReactOS](https://reactos.org/) or something.

**Comment by bamurtaugh** [comment]
Thanks for opening @nashley, and @eitsupi is correct!
