### ISSUE TITLE
SSH connection to github fails in devcontainer

### ISSUE THREAD

**Issue by hinamimi** [microsoft/vscode-dev-containers#1547]
I have done "Sharing Git credentials" based on the following site, but ssh fails in the devcontainer. 
https://code.visualstudio.com/docs/remote/containers#_sharing-git-credentials-with-your-container

However, the copy of gitconfig and ssh-agent seem to work fine. What are the likely causes?

```
# In devcontainer
$ cat ~/.gitconfig | head -n 3
[user]
        name = hinamimi
        email = hinamimi09@gmail.com
$ ssh-add -l
# ~~ My key data ~~
$ ssh -A -T git@github.com
ssh: Could not resolve hostname github.com: No address associated with hostname
```

```
# In wsl environment
$ ssh-add -l
# ~~ My key data ~~
$ ssh -A -T git@github.com
Hi hinamimi! You've successfully authenticated, but GitHub does not provide shell access.
```

Dockerfile
```
FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y \
    git \
    curl \
    wget

WORKDIR /workspace
```

The specific file structure can be found in the following repositories.
https://github.com/hinamimi/devcontainer-git-test

Environment
- Windows11
  - vscode: 1.69.2, 3b889b090b5ad5793f524b5d1d39fda662b96a2a, x64
  - Remote - Containers: v0.241.3
  - WSL: Ubuntu 20.04 on Windows
- WSL
  -  docker: Docker version 20.10.17, build 100c701

**Comment by joshspicer** [comment]
I suspect this has something to do with the bind-mount overriding the bashrc that the base image provides.  Could you try removing that bind mount and seeing if it helps?

**Comment by hinamimi** [comment]
I removed the bashrc mount and now ssh to github works! Thanks for your advice, I appreciate it.

The root cause was that I neglected the following setup options and tried to manage them in my own way.
https://code.visualstudio.com/docs/remote/containers#_personalizing-with-dotfile-repositories

Thank you for maintaining devcontainer. You have helped me a lot.
