### ISSUE TITLE
install_via_pip fails when used as fallback for install_via_apt when version is latest

### ISSUE THREAD

**Issue by ryan-smylski** [microsoft/vscode-dev-containers#1555]
- VSCode Version: 1.69.2
- Local OS Version: Windows_NTx64 10.0.19043
- Local chip architecture: x86
- Reproduces in: Both
- Name of Dev Container Definition with Issue: azcli-debian.sh

Steps to Reproduce:

1. While the azcli-debian.sh script is running with AZ_VERSION=latest, kill your network connection to have `install_using_apt` fail.
2. When it defaults to `install_using_pip` AZ_VERSION will have been set to `""` in `install_using_apt`, so when it does a version check, it will set `ver` to `==` resulting in `installing azure-cli from spec 'azure-cli=='

`install_using_apt` should use a new variable for its version instead or re-using AZ_VERSION to avoid a needing to add a new if condition for `["${AZ_VERSION}" = "" ]` in `install_using_pip` when its called as a fallback.

**Comment by joshspicer** [comment]
Hi @ryan-smylski , thanks for taking the time to create the issue.  I'll add in a quick fix to cache the version and restore it if we end up going down the pip path.
