### ISSUE TITLE
Node + MongoDB: missing $MDB_CONNECTION_STRING environment variable

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-dev-containers#1556]
- VSCode Version: 1.69.2 (user setup)
- Local OS Version: Win 11
- Local chip architecture: x86
- Reproduces in: Remote - containers
- Name of Dev Container Definition with Issue: Node + Mongo

![image](https://user-images.githubusercontent.com/41597107/181590735-f50eea04-b1d6-4229-a87e-0fd8fba5776f.png)

Steps to Reproduce:

1. Open Container (containers really)
2. Connect to Azure Cosmos DB with Mongo API
3. Use Mongo extension command palette to connect to Mongo Shell: "MongoDB: Launch MongoDB Shell"
4. Terminal opens with error
    ![image](https://user-images.githubusercontent.com/41597107/181591761-0e0b38e9-457d-46e2-a163-b9bb018da7bf.png)

Before you say this is a Mongo extension issue - where is the environment var coming from and which extension is responsible for it? 

Some times the shell opens successfully and sometimes it doesn't - how can I refresh the environment so the var is found?

**Comment by Chuxel** [comment]
That connection string would be set in the container, but what made you expect it would be there?

**Comment by diberry** [comment]
Thanks for your help earlier today on this in email - I wasn't sure who to contact when I logged this issue. Your change to the docker file fixed the issue. Can you post a link to your PR whenever that gets created?

**Comment by Chuxel** [comment]
Got it - in and merged https://github.com/microsoft/vscode-dev-containers/pull/1557

Will go with the next release!

**Comment by diberry** [comment]
Thank you.

**Comment by Iwett23** [comment]
> Děkuji.
