### ISSUE TITLE
Docker in Docker feature only accessible by single devcontainer at a time

### ISSUE THREAD

**Issue by templela** [microsoft/vscode-dev-containers#1596]
- VSCode Version: 1.70.2 (Universal)
- Local OS Version: Ubuntu 20.04.4
- Local chip architecture: amd64
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue:

Steps to Reproduce:

1. Have 2+ devcontainers open with `features`: `"docker-in-docker": "20.10"` 
2. The first opened container will have access to docker, other instances will give you the standard ```Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?``` error.

**Comment by alecdwm** [comment]
Related to https://github.com/microsoft/vscode-remote-release/issues/5679

**Comment by Chuxel** [comment]
https://github.com/devcontainers/spec/issues/62 is the proposed fix for this. Closing as a dupe of that and https://github.com/microsoft/vscode-remote-release/issues/5679 just to consolidate conversation. (Since agreed it is it is important.)
