### ISSUE TITLE
BUG - Docker Compose required

### ISSUE THREAD

**Issue by edwinhuish** [microsoft/vscode-dev-containers#1600]
- VSCode Version: 1.70.2
- Local OS Version: WIN11 (Window_NT x64 10.0.22000)
- Local chip architecture: x86
- Reproduces in: <Codespaces | Remote - Containers | Both>
- Name of Dev Container Definition with Issue: any

Steps to Reproduce:

1. project root with any .env file in INI format (with section name)
2. config dev container as docker-compose mode, build or rebuild the container.

### Why it happen:
**vscode run docker-compose version in the project root, but docker-compose read .env as default, and the project root .env not a valid docker-compose env file.**

**Comment by bamurtaugh** [comment]
Thanks for opening @edwinhuish. Does this issue pertain to a specific dev container definition? This repo is for discussing specific definitions and Features (although our team has been actively working on an updated plan for community contributions and this repo moving forward, which we've now outlined in this issue: https://github.com/microsoft/vscode-dev-containers/issues/1589).
