### ISSUE TITLE
Debian / Ubuntu base conda-notice.txt error

### ISSUE THREAD

**Issue by dmaasland** [microsoft/vscode-dev-containers#1617]
## Issue
Hello,

It seems that the base Debian / Ubuntu images add the following code to **`/etc/bash.bashrc`** and **`/etc/zsh/zshrc`**:
```bash
if [ -t 1 ] && [ "${IGNORE_NOTICE}" != "true" ] && [ "${TERM_PROGRAM}" = "vscode" ] && [ "${CODESPACES}" != "true" ] && [ ! -f "$HOME/.config/vscode-dev-containers/conda-notice-already-displayed" ]; then
    cat "${DEV_CONTAINERS_DIR}/conda-notice.txt"
    mkdir -p "$HOME/.config/vscode-dev-containers"
    ((sleep 10s; touch "$HOME/.config/vscode-dev-containers/conda-notice-already-displayed") &)
fi
```

However, the file **`${DEV_CONTAINERS_DIR}/conda-notice.txt`** isn't present by default and triggers an error when opening a terminal for the fist time:

```bash
cat: /conda-notice.txt: No such file or directory
vscode ➜ /workspaces/condabug $
```

## Additional information
- VSCode Version: 1.71.0
- Local OS Version: macOS Monterey 12.5.1
- Local chip architecture: x86
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue:  at least **`base:bullseye`** and **`base:focal`**

## Steps to Reproduce:

1. Create a devcontainer using the following config files below
2. Open up a new bash terminal window
3. Observe the warning ```cat: /conda-notice.txt: No such file or directory```

**`Dockerfile`**
```docker
ARG VARIANT=bullseye
FROM mcr.microsoft.com/vscode/devcontainers/base:${VARIANT}
```

**`devcontainer.json`**
```json
{
  "name": "Conda warning test",
  "build": {
    "dockerfile": "Dockerfile"
  },
  "remoteUser": "vscode"
}
```

## Workaround
Add 
```docker
ENV IGNORE_NOTICE=true
```
to your Dockerfile

## Impact
Very low, it only manifests on first startup of the terminal.

**Comment by Chuxel** [comment]
@samruddhikhandale @joshspicer Is this a regression for https://github.com/devcontainers/images/tree/main/src/anaconda ?

**Comment by samruddhikhandale** [comment]
Fix - https://github.com/devcontainers/features/pull/135
