### ISSUE TITLE
Github CLI Feature fails with GPG key error

### ISSUE THREAD

**Issue by JamesHutchisonCarta** [microsoft/vscode-dev-containers#1621]
See https://github.com/microsoft/vscode-dev-containers/issues/1615

Only making this ticket because that one was closed.

I've tried doing a clean rebuild and still see the issue.

**Comment by JamesHutchisonCarta** [comment]
Ok: the issue was I was testing locally and I had a cached version of the dev container base image that was missing the key. Doing `docker pull mcr.microsoft.com/vscode/devcontainers/<dev container name and tag>` prior to building resolved the issue.

**Comment by exilvm** [comment]
`github-cli` feature is currently maintained at: https://github.com/devcontainers/features. and the GDP key issue is already fixed.

**Comment by Chuxel** [comment]
Yeah GitHub's GPG expired unexpectedly, so it broke lots of people. They've since supposedly resolved it. 

The upstream issue is https://github.com/cli/cli/issues/6175 if you are still running into trouble.

**Comment by Chuxel** [comment]
Also - for reference, this was the update we did before the GPG key was fixed.

> 👋 For anyone using Codespaces, Remote-Containers, or the [dev container CLI](https://github.com/devcontainers/cli), we have updated the dev container feature to prefer pulling from the latest GitHub Release instead of adding the apt repo. (see: [devcontainers/features#133](https://github.com/devcontainers/features/pull/133))
> 
> #### Example `devcontainer.json`
> ```js
> {
>    "image": "mcr.microsoft.com/devcontainers/base:ubuntu", // Any debian-based image
>    "features": {
>       "ghcr.io/devcontainers/features/github-cli:1": {}
>    }
> }
> ```
> 
> For future reference, supplying the option `installDirectlyFromGitHubRelease: false` will attempt the traditional approach that adds and fetches the github-cli via apt.
> 
> ```js
> {
>    "image": "mcr.microsoft.com/devcontainers/base:ubuntu", // Any debian-based image
>    "features": {
>       "ghcr.io/devcontainers/features/github-cli:1": {
>         "installDirectlyFromGitHubRelease": false
>       }
>    }
> }
> ```
