### ISSUE TITLE
Not able to use .net 6 LTS in 22.04 LTS.

### ISSUE THREAD

**Issue by anirugu** [microsoft/vscode-dev-containers#1637]
I am trying to do add container configuration and use 22.04 option. This is the config I use

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/ubuntu
{
	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile",
		// Update 'VARIANT' to pick an Ubuntu version: jammy / ubuntu-22.04, focal / ubuntu-20.04, bionic /ubuntu-18.04
		// Use ubuntu-22.04 or ubuntu-18.04 on local arm64/Apple Silicon.
		"args": { "VARIANT": "ubuntu-22.04" }
	},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "uname -a",

	// Comment out to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "vscode",
	"features": {
		"docker-in-docker": "latest",
		"docker-from-docker": "latest",
		"node": "lts",
		"dotnet": "latest"
	}
}
```
not able to usse dotnet.

![image](https://user-images.githubusercontent.com/35772421/192076499-785a10ec-775b-4037-b5e4-9db3582a9b49.png)
I search the existing issue and this one look similar https://github.com/microsoft/vscode-dev-containers/issues/1458

**Comment by Chuxel** [comment]
.NET 6 is out including the ubuntu 22.04 pre-built image.  If you are still experiencing issues, please raise an issue in the feature repository (https://github.com/devcontainers/features) or the image repository (https://github.com/devcontainers/images).  The .NET feature is not maintained in this repository anymore.
