### ISSUE TITLE
Error with cat conda-notice.txt first time a cpp container is opened

### ISSUE THREAD

**Issue by aplatanado** [microsoft/vscode-dev-containers#1640]
- VSCode Version: 1.71.2
- Local OS Version: Windows 11
- Local chip architecture: x86
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: cpp

Steps to Reproduce:

1. Start a Dev Container mcr.microsoft.com/vscode/devcontainers/cpp
2. First time the terminal shows this error: `cat: /conda-notice.txt: No such file or directory`

This causes because /etc/bash.bashrc contains the next lines:

~~~
if [ -t 1 ] && [ "${IGNORE_NOTICE}" != "true" ] && [ "${TERM_PROGRAM}" = "vscode" ] && [ "${CODESPACES}" != "true" ] && [ ! -f "$HOME/.config/vscode-dev-containers/conda-notice-already-displayed" ]; then
    cat "${DEV_CONTAINERS_DIR}/conda-notice.txt"
    mkdir -p "$HOME/.config/vscode-dev-containers"
    ((sleep 10s; touch "$HOME/.config/vscode-dev-containers/conda-notice-already-displayed") &)
fi
~~~

These lines don't exist in container builds from base Dev Container Definition, so I guess are added during cpp imagen build. But I haven't found where.

**Comment by aplatanado** [comment]
You are right. It is.

**Comment by samruddhikhandale** [comment]
We missed releasing a new `cpp` image with the bug fix.

I'll post an update on this thread when its fixed.

**Comment by samruddhikhandale** [comment]
Fixed with the `cpp` image release.

![image](https://user-images.githubusercontent.com/24955913/192832225-abcc6844-2eb3-430b-968f-d698bdc6c415.png)
