### ISSUE TITLE
nerdctl support

### ISSUE THREAD

**Issue by markusgod** [microsoft/vscode-dev-containers#1651]
To complete docker-compatable CLIes line, please add support for containerd's nerdctl https://github.com/containerd/nerdctl

It looks like, there is only one incompatibility:
https://github.com/containerd/nerdctl/issues/1027

Relates to: Remote - Containers

**Comment by Chuxel** [comment]
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6075

The dev container CLI is also open source if you are interested in contributing support since this is what the extension uses under the hood. https://github.com/devcontainers/cli
