### ISSUE TITLE
Remove migrated R template

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode-dev-containers#1669]
Per https://github.com/microsoft/vscode-dev-containers/issues/1589

@eitsupi has migrated their Template over to a self-hosted repo (https://github.com/devcontainers/devcontainers.github.io/pull/49), so we can clean up the deprecated community template hosted in this repo!

**Comment by samruddhikhandale** [comment]
PR 

- https://github.com/microsoft/vscode-dev-containers/pull/1673

**Comment by samruddhikhandale** [comment]
Removed. `R` no longer exists in https://containers.dev/templates
