### ISSUE TITLE
azure-functions-python-3 container fails

### ISSUE THREAD

**Issue by marcusturewicz** [microsoft/vscode-dev-containers#168]
When installing the devcontainer, I get the following error:
```
 W: Conflicting distribution: https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease (expected stretch but got stable)
E: Failed to fetch https://packages.microsoft.com/repos/microsoft-debian-stretch-prod/dists/stretch/main/binary-amd64/Packages.bz2  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:156065 [weak]
    - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
    - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
    - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
    - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
   Hashes of received file:
    - SHA512:a18b4df496d00477e52cf62e01c9f6c9534926ad0e3bf17f94fc28fc9bd91d5ee5e906b460477e2c1b280a5757a067937c9b2724bd6c72066e982a19306f28b8
    - SHA256:94e637dd6df186bbed5a19f2e7bdc2dcc8f7bb0feb2f1eaf93f05b45dd322cc4
    - SHA1:fb9e80e17952a577030e9266737b23269c8d878b [weak]
    - MD5Sum:
[190154 ms] 4360374f4ec05159ef14908c0dbf4116 [weak]
    - Filesize:68668 [weak]
   Last modification reported: Fri, 13 Dec 2019 01:35:23 +0000
   Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

- VSCode Version: 1.41.0
- Local OS Version: macOS Mojave 10.14.6 
- Name of Dev Container Definition with Issue: azure-functions-python-3

Steps to Reproduce:

1. Include files in .devcontainer locally in your project
2. Reopen in Container
3. Wait for it to build and fail

**Comment by Chuxel** [comment]
@marcusturewicz Thanks for reporting this.  There appears to be something going on with the functions repo.  There are similar reports for GitHub actions: https://github.community/t5/GitHub-Actions/ubuntu-latest-Apt-repository-list-issues/td-p/41122

We'll keep an eye on it - leaving open for anyone else that may be encountering this.

**Comment by Chuxel** [comment]
The upstream issue appears to have been resolved!

More info: https://github.com/dotnet/core/issues/3995

Let us know if you're still hitting it!
