### ISSUE TITLE
Base image for Ubuntu Focal not available for arm64 architecture

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-dev-containers#1683]
I was checking the platform support for some devcontainer images on arm64 and just noticed that various ubuntu images support arm64 but the focal images do not.

Can we get that architecture `arm64` published for Ubuntu Focal too? or this is not available because of some particular issue? (if so maybe we should document it somewhere that it is not available, we struggled with a related issue while trying to use the derived dotnet:focal image on an arm64 system).

- VSCode Version:
- Local OS Version: Ubuntu Focal
- Local chip architecture: arm64
- Reproduces in: Both
- Name of Dev Container Definition with Issue: mcr.microsoft.com/vscode/devcontainers/base:focal

Steps to Reproduce:

```bash
$ docker run --rm mplatform/mquery mcr.microsoft.com/vscode/devcontainers/base:focal

Image: mcr.microsoft.com/vscode/devcontainers/base:focal (digest: sha256:ce4ae5134a435185a8a2052eab6d0ee2ad04f5f062a78377cc348ad9d8eab6f2)
 * Manifest List: No (Image type: application/vnd.docker.distribution.manifest.v2+json)
 * Supports: linux/amd64

$ docker run --rm mplatform/mquery mcr.microsoft.com/vscode/devcontainers/base:jammy

Image: mcr.microsoft.com/vscode/devcontainers/base:jammy (digest: sha256:1056dcb30c2510505fb344195f138c3a59d9323b09411045953490cc9afdd388)
 * Manifest List: Yes (Image type: application/vnd.docker.distribution.manifest.list.v2+json)
 * Supported platforms:
   - linux/amd64
   - linux/arm64

$ docker run --rm mplatform/mquery mcr.microsoft.com/vscode/devcontainers/base:bionic

Image: mcr.microsoft.com/vscode/devcontainers/base:bionic (digest: sha256:65563e258b3d994cfd015ee853cbcb75c5313837537bd7709e23c6c328fc98ca)
 * Manifest List: Yes (Image type: application/vnd.docker.distribution.manifest.list.v2+json)
 * Supported platforms:
   - linux/amd64
   - linux/arm64
```

**Comment by Chuxel** [comment]
This is expected.  See https://github.com/microsoft/vscode-dev-containers/issues/558

Docker Desktop bombs randomly with arm64 focal and debian buster. The same goes for buildx which prevents us from being able to cross compile.
