### ISSUE TITLE
New Ubuntu dev container with az cli feature won't run az cli with a runpy error

### ISSUE THREAD

**Issue by Codebytes** [microsoft/vscode-dev-containers#1685]
- VSCode Version: 1.73.1
- Local OS Version:
- Local chip architecture: x64
- Reproduces in: <Codespaces | Remote - Containers | Both>
- Name of Dev Container Definition with Issue: Ubuntu

Steps to Reproduce:

1. From command pallette: add dev container configuration files
2. Select Ubuntu
3. Select Jammy (default)
4. Add Azure CLI Feature
5. Add Terraform 
6. Add Python
7. Ok
8. Reopen and Rebuild without Cache
9. on prompt, type az version
10. Could not import runpy module
ModuleNotFoundError: No module named 'runpy'

**Comment by Chuxel** [comment]
This is https://github.com/devcontainers/features/issues/270. Please raise issues related to Features in this new repository as explained in the issue template.
