### ISSUE TITLE
Error loading webview: Error: Could not register service workers: NotSupportedError: Failed to register a ServiceWorker for scope

### ISSUE THREAD

**Issue by vivekpal1** [microsoft/vscode-dev-containers#1697]
## While Using Preview option for markdown files in GitHub Codespaces
I found this error -
Error loading webview: Error: Could not register service workers: NotSupportedError: Failed to register a ServiceWorker for scope....

![Screenshot from 2022-11-27 21-45-34](https://user-images.githubusercontent.com/88021457/204145573-24f56962-a041-4d88-b9c7-854124188cf8.png)

**Comment by brccabral** [comment]
This helped me https://github.com/orgs/community/discussions/26316

**Comment by Chuxel** [comment]
Yes, please raise issues related to Codespaces here: https://github.com/orgs/community/discussions/categories/codespaces

https://github.com/orgs/community/discussions/26316 looks relevant, so closing as a duplicate.
