### ISSUE TITLE
JSON configuration for mounts doesn't work in codespaces

### ISSUE THREAD

**Issue by dsyer** [microsoft/vscode-dev-containers#1699]
This works locally (and is the syntax recommended in the devcontainers reference docs):

```
"mounts": [{ "source": "test", "target": "/test", "type": "volume" }],
```

but causes the container creation to fail with no useful error message in codespaces. In codespaces you need:

```
"mounts": ["source=test,target=/test,type=volume"],
```

**Comment by Chuxel** [comment]
This sounds like a Codespaces bug rather than an image or dev container spec issue.  

@joshspicer @samruddhikhandale @jkeech @edgonmsft ?

**Comment by edgonmsft** [comment]
Yep it does sound like a Codespaces issue.
