### ISSUE TITLE
Java 8 & Tomcat 8.5 Build - The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by MarcJefferson5** [microsoft/vscode-dev-containers#170]
- VSCode Version: 1.41
- Local OS Version: Windows 10, 1803
- Name of Dev Container Definition with Issue: Java 8 & Tomcat 8.5

Steps to Reproduce:

1. Open Folder 
2. Add Development Container Configuration
3. Select Java 8 & Tomcat 8.5
4. Reopen Folder in Container

The build will fail with the error message: "The requested URL returned error: 404 Not Found"

**Comment by Chuxel** [comment]
@MarcJefferson5 Thanks for reporting this.  It looks like Apache removed Maven 3.6.1 for some reason.  

The simple fix is to change:

```
ARG MAVEN_VERSION=3.6.1
ARG MAVEN_SHA=b4880fb7a3d81edd190a029440cdf17f308621af68475a4fe976296e71ff4a4b546dd6d8a58aaafba334d309cc11e638c52808a4b0e818fc0fd544226d952544
```

to

``` 
ARG MAVEN_VERSION=3.6.3
ARG MAVEN_SHA=c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
```

I'll update the definitions as well.

/cc: @testforstephen @chrmarti

**Comment by Chuxel** [comment]
Ok, it looks like the non-archive URL is being used.  I also updated that so this doesn't happen again.

```
  && curl -fsSL -o /tmp/apache-maven.tar.gz https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
```
