### ISSUE TITLE
dotnetcore-3.1

### ISSUE THREAD

**Issue by ignatandrei** [microsoft/vscode-dev-containers#172]
Please add dotnetcore 3.1 container for https://github.com/microsoft/vscode-dev-containers/tree/master/containers

**Comment by Chuxel** [comment]
Thanks for the feature request!  Happy to take a look at a PR if you are interested in creating one.

**Comment by ignatandrei** [comment]
I am not sure that I understand the 
https://github.com/microsoft/vscode-dev-containers/blob/master/containers/dotnetcore-3.0/.devcontainer/Dockerfile
in order to do the same for .NET Core 3.1

**Comment by Chuxel** [comment]
They're in the repo now and you should see them in the next release in VS Code!

**Comment by ignatandrei** [comment]
Thank you!
