### ISSUE TITLE
command 'remote-containers.createDevContainer' not found

### ISSUE THREAD

**Issue by helbing** [microsoft/vscode-dev-containers#1721]
- VSCode Version: 1.75.1
- Local OS Version: macOS 13.2.1 (22D68)
- Local chip architecture: x86
- Reproduces in: Remote - Containers, and I can open the project in Codespaces
- Name of Dev Container Definition with Issue: none

Steps to Reproduce:

1. F1 ->  Create Dev Container, it will popup an error, Command 'Dev Containers: Create Dev Container...' resulted in an error (command 'remote-containers.createDevContainer' not found)
2. I reinstall the dev container plugin, but it also doesn't work

**Comment by david-engelmann** [comment]
Is this the current place to add issues? I'm getting no responses on my issue

**Comment by david-engelmann** [comment]
[I moved my issue card here](https://github.com/microsoft/vscode-remote-release/issues)

**Comment by helbing** [comment]
> [I moved my issue card here](https://github.com/microsoft/vscode-remote-release/issues)

thx guy, my issue is fixed suddenly, and I have no idea why.
