### ISSUE TITLE
Go container fails

### ISSUE THREAD

**Issue by eelmasllari** [microsoft/vscode-dev-containers#174]
- VSCode Version: 
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

- Local OS Version: Mojave 10.14.6

- Name of Dev Container Definition with Issue: go

Steps to Reproduce:

1. Open any folder in container, select "Go" from templates
2. Container build fails

As I can best tell, it is related to this commit in gopls, but I am not sure:
https://github.com/golang/tools/commit/8647d4c87977ec65bfce87fe963652c71cd2e0db

**Comment by Chuxel** [comment]
Thanks for reporting the issue!  It looks like the path to gopls changed upstream which broke the definition.  PR #173 was just merged with the fix.

```
golang.org/x/tools/cmd/gopls \
```
should be changed to

```
golang.org/x/tools/gopls \
```

in .devcontainer/Dockerfile
