### ISSUE TITLE
containers/go: Go tool installation will not work with Go modules

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-dev-containers#175]
The Go tools for development are installed [here](https://github.com/microsoft/vscode-dev-containers/blob/master/containers/go/.devcontainer/Dockerfile#L32) with a single command and with the `-u` flag. This will not work as expected if these tools are versioned using Go modules, and it may result in conflicting behavior if the tools share dependencies. Users may get an unexpected versions of these tools (in particular, `gopls` is versioned so `master` may be broken at the moment when the user installs it).

A better approach would be to stop using the `-u` flag, and to install tools individually in a temporary directory with a temporary `go.mod` file. As an example, VS Code Go does [this](https://github.com/microsoft/vscode-go/blob/24b493b0a4848b56cc031fafe3d6dbb715da1c8e/src/goInstallTools.ts#L137).

**Comment by Chuxel** [comment]
Apologies for the delay - our coverage was limited over holidays.

Thanks for letting us know. Happy to take a PR with your suggestion - otherwise we can try to take a look at it this iteration.

**Comment by Chuxel** [comment]
#193 is a PR to attempt to resolve this.
