### ISSUE TITLE
Document Dev Container definition release process

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-dev-containers#185]
Add documentation to describe how new Dev Container definitions (and updates to existing ones) propagate to VS Code.  (E.g. it looks like `vscode-dev-containers` releases are created periodically, which are then eventually picked up by a new release of the `remote-containers` extension. However, I don't see any notes about the general timelines involved, release schedules, etc.)

**Comment by Chuxel** [comment]
Good suggestion - we'll get that into CONTRIBUTING.md.  To answer the question:

1. The vscode-dev-containers repo does ship with the VS Code extension currently. (There is a feature request to do this out-of-band: https://github.com/microsoft/vscode-remote-release/issues/425)
2. The Remote - Containers extension ships into **Stable** on the same release cadence as VS Code itself using [four week iterations](https://github.com/microsoft/vscode/wiki/Development-Process#inside-an-iteration). Here is the [current VS Code iteration plan](https://github.com/microsoft/vscode/issues/87479) with dates, and then the additions for the [remote extensions](https://github.com/microsoft/vscode-remote-release/issues/2075).
3. The Remote - Containers extension ships into **Insiders** as new features land during the iteration. This is not currently an automated daily release like VS Code itself.
4. If there is urgency for an update to the definitions outside of this release cycle, we can do one-off updates to Insiders and Stable as the need arises - particularly for Insiders.

That help?

**Comment by Chuxel** [comment]
Updated with https://github.com/microsoft/vscode-dev-containers/commit/2bf50522aec01c80533b033f6a0275406651ad8c.  Let me know if you'd like to see anything else in the content to help clarify!

**Comment by philliphoff** [comment]
That's perfect, thanks!
