### ISSUE TITLE
Add Haskell dev-container

### ISSUE THREAD

**Issue by aszenz** [microsoft/vscode-dev-containers#202]

**Comment by Chuxel** [comment]
Thanks for the feature request!  Happy to take a look at a PR if you (or anyone reading this) is interested in contributing one.

**Comment by Krzysztof-Cieslak** [comment]
Hey @hmemcpy maybe we should move https://github.com/hmemcpy/haskell-hie-devcontainer here to make it available in out-of-the-box templates?

**Comment by hmemcpy** [comment]
It would be great! But I just literally yesterday stumbled upon it, so I'm not sure it's "up to standards". If someone could take a look, I'd be happy to make needed tweaks, if any.

Also, the image I'm using takes a while to build, so I've built it under my own docker hub account. Not sure that's a problem for "public" documentation, I'm hoping if this works to contribute it to the haskell-ide-engine repository.

**Comment by eitsupi** [comment]
I believe this issue has been resolved by #685.
