### ISSUE TITLE
Git containers should have SSH

### ISSUE THREAD

**Issue by aaronadamsTO** [microsoft/vscode-dev-containers#210]
Containers alpine-3.10-git, debian-9-git, and ubuntu-18.04-git don't currently have the `ssh` command available. This results in a very obscure error message when attempting to clone or sync via SSH:

```sh
# git clone git@github.com:microsoft/vscode-dev-containers.git
Cloning into 'vscode-dev-containers'...
fatal: unable to fork
```

@Chuxel, I didn't want to blindly fire a PR at the new image generation scripts, since it seems like you're in the middle of a refactor. For now I'll just add an SSH client to my own Dockerfile that uses these upstream images, but I think they should probably come with it. Thanks!

**Comment by Chuxel** [comment]
Thanks for pointing that out! Can add it to the common script so it gets picked up wherever an images it built.
