### ISSUE TITLE
Elm: Update to elm 0.19.1 and use the language server

### ISSUE THREAD

**Issue by andys8** [microsoft/vscode-dev-containers#222]
Hey, I like the dev-container idea for vscode.

## Issue

I saw the current elm project is using version `0.19.0` and not the latest `0.19.1`. This is actually a breaking change and around 1 year newer.

https://github.com/microsoft/vscode-dev-containers/blob/cd4e2d538d15efc1f39c160bd106d83fbe28e8e3/containers/elm/test-project/elm.json#L6

https://github.com/microsoft/vscode-dev-containers/blob/cd4e2d538d15efc1f39c160bd106d83fbe28e8e3/containers/elm/.devcontainer/Dockerfile#L12

The vscode plugin that is used was recently deprecated and replaced.
https://github.com/microsoft/vscode-dev-containers/blob/cd4e2d538d15efc1f39c160bd106d83fbe28e8e3/containers/elm/.devcontainer/devcontainer.json#L12

https://marketplace.visualstudio.com/items?itemName=sbrink.elm
![image](https://user-images.githubusercontent.com/13085980/73492750-9ec1e100-43b1-11ea-9d47-634fe1259673.png)

There is a new plugin that is using the `elm-language-server`.
https://marketplace.visualstudio.com/items?itemName=Elmtooling.elm-ls-vscode

## Solution

* Rely on the vscode plugin `Elmtooling.elm-ls-vscode`
* Provide dependencies
  * elm
  * elm-test
  * elm-format
  * git (?)

#### `devcontainer.json`

```json
{
  "name": "Elm",
  "dockerFile": "Dockerfile",
  "extensions": ["Elmtooling.elm-ls-vscode"]
}
```

#### `Dockerfile`

`Dockerfile` (based on `nix`, could also be based on `node`, `alpine` or `debian`)

```docker
FROM nixos/nix

RUN nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
RUN nix-channel --update
RUN nix-env -iA nixpkgs.elmPackages.elm nixpkgs.elmPackages.elm-test nixpkgs.elmPackages.elm-format nixpkgs.git
```

or

Since Elm and its tooling can be installed with `node`/`npm` the `Dockerfile` can be a copy of [`containers/javascript-node-12`](
https://github.com/microsoft/vscode-dev-containers/blob/master/containers/javascript-node-12/.devcontainer/Dockerfile) and install `elm` and other dependencies.

```docker
FROM node:12
...
RUN npm install --global --unsafe-perm elm elm-test elm-format
```

What do you think? @xWiiLLz @Chuxel

**Comment by Chuxel** [comment]
Sounds reasonable to me!   @xWiiLLz? 

For the image, you could actually use the new pre-built node-12 image: `mcr.microsoft.com/vscode/devcontainers/javascript-node:12`  There's also one for Debian as well, but not nix at the moment. (See [here](https://hub.docker.com/_/microsoft-vscode-devcontainers).) The has git, zsh (and oh my zsh) and typical dependencies installed along with a vscode non-root user.

 If you're interested in submitting a PR, happy to review it.

**Comment by andys8** [comment]
That's a good idea. I'll come up with a pull request soon.
