### ISSUE TITLE
typo on dockerhub vscode-devcontainer page

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-dev-containers#246]
Testing https://github.com/microsoft/vscode-remote-release/issues/2409

![image](https://user-images.githubusercontent.com/6461412/75334206-b5136d80-5887-11ea-9ead-2d1a6d59e23e.png)

The last list entry `mcr.microsoft.com/vscode/devcontainers/javascript-node:12` should be `typescript`

**Comment by Chuxel** [comment]
Whoops!  Good catch.  Will update.

**Comment by Chuxel** [comment]
Will be corrected with https://github.com/microsoft/mcrdocs/pull/381

**Comment by Chuxel** [comment]
Fixed!
