### ISSUE TITLE
Unable to extend existing Docker Compose and still use different Dockerfile

### ISSUE THREAD

**Issue by StevenLiekens** [microsoft/vscode-dev-containers#247]
Extending an existing _docker-compose.yml_ and overriding the _build_ section to reference a different _Dockerfile_ is not well supported. It seems that _docker-compose_ searches for a _Dockerfile_ in the wrong directory.

- VSCode Version: 1.42.1
- Local OS Version: Windows 10 version 1909 (build 1836.567)
- Name of Dev Container Definition with Issue: Existing Docker Compose (Extend)

Steps to Reproduce:

1. Extend an existing _docker-compose_ file
    - Remote-Containers: Add Development Container Configuration Files...
    - From 'docker-compose.yml'
2. Add a new _Dockerfile_ alongside _devcontainer.json_
3. Uncomment the _build_ section in _docker-compose.yaml_

https://github.com/microsoft/vscode-dev-containers/blob/bf82fa0128cec15e935d04bbb50761e45a907f37/containers/docker-existing-docker-compose/.devcontainer/docker-compose.yml#L18-L21

The workspace should look like this:

    D:\src\workspace
    │   docker-compose.yml
    │   (+ other project files)
    └───.devcontainer
            devcontainer.json
            docker-compose.yml
            Dockerfile

Reopening in a container fails on the build step.

    Building my-service
    ERROR: Cannot locate specified Dockerfile: Dockerfile
    Failed: docker-compose up
    Command failed: C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe --project-name workspace -f d:\src\workspace\docker-compose.yml -f d:\src\workspace\.devcontainer\docker-compose.yml up -d --build

**Comment by Chuxel** [comment]
Apologies for the delayed response here. We just updated the template with additional information that should resolve your problem. These paths are relative to the primary docker-compose.yml file rather than the one in the .devcontainer.  The comments have been updated as follows:

```yaml
# Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
# folder. Note that the path of the Dockerfile and context is relative to the *primary* 
# docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
# array). The sample below assumes your primary file is in the root of your project.
#
# build:
#   context: .
#   dockerfile: .devcontainer/Dockerfile
```

Please feel free to reopen if this does not resolve your problem.

**Comment by StevenLiekens** [comment]
Thanks, it's good to know that my workaround for this was actually the proper solution. Stay safe!
