### ISSUE TITLE
Go devcontainer fails to build some Go modules when running as a non-root user

### ISSUE THREAD

**Issue by kaharlichenko** [microsoft/vscode-dev-containers#249]
## Versions

- VSCode Version: 1.42.1
- Local OS Version: macOS Mojave 10.14.6
- Name of Dev Container Definition with Issue: go

## Steps to Reproduce

1. Create a new empty directory.
2. Open the directory in VS Code.
3. `> Remote-Containers: Add Development Container Configuration Files...`
4. Select `Go` template.
5. Open the `devcontainer/devcontainer.json` file.
6. Uncomment the `"remoteUser": "vscode"` line and put a `,` before it.
7. Create a `go.mod` file with the following content:

    ```go
    module github.com/microsoft/vscode-dev-containers/go-template-bug

    require github.com/mitchellh/go-homedir v1.1.0

    go 1.13
    ```

8. Create a `main.go` file with the following content:

    ```go
    package main

    import (
        "fmt"
        "github.com/mitchellh/go-homedir"
    )

    func main() {
        home, err := homedir.Dir()
        if err == nil {
            fmt.Println("Home directory is", home)
        } else {
            fmt.Println("Unable to resolve the home directory")
        }
    }
    ```

9. `> Remote-Containers: Reopen in Container`
10. Open the `main.go` file.
11. `> Debug: Run (Start Without Debugging)`

## Expected Outcome

Debug Console shows

```
Home directory is /home/vscode
Process exiting with code: 0
```

## Actual Outcome

Debug Console shows

```
build github.com/microsoft/vscode-dev-containers/go-template-bug: cannot load github.com/mitchellh/go-homedir: module github.com/mitchellh/go-homedir@latest found (v1.1.0), but does not contain package github.com/mitchellh/go-homedir
exit status 1
Process exiting with code: 1
```

## Analysis

The error message is quite cryptic. If we check the source code is actually there:

```
$ ls -l /go/pkg/mod/github.com/mitchellh
total 4
drwx-w--w- 2 root root 4096 Feb 27 21:58 go-homedir@v1.1.0
```

But it turns out that `go-homedir@v1.1.0` is neither readable nor openable for a non-root user. It would also be non-writable as well if not for the `chmod -R a+w /go/pkg` in the Dockerfile.

We can find a lot of other modules that would fail to build due to the permission issue:

```sh
find /go -type d -name '*@*' ! -executable 2> /dev/null
```

## Solution

All the packages in `/go` that end up in the image are leftovers from the Go tools installation. The end-user has no use for them.

If we build the Go tools in a throw-away `GOPATH` and only put the resulting binaries in the image this problem will go away.

**Comment by Chuxel** [comment]
Yeah looking at it, in vscode-remote-try-go we do `chmod -R a+rwX /go/pkg` to avoid the problem.  Let me take a look at your PR to see if that's a better option.
