### ISSUE TITLE
PHP & MySQL docker-compose.yml

### ISSUE THREAD

**Issue by KROSF** [microsoft/vscode-dev-containers#253]
something similar to [devilbox](https://github.com/cytopia/devilbox) could be great (a tiny version)

**Comment by Chuxel** [comment]
Thanks for the feature request!  Happy to take a look at a PR if you'd like to submit one.

**Comment by Chuxel** [comment]
@ThoolooExpress contributed a PHP7 & MariaDB definition! Check it out.
