### ISSUE TITLE
mcr.microsoft.com/java/jdk:8u232-zulu-ubuntu updated to 19.10, breaks Azure Functions

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#264]
@testforstephen @hexiaokai @brunoborges 

It looks like the `mcr.microsoft.com/java/jdk:8u232-zulu-ubuntu` image in MCR got updated to Ubuntu 19.10 because a distribution upgrade was [added into the Dockerfile 11 days ago](https://github.com/microsoft/java/commit/75aa80766854403d924a143366f2b61114cbb678#diff-13c7d7a346a7d5bf80c5a7c723c2b934).

The problem is that this causes the installation of the Azure Functions Core Tools to fail since there doesn't appear to be a package for that version.

Is this the correct image to be used or was this an accidental upgrade? There's no information about this update out in GitHub and right now the `azure-functions-java-8` definition is broken because of it.

**Comment by Chuxel** [comment]
//cc: @jeffhollan

The image referenced here appears to be focused more on internal Azure deployments. Should this be a standard open JDK base image instead to avoid unexpected breaks like this?

**Comment by jeffhollan** [comment]
@ahmelsayed @amamounelsayed to check this out and confirm the right base image is being used

**Comment by jeffhollan** [comment]
// @kulkarnisonia16 as well

**Comment by amamounelsayed** [comment]
@Chuxel Thank you for your question, the java function is using mcr.microsoft.com/azure-functions/java:3.0-java8-appservice --> This is use the azule version, we use mcr.microsoft.com/java/jre:8u212-zulu-debian9

The openjdk version, mcr.microsoft.com/azure-functions/java:3.0-java8

No idea what is azure-functions-java-8. mcr.microsoft.com/azure-functions/java:3.0-java8

What are trying to build and use?

**Comment by Chuxel** [comment]
@amamounelsayed This is a definition @testforstephen has been maintaining for [VS Code Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) to work with Azure Functions in Java inside a container. Its an environment you use to develop the function, not deploy the function.

There was an internal mail thread that landed on `mcr.microsoft.com/java/jdk:8u232-zulu-ubuntu` as the correct base image - but I am not aware of the specifics as to why that version was picked. Presumably that being closest to Azure.

Would `mcr.microsoft.com/java/jre:8u212-zulu-debian9` be the right one?  If so, that's an easy fix.

FWIW - What appears to be happening is this section is failing on installing `azure-functions-core-tools` because 8u212 is now based on Ubuntu 19.10.

```Dockerfile
    # Install Azure Functions, .NET Core, and Azure CLI
    && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/azure-cli.list \
    && echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list \
    && curl -sL https://packages.microsoft.com/keys/microsoft.asc | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
    && apt-get update \
    && apt-get install -y azure-cli dotnet-sdk-2.1 azure-functions-core-tools \
```

To see where this shows up, if you use the extension, you can run "Reopen Folder in Container" and pick this definition as a starting point:

![image](https://user-images.githubusercontent.com/312252/77484977-390a3800-6de9-11ea-980e-865e0bb4dfc7.png)

**Comment by ahmelsayed** [comment]
I just pushed the core tools package to 19.10 sources feed.

**Comment by Chuxel** [comment]
@ahmelsayed Perfect - looks like that resolved the core issue. 

FWIW - @amamounelsayed and I also had an offline conversation about the right way to maintain these going forward. Happy to have the right folks get access to do maintenance or we can even just directly reference an image. @anthonychu I'm sure can lend some insights into the right plan given he also submitted the Python definition here. 😀That said, this seems to resolve the immediate issue, so I'll close.

Thanks!

**Comment by anthonychu** [comment]
We probably should change this devcontainer to use `8u232-zulu-ubuntu-18.04` or another base image that's pinned to a specific OS major version.

The Python devcontainer uses `3.6-stretch`. They don't publish Python 3.8 images for Stretch. We probably should update that one to `3.8-buster`.

As for making sure Core Tools is published to all the relevant feeds automatically, we have an item https://github.com/Azure/azure-functions-core-tools/issues/1859 tracking that. /cc @ankitkumarr

**Comment by brunoborges** [comment]
Better yet if the base image was a bare bones Linux (could be Debian) and all tools were installed manually (not through apt), including the JDK.
