### ISSUE TITLE
azure-machine-learning-python-3 not supported by azureml-dataprep part of azureml-sdk

### ISSUE THREAD

**Issue by luuk-codebeez** [microsoft/vscode-dev-containers#265]
- VSCode insider
- Windows 10 Pro
- azure-machine-learning-python-3

The image 'azure-machine-learning-python-3' derives from continuum:anaconda3, which derives from Debian (https://github.com/ContinuumIO/docker-images/blob/master/anaconda3/debian/Dockerfile).

The supported linux distributions for azureml-dataprep are listed here and Debian is not one of them:
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-with-datasets#prerequisites

Steps to Reproduce:

1. use the azureml-sdk to register a Dataset in an azure ml workspace (https://docs.microsoft.com/en-us/learn/modules/work-with-data-in-aml/4-datasets)
2. This will cause the following issue: "NotImplementedError: Unsupported Linux distribution"

It seems the Linux distribution check is done very naively and does not allow Debian although Ubuntu is based on it. The same reportedly holds for Linux Mint based on Ubuntu 18:04 (https://github.com/Azure/MachineLearningNotebooks/issues/713) as it too is 'not supported'.

I have copied the contents of continuumio/anaconda3 and moved to Ubuntu:18.04 as a base image. This solves the issue and lets me register an azure-ml Dataset.

I would like to see the official vscode devcontainer for azure-ml actually supporting azureml-sdk and azureml-dataprep specifically. Although I did not test it I checked whether the suggested alternate base image (see comments in Dockerfile)  'python:3' would help and as far as I can see these are Debian only.  For now I would like to see full Conda and azureml-sdk support as these two are very relevant in the machine learning domain.

**Comment by Chuxel** [comment]
Thanks for reporting this!  That must be a new check - and I think Anaconda may have recently moved to Debian 10.

Can you see if the `.devcontainer` folder contents here work for you?

https://github.com/microsoft/vscode-dev-containers/tree/clantz/azure-ml-fix/containers/azure-machine-learning-python-3/.devcontainer

Unfortunately, I think getting the container up is slower since Anaconda is installed manually.

**Comment by luuk-codebeez** [comment]
thanks @Chuxel , I build a container from your branch and ran the azureml-dataprep code.

It works in relation to the bug I reported. 

remarks/questions:
- I would like to use the image as a base image for my own devcontainer
  - are there plans to host the image on a docker registry? (or have I missed something)
  - what would you advice to extend the container definition?

- On getting the dataset (tabular) and moving it to a pandas dataframe I get the warning shown below, which I solved by pip installing pyarrow>=0.12.0. The warning suggests adding the pandas extension for azureml-dataprep "pip install azureml-dataprep[pandas]" (not tested)

- azureml-dataprep seems to set locks inside the conda env folder.
  - this means we have to run as "root" inside the container (vscode user fails initiating azureml-dataprep engine, see error below)
  - I did not try to work around this in other ways such as chown or creating other envs than "base"


pyarrow dependency recommendation:
"""
/opt/conda/lib/python3.7/site-packages/azureml/dataprep/api/dataflow.py:722: UserWarning: Your pandas and pyarrow versions are incompatible. Please install pyarrow>=0.12.0 for improved performance of to_pandas_dataframe. You can ensure the correct version is installed by running: pip install azureml-dataprep[pandas].
  warnings.warn('Your pandas and pyarrow versions are incompatible.
"""

When using "vscode" user instead of root.
"""
 File "/opt/conda/lib/python3.7/site-packages/azureml/dataprep/api/engineapi/engine.py", line 268, in launch_engine
    dependencies_path = runtime.ensure_dependencies()
  File "/opt/conda/lib/python3.7/site-packages/dotnetcore2/runtime.py", line 116, in ensure_dependencies
    with _FileLock(deps_lock_path, raise_on_timeout=timeout_exception):
  File "/opt/conda/lib/python3.7/site-packages/dotnetcore2/runtime.py", line 92, in __enter__
    self.acquire()
  File "/opt/conda/lib/python3.7/site-packages/dotnetcore2/runtime.py", line 65, in acquire
    self.lockfile = os.open(self.lockfile_path, os.O_CREAT | os.O_EXCL | os.O_RDWR)
PermissionError: [Errno 13] Permission denied: '/opt/conda/lib/python3.7/site-packages/dotnetcore2/bin/deps.lock'
"""

**Comment by Chuxel** [comment]
> I would like to use the image as a base image for my own devcontainer
>
> - are there plans to host the image on a docker registry? (or have I missed something)
>- what would you advice to extend the container definition?

You can add another `RUN` statement to the Dockerfile to add things to it.  For example, to install the dependency you mention as the vscode user:

```Dockerfile
USER vscode
RUN pip install azureml-dataprep[pandas]
```
The main `RUN` statement is cached, so it will just be reused as you modify the Dockerfile which speeds up making changes as needed.  The `USER` statement will also default the container to run as vscode instead of "root".  You can add `USER root` right after the run if you do not want this to happen.

> On getting the dataset (tabular) and moving it to a pandas dataframe I get the warning shown below, which I solved by pip installing pyarrow>=0.12.0. The warning suggests adding the pandas extension for azureml-dataprep "pip install azureml-dataprep[pandas]" (not tested)

The Azure ML defaults are installed plus notebooks and automl.  You can install other things for your scenarios as appropriate. See above for the one you mention.

> azureml-dataprep seems to set locks inside the conda env folder.

The core issue here was that conda was not setup for use with a non-root user, so I fixed this problem.  Grab the latest versions of the files from the PR and see if it now works for you.

**Comment by luuk-codebeez** [comment]
Hi @Chuxel ,

I have build the devcontainer.

Your fix for the ownership of `/opt/conda` with `chown vscode \opt\conda` seems to be incomplete.
Subsequent installations are performed under root and thus the contents of `/opt/conda` is owned by root:root giving the same error as before.

I applied `chown -R vscode:root /opt/conda` which took a long while to complete. A more specific `sudo chown -R vscode:root /opt/conda/lib/python3.7/site-packages/dotnetcore2/bin` solves it too.

That last command demands some maintenance and I am not sure what is best.

**Comment by Chuxel** [comment]
> Subsequent installations are performed under root and thus the contents of /opt/conda is owned by root:root giving the same error as before.

How are you doing these installations?  Can you include a code snippet?

If you install anything as root, it will have root permissions.  So the trick is to use the "vscode" user to avoid that problem.  If you're doing this in a Dockerfile, the "USER" before your run statement should resolve this problem.

If you're running in the container as root, that would also install as root.  If you're running as vscode, then it will install as vscode.

```Dockerfile
USER vscode
RUN pip install azureml-dataprep[pandas]
```

**Comment by luuk-codebeez** [comment]
With 'Subsequent install' I did not mean install I added myself. I meant the installs happening at line: 59 in your Dockerfile.

**Comment by Chuxel** [comment]
@luuk-codebeez Are you grabbing the latest Dockerfile?  Like 59 is "        && conda activate base" \"

**Comment by luuk-codebeez** [comment]
oops, give me a moment to rebuild

**Comment by luuk-codebeez** [comment]
Ok, approved from my side. sry about the noise @Chuxel  and thank you
