### ISSUE TITLE
Azure Functions & Python 3.8

### ISSUE THREAD

**Issue by mchenier** [microsoft/vscode-dev-containers#270]
I just realize that the Azure Functions & Python 3 included in VSCode only has version 2.x of Azure Function core tools and version 3.6 of Python.

It will be usefull to update those containers so it support Python 3.8 and core tools 3.x

I have tried myself doing the upgrade and I was sucessful changing to Python 3.7.7 and core tools 3.x but the switch to 3.8 is a little more tricky because there is no version of python 3.8-stretch only buster or alpine and I tried buster and there was problem without trivial solution.

**Comment by Chuxel** [comment]
//cc: @anthonychu - Just to double check, will you be continuing to maintain the Azure Functions definitions or is there someone else on the team that should?  Happy to add whoever as a collaborator.

**Comment by Chuxel** [comment]
Oh - one more note, there's actually now a Python image that can be used that has git and the other common utilities installed to make this all easier.

mcr.microsoft.com/vscode/devcontainers/python:3.8 (or 3.7 or 3.6).

**Comment by anthonychu** [comment]
Waiting for Azure Functions Core Tools v3 to be published to the buster feed. We can bump to 3.7-stretch for now, but will be a couple of weeks before we can update to 3.8-buster (stretch not available). Good tip on mcr.microsoft.com/vscode/devcontainers/python:3.8. We can update it to that when the tools can be installed.
