### ISSUE TITLE
Cannot add tomcap server

### ISSUE THREAD

**Issue by sungle3737** [microsoft/vscode-dev-containers#281]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

## Cannot Add tomcat server?!
![ss](https://user-images.githubusercontent.com/27716524/79090245-facabd80-7d83-11ea-993e-df92ff2c5062.gif)

**Comment by Chuxel** [comment]
Unfortunately, I am unable to reproduce this problem.  It looks like you are using some sort of clipboard utility.  Does it work if you key it in directly without the utility?

If not, please include the platform you are running in (Windows, macOS, Linux) and the version of VS Code (or VS Code Insiders). You may also want to open an issue with the [extension author](https://github.com/adashen/vscode-tomcat).

**Comment by sungle3737** [comment]
I found the reason that java extension pack (java debug) was running in infinite loop (i dont know why)
- so i uninstalled java debug extension and reload
- after reload add server
- add extension again
### so if anyone experience same thing check another extension in infinite loop
I wish this can help others
