### ISSUE TITLE
dotnetcore-3.1: URL to nvm install script is no longer valid

### ISSUE THREAD

**Issue by vinman1** [microsoft/vscode-dev-containers#285]
### Problem
When the `$INSTALL_NODE` env var is 'true' (default) then this Dockerfile tries to install `node.js` via a `nvm` installation script. The current url of `https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh` no longer seems valid. The new url is `https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh`(as stated here: https://github.com/nvm-sh/nvm#install--update-script)

### Environment Details

VSCode: 1.44.1 (Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Installed Extensions:
- "ms-dotnettools.csharp"

### Reproduction Steps

1. Open the containers/dotnetcore-3.1 folder in the devcontainer.
   --> The _Building Image_ step of 'Starting with Dev Container' will fail with the following error:

  ```
  
  ... (Redacted for brevity)

[2020-04-15T20:18:45.687Z] [PID 17880] Selecting previously unselected package sudo.
(Reading database ... 13244 files and directories currently installed.)
Preparing to unpack .../sudo_1.8.27-1+deb10u2_amd64.deb ...
[2020-04-15T20:18:45.713Z] [PID 17880] Unpacking sudo (1.8.27-1+deb10u2) ...
[2020-04-15T20:18:45.838Z] [PID 17880] Setting up sudo (1.8.27-1+deb10u2) ...
[2020-04-15T20:18:45.900Z] [PID 17880] invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
[2020-04-15T20:18:46.153Z] [PID 17880] /bin/bash: /home/vscode/.nvm/nvm.sh: No such file or directory
[2020-04-15T20:18:46.343Z] [PID 17880] The command '/bin/sh -c apt-get update     && apt-get -y install --no-install-recommends apt-utils dialog 2>&1     && apt-get -y install git openssh-client less iproute2 procps apt-transport-https gnupg2 curl lsb-release
  && groupadd --gid $USER_GID $USERNAME     && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME     && apt-get install -y sudo     && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME    &
& chmod 0440 /etc/sudoers.d/$USERNAME     && if [ "$INSTALL_NODE" = "true" ]; then         mkdir ${NVM_DIR}         && curl -so- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash 2>&1         && cho
wn -R vscode:vscode ${NVM_DIR}         && /bin/bash -c "source $NVM_DIR/nvm.sh             && nvm install ${NODE_VERSION}             && nvm alias default ${NODE_VERSION}" 2>&1         && INIT_STRING='[ -s "$NVM_DIR/nvm.sh"
 ] && \\. "$NVM_DIR/nvm.sh"  && [ -s "$NVM_DIR/bash_completion" ] && \\. "$NVM_DIR/bash_completion"'         && echo $INIT_STRING >> /home/vscode/.bashrc         && echo $INIT_STRING >> /home/vscode/.zshrc         && echo $
INIT_STRING >> /root/.zshrc         && curl -sS https://dl.yarnpkg.com/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/pubkey.gpg | apt-key add - 2>/dev/null         && echo "deb https://dl.yarnpkg.com/$(lsb_release -is | t
r '[:upper:]' '[:lower:]')/ stable main" | tee /etc/apt/sources.list.d/yarn.list         && apt-get update         && apt-get -y install --no-install-recommends yarn;     fi     && if [ "$INSTALL_AZURE_CLI" = "true" ]; then
         echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/azure-cli.list         && curl -sL https://packages.microsoft.com/keys/microsoft.asc | apt-k
ey add - 2>/dev/null         && apt-get update         && apt-get install -y azure-cli;     fi     && apt-get autoremove -y     && apt-get clean -y     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
[2020-04-15T20:18:46.371Z] [PID 17880] [72189 ms] Command failed: docker build -f c:\ws\github\vscode-dev-containers\containers\dotnetcore-3.1\.devcontainer\Dockerfile -t vsc-dotnetcore-3.1-8c8a6621505b00890fbf516eed93de76 c:\ws\github\vscode-dev-containers\containers\dotnetcore-3.1\.devcontainer
  ```

### Expected Behavior

The devcontainer starts normally

**Comment by Chuxel** [comment]
Hmmm - I'm not sure that is what is going on here. https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh still resolves correctly, so this wouldn't cause the error you're seeing.

All that has happened is that the repo under creationix was switched to an organization called nvm-sh - likely due to recently announced [pricing changes](https://help.github.com/en/github/getting-started-with-github/faq-about-changes-to-githubs-plans) for GitHub.  So the GitHub repository will redirect, but the old URI is still valid.

Happy to update, but you shouldn't be seeing a failure.  It's possible this was a temporary situation during the move, because I'm not able to repro.  Can you retry?

**Comment by vinman1** [comment]
OK. Retried again from `master`. You're right, I'm no longer getting the error either. 

The call to `curl` was definitely the culprit earlier, but I didn't pay close enough attention to know the exact cause. As you say, probably only a temporary issue that now seems resolved. Maybe something to do with certs...

I'm closing this issue now since the problem can't be reproduced. 

Please feel free to accept the PR if you'd still like to update the `nvm` install script url to the new one.
