### ISSUE TITLE
Consolidate version specific definitions with a build arg, enable expansion in VS Code

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#294]
Now that build args are supported in devcontainer.json we can consolidate multiple versions of the same definition that vary only in the version of one piece of software.  Examples include the donetcore definitions, javascript/typescript-node, azure-terraform and more.

For those that include image builds, we can follow the model that is used in python-3 with a VARIANT arg that results in multiple image builds.

To round this out, we can expand these variants in the list that appears in VS Code when using commands like **Reopen in container** or **Add Development Container Configuration Files**.

To-do list:

- [x] Ubuntu 18.04, 20.04 (`base` image)
- [x] Debian 9, 10 (`base` image)
- [x] JS and TS Node.js 10, 12, 14 (`javascript-node`, `typescript-node` image)
- [x] .NET Core 2.1, 3.0, 3.1 (C# and F# definitions)
- [x] Java
- [x] Terraform 0.11, 0.12 (Azure Terraform)

Python is already set up this way.

**Comment by Chuxel** [comment]
Started with Ubuntu 20.04 for #303 in this branch: https://github.com/microsoft/vscode-dev-containers/tree/clantz/multi-tag-and-variant-expansion/containers

Changes were needed to the CI system to support version specific tags (e.g. "bionic"). This branch also gets metadata into the npm package for use in VS Code or Codespaces or wherever.

**Comment by felipecassiors** [comment]
I submitted a pull request, wasn't aware of your current work. Should it be closed? 

I would also want to say that might be also a good idea to change the base image from `ubuntu:20.04` to `buildpack-deps:focal` instead. And maybe reconsider the branding "git" on the container, because, isn't this too obvious?

**Comment by Chuxel** [comment]
@felipecassiors Yeah I am looking into some refactoring that will allow us to just change a property to generate another version of a given image.  I plan to start with Ubuntu 20.04 since it's top of mind.

In terms of using `buildpack-deps:focal` - The only downside is that image is 695MB where the fully built image here is around 252MB.  Are there things critically missing you think should be in the image?

I'm fine with removing the `-git`.

**Comment by felipecassiors** [comment]
@Chuxel the new approach sounds cool! 

The `buildpack-deps`, according to [its documentation](https://hub.docker.com/_/buildpack-deps/), was conceived to be used as the base for any language-stack image, which I suppose is exactly what this image is. Concerning the size is indeed a valid point, however without these "basic" dependencies, many users may find out that they'll have to install some other tools for running their projects with this image, which might not be so straight forward.

In my point of view, a development container should look closer to a desktop Linux distribution which is used to be shipped with full batteries-included (except for the fact that there is no graphical environment) than a fully lean container, such as the plain `ubuntu`.

The main question might be, what comes first: usability or image size? It would be good if we had other opinions.

**Comment by Chuxel** [comment]
@felipecassiors Yes, these things are always a balancing act which is why I'm asking what you think is missing. If you install Python, the needed packages are provided automatically, and with most workloads installing something will be required. That's why there's a number of images in this repository.

The `universal` (codespaces-linux) image is more of an all-in Ubuntu image that comes from buildpack-deps an adds a ton of other stuff, but it is huge as a result.  This is more of the "desktop" image.

So, the goal here would be to at least have a variant that is a reasonable "slim" starting point with core needs met. If we did base this on buildpack-deps, we'd want "ubuntu-slim" as well, which is why understanding the gaps is so important.

**Comment by felipecassiors** [comment]
I didn't know the `universal` image, it sounds cool. 

When I meant missing dependencies, I meant the project-specific ones which are not installed by default through `apt` when installing `python`. 

But your points are valid. And I didn't find any problem so far using this image. I agree to keep using the `ubuntu` as the base until, maybe later, we find a real reason for switching.

**Comment by Chuxel** [comment]
@felipecassiors One update here - looks like buildpack-deps:bionic-curl is perfect and only minimally affects image size, so I'll likely switch to that.  The reason the other is so big is it has a ton of different source control systems in it beyond git. More than doubles the image size.
