### ISSUE TITLE
pytest not working after upgrading to latest image

### ISSUE THREAD

**Issue by mchenier** [microsoft/vscode-dev-containers#300]
- VSCode Version: 1.44.2 (user setup)
- Local OS Version: Windows 10
- Name of Dev Container Definition with Issue: mcr.microsoft.com/vscode/devcontainers/python:0-3

I'm trying to get pytest work with the new image and VSCode. Note that this was working on the old python 3.6-stretch image.

First problem is that the Test discovery failed. The error says to look my setting.
Here is my settings.json

`{
    "azureFunctions.deploySubpath": ".",
    "azureFunctions.scmDoBuildDuringDeployment": true,
    "azureFunctions.projectLanguage": "Python",
    "azureFunctions.projectRuntime": "~3",
    "debug.internalConsoleOptions": "neverOpen",
    "python.pythonPath": "/usr/local/bin/python3.8",
    "python.linting.enabled": true,
    "python.testing.pytestEnabled": true
}`

I then try to run pytest manually in terminal.
I get this error.

    tokenUri = os.environ['tokenUri']
/usr/local/lib/python3.8/os.py:675: in __getitem__
    raise KeyError(key) from None

I then suppose that my local.settings.json is not loaded in the environnement.

Can you tell me witch part of the configuration I'm missing for this to work?

Thanks

**Comment by Chuxel** [comment]
@mchenier Are you using the Azure Functions definition or the Python one?  

@anthonychu @TsuyoshiUshio Assuming this is the Azure Functions definition given what is in the settings file, could this be a SDK related issue?

**Comment by mchenier** [comment]
@Chuxel 
Im not quite sure I understand what your asking me. You mean for the test? 
If there is a special test definition for Azure Function I didn't find anything on that so I assume I am using Python definition.

**Comment by Chuxel** [comment]
```
I'm trying to get pytest work with the new image and VSCode. Note that this was working on the old python 3.6-stretch image.
```

@mchenier I'm missing context here as to where the Dockerfile you are having trouble with came from. Did you create it? Was it added by VS Code by you selecting it from a menu (e.g. when using the "Reopen in container")?

`mcr.microsoft.com/vscode/devcontainers/python:0-3` is a like `python:3` which is Python 3.8.  If you need Python 3.6, use `mcr.microsoft.com/vscode/devcontainers/python:0-3.6` or just `mcr.microsoft.com/vscode/devcontainers/python:3.6`.

Maybe if you could include your Dockerfile and devcontainer.json that would help.

**Comment by mchenier** [comment]
@Chuxel 
I use the DockerFile that was added by VSCode when choosing Open folder In container. I choose Azure Functions & Python 3. I tried changing to 3.6 but it didn't help same problem with the local.settings.json variable that don't seams to be present in os.environ.

DockerFile
`#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

FROM mcr.microsoft.com/vscode/devcontainers/python:0-3

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# Configure apt and install packages
RUN \
    #
    # Install Azure Functions, .NET Core, and Azure CLI
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/azure-cli.list \
    && echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list \
    && curl -sL https://packages.microsoft.com/keys/microsoft.asc | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
    && apt-get update \
    && apt-get install -y azure-cli dotnet-sdk-3.1 azure-functions-core-tools-3 \
    #
    # Install Docker CE CLI (needed for publish with --build-native-deps)
    && apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common lsb-release \
    && curl -fsSL https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/gpg | apt-key add - 2>/dev/null \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable" \
    && apt-get update \
    && apt-get install -y docker-ce-cli \
    #
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /home/vscode/.local/share \
    && chown -R vscode /home/vscode

# Azure Functions Core Tools needs a place to save data
ENV XDG_DATA_HOME=/home/vscode/.local/share

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog
`

devcontainer.json
`// For format details, see https://aka.ms/vscode-remote/devcontainer.json or this file's README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.112.0/containers/azure-functions-python-3
{
	"name": "Azure Functions & Python 3",
	"dockerFile": "Dockerfile",
	"forwardPorts": [ 7071 ],
	"mounts": [ "source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind" ],

	// Set *default* container specific settings.json values on container create.
	"settings":  {
		"terminal.integrated.shell.linux": "/bin/bash"
	},

	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"ms-azuretools.vscode-azurefunctions",
		"ms-azuretools.vscode-docker",
		"ms-python.python"
	],
	
	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "npm install",

	// Uncomment to connect as a non-root user. See https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "vscode"
}`

**Comment by anthonychu** [comment]
@mchenier Can you share a repo that demonstrates this problem?

**Comment by mchenier** [comment]
@anthonychu 
I have created a simple repo so you can help me.
 https://github.com/mchenier/azure_test_env_var

When you run "python -m pytest" on this project you will get an error because the environnement variable wasn't found.

Maybe it is just me not understanding how local.settings.json work but when running pytest it is not loaded as envioronment variable. Is that an intended behaviour and have to pass environnement variable to pytest an other way?

**Comment by anthonychu** [comment]
Settings in local.settings.json are only loaded when running `func`. func reads the settings in the file and makes them available as environment variables in the functions host and your functions. When you run `pytest`, I would not expect those values to be loaded into the environment. However, I’m curious why it appeared to be working if you switched base images.

**Comment by mchenier** [comment]
I will find the old image I was using and make an other repo so we can compare.

**Comment by mchenier** [comment]
Ok with that simple example I have the same problem with the old image. I don't know how the env variable worked in my test earlier but the problem is not with the image. Sorry for my mistake. Im pretty sure it was working but it is for sure not related to the image.

But let me ask you what will be a valid way to load those local.settings.json into the test environment. Im using `func` to create a fake request but that doesn't seams enough. Or should my test have it's own envrionment variable ?

**Comment by mchenier** [comment]
This is definitly not an issue with the new image. There was an error with my original test making the os.environ never called. But I confirm that local.settins.json is not loaded in the environement variable when running pytest. I will have to look around what are the good way to do that.
Thanks.
