### ISSUE TITLE
Add Ubuntu 20.04 container

### ISSUE THREAD

**Issue by felipecassiors** [microsoft/vscode-dev-containers#303]
With the release of Ubuntu 20.04 LTS, I believe a good amount of developers would like to move their devcontainer from the 18.04 to this new LTS version as well.

I suggest to use [buildpack-deps:focal](https://hub.docker.com/_/buildpack-deps/) as the base, since it is an official Docker image based on ubuntu:20.04 with many common and basic dependencies used by developers already installed, such as `git` and `curl`.

**Comment by Chuxel** [comment]
Thanks for the suggestion!  Agreed we should add this.

**Comment by Chuxel** [comment]
Resolved with https://github.com/microsoft/vscode-dev-containers/pull/345
