### ISSUE TITLE
[java] Simplify Dockerfiles

### ISSUE THREAD

**Issue by brunoborges** [microsoft/vscode-dev-containers#31]
Currently, the Dockerfiles for Java are based on Maven and then they add Gradle manually.

Nowadays it is common for Java projects (whether Maven or Gradle) to come with proper wrappers that will download either of these build tools when build is first triggered, therefore making it the case where the installed version may not even be used, if different than what is defined in the project.

Simplifying the Dockerfiles will reduce the size to build and run the image for the first time, as it involves two downloads (Maven image, and then Gradle).

**Comment by Chuxel** [comment]
@testforstephen - Thoughts?

**Comment by brunoborges** [comment]
I'd also add that it is best to keep the basic image profiles simple and small, while also allowing users to customize/modify the setup in `.devcontainer` as they want.

Once [this enhancement](https://github.com/Microsoft/vscode-remote-release/issues/115) is delivered, users can then choose the publicly available Maven or Gradle images from Docker Hub.

**Comment by Chuxel** [comment]
> Once this enhancement is delivered, users can then choose the publicly available Maven or Gradle images from Docker Hub.

Let's set this topic aside here. This repo is intended to be for curated definitions that are known to work and be customizable.

**Comment by testforstephen** [comment]
My opinion is keeping maven as the base image, because maven is the current dominant build tool. This will make sure most of java project works regardless of it containing mvn wrapper or not.

But we could wipe out the gradle part from the predefined dockerfile. Instead, comment some alternative base image in the dockerfile header.
```
FROM maven:3-jdk-8

# An alternative docker image only with openjdk installed.
# FROM openjdk:8-jdk

# An alternative docker image with gradle and openjdk installed.
# FROM gradle:latest
```

**Comment by brunoborges** [comment]
I see two issues today with this Dockerfile having both Gradle and Maven out of the box:

1. Projects use either Maven or Gradle. Never both.
1. When the image is built, it takes a while because it needs to pull the `maven:3-jdk-8` image, and then during build it will download the Gradle package. This adds up in build time.
1. Users want either JDK only, Maven (JDK implicit) or Gradle (JDK implicit). They will search for Java, Maven, or Gradle. And as you know, searching for Maven or Gradle won't result in any entry in the VS Code extension (Open/Reopen folder in container).

Currently, the curated images for Java are displayed this way:

![image](https://user-images.githubusercontent.com/129743/57487508-2a756980-7287-11e9-9b26-ce210852689e.png)

Because the FROM of the Dockerfile is `maven:3-jdk-8`, this text is displayed, and there is no way for users to know through this experience, if Gradle will be present.

I believe this Dockerfile should be simplified, and we should provide `java-maven` and `java-gradle` Dockerfiles.

**Comment by Chuxel** [comment]
@brunoborges We might want to be a bit careful on the number of variations reasonable since splitting maven and gradle would double everything.

@brunoborges @testforstephen  A suggestion - perhaps the thing to do here would be to start from `openjdk` and then have the maven **and** gradle install steps commented out in the Dockerfile.  The main addition to the current files would be maven installation, but again commented out.  The README can mention this and if someone isn't using `gradelw` (or just wanted it pre-installed) they'd then have the template to add it in by just commenting it.  The samples could then use the maven wrapper.

Also has the upside of speeding up initial provisioning of the container for first time use.  Thoughts?

**Comment by brunoborges** [comment]
@Chuxel the problem is that the image build is triggered right after I select Open/Reopen, which does not give me time to adjust the Dockerfile accordingly.

**Comment by Chuxel** [comment]
@brunoborges Depends on how you add them to your project. **Remote-Containers: Add Container Configuration Files...** does not do that.  You can also **Remote-Containers: Rebuild Container** to make changes.

As an alternative, both could be installed by default with a note to comment out the one they don't use.

**Comment by brunoborges** [comment]
The action is labeled `>Create Container Configuration File` which is why I was confused. Perhaps it should be `Add Predefined Container Configuration`.

**Comment by brunoborges** [comment]
I also wouldn't be concerned with a "big list". There are large sets already:

Python:
![image](https://user-images.githubusercontent.com/129743/57488747-5b0ad280-728a-11e9-82ad-aa1f4a9f8e81.png)

Node:
![image](https://user-images.githubusercontent.com/129743/57488767-6b22b200-728a-11e9-9fb7-93ffaa364db9.png)

**Comment by Chuxel** [comment]
@brunoborges It also supports existing `Dockerfiles` and `docker-compose.yml` which are not-predefined.  (In fact so does open folder in container). The configuration file it creates is `devcontainer.json`.

**Comment by brunoborges** [comment]
But selecting the current action `Create Container Configuration File...` I get a `.devcontainer` folder with devcontainer.json, Dockerfile, and settings.vscode.json.

So...

**Comment by Chuxel** [comment]
@brunoborges Yes, but these are all unique language configurations and runtimes.  (JS and TS is more like Java and Groovy.)  Python has distinct runtime distributions targeted at different use cases like Anaconda. The Node definitions include both the npm and yarn packaging systems.  They also do not include build systems at all.  If we added "gulp" and "grunt" to the Node definitions, they'd all double.  

Java's the only place where we've been talking about separating for a packaging system.

**Comment by Chuxel** [comment]
> But selecting the current action Create Container Configuration File... I get a .devcontainer folder with devcontainer.json, Dockerfile, and settings.vscode.json.

If you pick a definition with those, yes. As I said, that's not the only outcome since you can reuse an existing Dockerfile.  "Dev Container Definition" is the term for these pre-defined ones, but you don't have to pick one of those at all if you've got existing container config.

**Comment by brunoborges** [comment]
Well, I'm trying to help enhance the Day 1 experience for Java developers.

**Comment by brunoborges** [comment]
The easiest way to get started is by picking a predefined configuration, and then adjust accordingly.

So we are down to this so far:

1. Change label to `Add Container Configuration...`
1. Simplify Dockerfile for Java apps to not extend from Maven and instead have helper instructions to adjust accordingly to user's preference.

**Comment by Chuxel** [comment]
> Change label to Add Container Configuration...

Lets separate this one since it's a bit off topic.  We probably need to brainstorm a bit on what we'd call it... "container configuration"  may be the problem since that implies Dockerfile to some extent.  We can raise the topic for feedback on vscode-remote-release since that's where product discussions are happening. 

>Simplify Dockerfile for Java apps to not extend from Maven and instead have helper instructions to adjust accordingly to user's preference.

Yep - I'd suggest you guys chat and decide what you want to do.  I'm mainly providing some advice based on what other teams have been doing.

**Comment by testforstephen** [comment]
After the discussion, we reached the following solution:
- Use openjdk as the base image of Java Dockerfiles.
- Comment out the steps to install maven and gradle build tools so users can choose to enable later.
