### ISSUE TITLE
Puppet PDK Container Image

### ISSUE THREAD

**Issue by jpogran** [microsoft/vscode-dev-containers#316]
I contributed the `Puppet Development Kit - Dockerfile` devcontainer [config](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/puppet).

I would like to contribute a devcontainer config that points to the official Puppet PDK docker [image](https://hub.docker.com/r/puppet/pdk), but do not know if you would want the existing devcontainer updated to use the image instead of a docker file, or an new  devcontainer folder created. Let me know which you would like and I'll put up a PR.

**Comment by Chuxel** [comment]
Thanks for asking!  I'd suggest updating the existing one since it sounds like it would hit the same need.  Really appreciate the contribution.

Anywhere that the existing contents are referenced in something like a comment from the VS Code tool pins to a tag in the repository, so you don't need to worry about that particular part either.

**Comment by jpogran** [comment]
Thanks for confirming. Do you think I should leave the dockerfile and comment out the line in `devcontainer.json`, with an additional comment that they can use the dockerfile for more customization, or just remove it entirely as too much to get confused by.

**Comment by Chuxel** [comment]
We're now pre-building some of the development containers, and what we've been doing is keeping a Dockerfile that just points to the image with some comments on how to customize.  We've also had other external teams / companies take ownership of building their own images.  Here's a few examples:

* Here's what ends up getting added to your project for Python now: https://github.com/microsoft/vscode-dev-containers/blob/master/containers/python-3/.devcontainer/Dockerfile

* The Azure Functions Java team did one that just has the FROM with a link to the Dockerfile in their own repo: https://github.com/microsoft/vscode-dev-containers/blob/master/containers/azure-functions-java-8/.devcontainer/Dockerfile

* Salesforce went even more basic: https://github.com/microsoft/vscode-dev-containers/blob/master/containers/sfdx-project/.devcontainer/Dockerfile

But, if you think most people won't even need the Dockerfile, you could use an image reference too.  Either one should work in Remote - Containers (and Codespaces in GitHub or Azure).

**Comment by jpogran** [comment]
I tested the options above, and I think I've settled on the first one, it seems to give the most flexibility with the least amount of change. Would you prefer a new PR or to use #315 where I am updating the extension name

**Comment by Chuxel** [comment]
Updating #315 probably makes sense. No need to do a separate one.

**Comment by jpogran** [comment]
Thanks for answering all the questions @Chuxel, I updated #315 with the new commit

**Comment by jpogran** [comment]
Looks like #315 was merged, so closing this. Thanks!
