### ISSUE TITLE
Pytest discovery not working in python3 image

### ISSUE THREAD

**Issue by jahan01** [microsoft/vscode-dev-containers#337]
- VSCode Version: 1.45.1
- Local OS Version: Mac OS 10.15.4 
- Name of Dev Container Definition with Issue: `/containers/python-3/.devcontainer/devcontainer.json`

Steps to Reproduce:

1. Use any python repo with this workspace settting `"python.testing.pytestEnabled": true,`
2. You ll see python test discovery fails with below error in _Python Test Log_ channel in _Output_ panel
    ```
    Test Discovery failed: 
    Error: Traceback (most recent call last):
    File "/home/vscode/.vscode-server/extensions/ms-python.python-2020.5.78807/pythonFiles/testing_tools/run_adapter.py", line 17, in <module>
        from testing_tools.adapter.__main__ import parse_args, main
    File "/home/vscode/.vscode-server/extensions/ms-python.python-2020.5.78807/pythonFiles/testing_tools/adapter/__main__.py", line 9, in <module>
        from . import pytest, report
    File "/home/vscode/.vscode-server/extensions/ms-python.python-2020.5.78807/pythonFiles/testing_tools/adapter/pytest/__init__.py", line 7, in <module>
        from ._discovery import discover
    File "/home/vscode/.vscode-server/extensions/ms-python.python-2020.5.78807/pythonFiles/testing_tools/adapter/pytest/_discovery.py", line 8, in <module>
        import pytest
    ModuleNotFoundError: No module named 'pytest'
    ```

This may because that pytest is not added to **PYTHONPATH** environment variable?

**Comment by Chuxel** [comment]
@brettcannon Brett - I assume the reason this is happening because we've got pytest installed using PIPX to avoid module conflicts, is that correct? Given this code appears to be doing a direct import, should we be installing pylint globally?

**Comment by brettcannon** [comment]
It's because users are expected to have pytest installed as part of their project so it can be impored. I honestly overlooked the fact that pytest was being installed by pipx as part of the Dockerfile.

**Comment by Chuxel** [comment]
@brettcannon Should we move it global or not include it all given that?  (Also, any other tools we need to consider?)

**Comment by brettcannon** [comment]
- I wouldn't bother including it
- Looking at https://github.com/microsoft/vscode-dev-containers/blob/master/containers/python-3/.devcontainer/base.Dockerfile, pytest is the only thing that should probably get dropped

**Comment by Chuxel** [comment]
@jahan01 Installing pytest yourself should resolve the issue. We'll remove it from future versions of the image to avoid confusion.
