### ISSUE TITLE
Azure Functions definitions stopped working with recent image update

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#340]
@TsuyoshiUshio Something appears to have changed in the images referenced in the Azure Functions Node.js 10, 12, and Python definition that broke the dev containers.  

I think this happened either Sunday or today, since regression tests ran successfully on Saturday.

In the case of the node images, there is no longer a `node` user in the image while this is referenced in the `devcontainer.json`.  Python 3 is similar, but is missing a `vscode` user instead.

`git` and other tools are also now missing.

Is it possible that the wrong Dockerfile was used to build an update to the referenced image?

**Comment by Chuxel** [comment]
Log example:
```
[1281 ms] Start: Run in container: uname -m
[1339 ms] Start: Run in container: cat /etc/passwd
[1339 ms] Stdin closed!
[1341 ms] Shell server terminated (code: 126, signal: null)
unable to find user node: no matching entries in passwd file
```

If you remove `"remoteUser": "node"` from `devcontainer.json`, it starts, but `git` fails:
```
root@802bde3acb71:/workspaces/vscode-dev-containers/containers/azure-functions-node-10# git
bash: git: command not found
root@802bde3acb71:/workspaces/vscode-dev-containers/containers/azure-functions-node-10# 
```

I'm pretty sure it's the app service image because this is the ENTRYPOINT:
```
/azure-functions-host/start.sh
```
like: https://github.com/Azure/azure-functions-docker/blob/master/host/3.0/buster/amd64/node/node10/node10-appservice.Dockerfile

**Comment by TsuyoshiUshio** [comment]
Sorry @Chuxel Actually, I do nothing between Sun and Today for publishing. I'll investigate the root cause and rollback as fast as I can.

**Comment by TsuyoshiUshio** [comment]
Hi @Chuxel I rollback three images (node-10, node-12, python) and I tested locally, now I believe, its fine. 
Could you add me your CI system to get notification of the failure of the azure functions related images? The root cause is old version seems released. (The node bug was happened before Friday). I try not to happen again this. I'm very sorry about that and thank you for pinging me!

**Comment by Chuxel** [comment]
@TsuyoshiUshio Yep things look good now.

The regression test suite runs in a different internal repo given what it needs access to. I can look at adding you given you are internal, but it tests all definitions, so you'd get notices even if it didn't apply to the Azure Functions definitions.
