### ISSUE TITLE
.npmignores refering to definition-build.json

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-dev-containers#359]
These need to be updated:
![image](https://user-images.githubusercontent.com/9205389/83498894-cd190f80-a4bc-11ea-82d4-b338162d5b33.png)

**Comment by Chuxel** [comment]
Good catch - must have missed this with a merge. Fixed in https://github.com/microsoft/vscode-dev-containers/commit/730d3ff110d1f735507583ca3441f0b6ecb84c4f.
