### ISSUE TITLE
Missing dependency for black in python-3 devcontainer

### ISSUE THREAD

**Issue by ajschmidt8** [microsoft/vscode-dev-containers#361]
**Environment Info:**
- VSCode Version: 1.45.1
- Local OS Version: Ubuntu 20.04
- Name of Dev Container Definition with Issue: [python-3](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3)

**Issue:**
The [black](https://github.com/microsoft/vscode-dev-containers/blob/master/containers/python-3/.devcontainer/base.Dockerfile#L37) package in the [python-3](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3) devcontainer does not work out of the box. It seems to be missing the [click](https://pypi.org/project/click/) dependency.

**Steps to Reproduce:**

1. Do a docker build on [base.Dockerfile](https://github.com/microsoft/vscode-dev-containers/blob/master/containers/python-3/.devcontainer/base.Dockerfile) (i.e. `docker build -t pydc:test -f base.Dockerfile .`
2. Run the container with the following command to see the error:
`docker run --rm -it pydc:test bash -c "black"`

![image](https://user-images.githubusercontent.com/7400326/83826382-c8fe1500-a6a9-11ea-9f90-47db4704851f.png)

It works fine once `click` is installed:
 `docker run --rm -it pydc:test bash -c "pip install click; black"`

![image](https://user-images.githubusercontent.com/7400326/83826436-e4692000-a6a9-11ea-8d84-713dac37744d.png)

Also worth noting is that I think the only reason `black` works in the [vscode-remote-try-python](https://github.com/microsoft/vscode-remote-try-python) devcontainer is because it [installs flask](https://github.com/microsoft/vscode-remote-try-python/blob/master/.devcontainer/devcontainer.json#L37) which has `click` as a dependency.

**Comment by Chuxel** [comment]
Wild - thanks for catching it. I'm surprised the dependency didn't get installed - seems like a bug in the black package. We should be able to patch for it - also explains why we missed it.

**Comment by Chuxel** [comment]
Figured out what was going on and resolved it.  Thanks again!

**Comment by ajschmidt8** [comment]
Nice! No problem. What was the issue? I'm perplexed as to why `--force-reinstall` fixed it

**Comment by Chuxel** [comment]
pipx is installed in a user location while other tools are installed. To ensure the tools can interact with global packages, the `--system-site-packages` flag is passed in. This finds pipx in its temporary location which itself installs `click`, so it assumes its already installed. Forcing reinstall causes it to be installed in the venv which resolves the problem.

**Comment by ajschmidt8** [comment]
@Chuxel, thanks for that explanation. Two more quick questions.

1) Is there an online repository similar to DockerHub where I can view all of the VSCode Devcontainer image and tags? I tried navigating to [mcr.microsoft.com/vscode/devcontainers/python](http://mcr.microsoft.com/vscode/devcontainers/python) from [here](https://github.com/microsoft/vscode-dev-containers/blob/master/containers/python-3/.devcontainer/Dockerfile#L8), but that didn't seem to work.

2) What's the difference between these image tags:
  - mcr.microsoft.com/vscode/devcontainers/python:0-3.8
  - mcr.microsoft.com/vscode/devcontainers/python:3.8
