### ISSUE TITLE
Update Ansible devcontainer to support Collections

### ISSUE THREAD

**Issue by InTheCloudDan** [microsoft/vscode-dev-containers#368]
I tried to use: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/azure-ansible/.devcontainer as basis for Ansible Collection development. An immediate issue I ran into is that the mount is not to the default COLLECTIONS_PATH. It could either mount a volume to that location or set an environment variable for it.

I'm just learning my way around these containers or I'd offer a PR for the functionality.

**Comment by Chuxel** [comment]
> An immediate issue I ran into is that the mount is not to the default COLLECTIONS_PATH. It could either mount a volume to that location or set an environment variable for it.

@cmendible, should we make a tweak here?

**Comment by cmendible** [comment]
@InTheCloudDan check if https://github.com/microsoft/vscode-dev-containers/pull/379 works for you. This will mount the folder **.ansible/collections** from your local profile into the container.

**Comment by Chuxel** [comment]
Closing since #379 should have this covered. Feel free to reopen if that is not the case.  Thanks much!
