### ISSUE TITLE
Add Go image to Docker Hub or similar so we can use as a base image for ./devcontainer/Dockerfile, rather than cloning.

### ISSUE THREAD

**Issue by leighhopcroft** [microsoft/vscode-dev-containers#397]

**Comment by Chuxel** [comment]
@hyangah Would adding `"go.useGoProxyToCheckForToolUpdates": false` to settings make the tools stable enough that a pre-built image would be viable?  Part of the reason I'd held off was how often the tools updated and that people kept getting toasts to update.  A pre-built image would be even more likely for that to happen.

**Comment by hyangah** [comment]
@Chuxel How frequently does the container image get updated? Since `gopls` is under active development, I think update notification is a feature. But yes, it will be annoying if users have to install the `gopls` whenever starting a new session.

@stamblerre @Chuxel Is it possible to arrange the container image release synchronized with gopls stable version release?

**Comment by Chuxel** [comment]
@hyangah The images in this repo sym-ship with VS Code releases primarily, so I don't know that we can do that from here realistically. What teams that need different release schedules have done is create their own image and just reference it from here.  As you've seen, there's a common script that can be referenced either via curl or directly.

Is the issue just `gopls`? We could have that one in the Dockerfile while the rest are pre-built in the image I suppose. Even that would help quite a bit.

**Comment by hyangah** [comment]
If it's aligned with VS Code releases, it will be updated monthly. That's frequent enough to pick up the recent version. 
So, disabling the tool update check seems ok.

For now, yes, only `gopls` is utilizing this feature.

**Comment by Chuxel** [comment]
@hyangah Great! Do people get notified if the other tools are out of date? Does setting `"go.useLanguageServer": true` change that at all?

**Comment by hyangah** [comment]
@Chuxel We don't have version checks for other tools yet. Only the `gopls`, which is used when `"go.useLanguageServer": true`.
