### ISSUE TITLE
.NET 3.1.302 SDK not installed on codespace-linux

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode-dev-containers#398]
- Name of Dev Container Definition with Issue: codespace-linux

Steps to Reproduce:

1. Create a Codespace w/Linux using a Blazor Wasm app repo
2. Attempt to build
EXPECT: Success
ACTUAL: Fail as Blazor Wasm build components in 3.1.302+ SDK for .NET Core which is not present as of the date of this report

**Comment by Chuxel** [comment]
//cc: @edgonmsft

**Comment by timheuer** [comment]
@chuxel - looks like it actually needs to be here: https://github.com/microsoft/Oryx/blob/c2314bce463ceb6c82be1291c1f6f78e5fcab14f/platforms/dotnet/versionsToBuild.txt#L28 as a new line...

**Comment by Chuxel** [comment]
This should be updated in the current `dev` image `mcr.microsoft.com/vscode/devcontainers/universal:dev`

**Comment by Chuxel** [comment]
Closing since this should be resolved and will be deployed into Codespaces soon.
