### ISSUE TITLE
Node + Postgres

### ISSUE THREAD

**Issue by preconception** [microsoft/vscode-dev-containers#42]
Could you make a container template with node + postgres instead of mongodb?

**Comment by Chuxel** [comment]
@preconception Thanks for the request!

The great news is that this is an open source repository, so we'd welcome any contributions in this area you're interested in making.  See [here](https://github.com/microsoft/vscode-dev-containers/blob/master/CONTRIBUTING.md#contributing-dev-container-definitions) for details.

**Comment by Chuxel** [comment]
Resolved by #84
