### ISSUE TITLE
Java dev container template has an ineffective cleanup step

### ISSUE THREAD

**Issue by ilkka** [microsoft/vscode-dev-containers#422]
I don't think this cleanup step in the Dockerfile for the java-11 dev container (probably the other versions too) is doing what it is intended to do:

https://github.com/microsoft/vscode-dev-containers/blob/dfda2f5e04c41c7902216b149d4abce1f6f54e23/containers/java-11/.devcontainer/Dockerfile#L53-L56

Removing files and/or packages in a separate RUN instruction will simply render them invisible in the final flattened container FS, but they will still be part of the image layer stack i.e. they will take up disk space. If the intent is simply to make them invisible this is of course perfectly fine, but if the intention is to make the image smaller, I believe this is not an effective strategy.

This is mitigated a bit by the fact that for a while now already, basically all Debian-derivative Docker images have had APT hooks in place that remove any downloaded package files after each run, therefore `apt-get clean` in this context doesn't really do anything. Package lists would still need to be removed if one wants to save the space that they take up.

**Comment by Chuxel** [comment]
//cc: @testforstephen @akaroml - Some feedback on the dev container for Java.

**Comment by testforstephen** [comment]
@Chuxel Looks like this is not a Java specific issue, i see other dev container such as go is using the similar logic. It's better to have someone to fix this systematically.
https://github.com/microsoft/vscode-dev-containers/blob/dfda2f5e04c41c7902216b149d4abce1f6f54e23/containers/go/.devcontainer/Dockerfile#L65-L68

**Comment by Chuxel** [comment]
@testforstephen The issue here is that it's in a different `RUN` which is not the case in other places.  Each `RUN` is a separate layer, so if the previous layer doesn't have the cleanup step in it, the contents are effectively in the image.  The Go definition you reference does not have this problem.
