### ISSUE TITLE
Default Codespaces image has misconfigured .NET Core SDKs

### ISSUE THREAD

**Issue by JoeRobich** [microsoft/vscode-dev-containers#428]
- VSCode Version: 1.45.1 (VS Codespaces)
- Local OS Version: Debian 9 (Default Codespaces image)
- Name of Dev Container Definition with Issue: codespaces-linux

We've had a report on the VS Code C# extension about projects not loading properly using the default codespaces image. See https://github.com/OmniSharp/omnisharp-vscode/issues/3913

The issue seems to be that references assemblies are not loaded (available) during design time builds.

The workaround seems to be to delete the /home/codespaces/.dotnet folder and to install the dotnet-sdk-3.1 package using apt. See https://github.com/OmniSharp/omnisharp-vscode/issues/3913#issuecomment-663749636

## Steps to Reproduce ##

1. Create a new VS code online (codespaces) instance with the standard image.
1. Create a new web api with `dotnet new webapi`
1. Install C# extensions
1. Open `.cs` file and look at the highlighting and errors.

**Comment by JoeRobich** [comment]
This issue seems to be that the .App.Ref packs are missing.

Installed on the default codespaces image:
![image](https://user-images.githubusercontent.com/611219/88441796-19027980-cdc7-11ea-86d2-37d8b3631084.png)

Delivered in the Linux binaries tar.gz:
![image](https://user-images.githubusercontent.com/611219/88441841-3e8f8300-cdc7-11ea-90b2-01ec37e20ead.png)

I have verified that adding only these missing pack folders fixes the issue with project loading in the C# extension.

**Comment by Chuxel** [comment]
//cc: @edgonmsft Is this solved by #404 that was just merged?

**Comment by edgonmsft** [comment]
I think it will let me validate.

//cc: @dmgardiner25

**Comment by JoeRobich** [comment]
Verified that the current version of the Symlinking script (https://github.com/microsoft/vscode-dev-containers/blob/master/containers/codespaces-linux/.devcontainer/symlinkDotNetCore.sh#L19) seems to be doing the right thing by running it in my Codespaces environment. 

The issue seems to be that VS Online (Codespaces) is using an old version of the codespaces-linux .devcontainer.

These are the listed SDKs installed by Oryx
![image](https://user-images.githubusercontent.com/611219/88598756-d1762a80-d01e-11ea-83fd-2b8f5bcc4b88.png)

**Comment by edgonmsft** [comment]
Thanks! The change to this newer version will be on this weeks release.

**Comment by Chuxel** [comment]
Great! Closing the issue here given we're now just waiting for deployment.

**Comment by JoeRobich** [comment]
When is the rollout expected for this week? I would like to validate and update our issue when it is resolved.

-Joey
