### ISSUE TITLE
Jekyll - can we run postCreateCommand: bundle install by default?

### ISSUE THREAD

**Issue by jongio** [microsoft/vscode-dev-containers#447]
Right now, users have to run `bundle install` manually.

Can we uncomment this line so it runs automatically?

https://github.com/microsoft/vscode-dev-containers/blob/v0.128.0/containers/jekyll/.devcontainer/devcontainer.json#L17

This is what I have:
`"postCreateCommand": "bundle install",`

Not sure you need "input.projectName"

@cmendible

**Comment by cmendible** [comment]
Running bundle install without a Gemfile will result in: **Could not locate Gemfile** on startup which would be the case if you are starting a new project or you are still learning the ways of jekyll without plugins.

I'll remove the **cd ${input:projectName} &&** but leave the comments. Thoughts?

**Comment by jongio** [comment]
Okay, thanks.    I was also thinking...what if we also add the serve command, so when the container loads the site is all ready to be hit.  I like that.

**Comment by Chuxel** [comment]
@cmendible Let me know your thoughts here - I'll wait on merging to avoid another update if you think this makes sense.

**Comment by cmendible** [comment]
@jongio can you confirm that the PR can be merged? I know it's working for your usecase 😉

**Comment by Chuxel** [comment]
Merged for now. Feel free to reopen if more discussion is required.

**Comment by ItalyPaleAle** [comment]
I proposed some changes in #661 that would automatically run bundle install if a Gemfile is present. @jongio can you take a look too and let me know your thoughts?
