### ISSUE TITLE
Add Ruby container

### ISSUE THREAD

**Issue by mhoad** [microsoft/vscode-dev-containers#457]
I was looking at forking the Python example and trying to create one for Ruby but I'm pretty inexperienced with Docker and I don't know how much I trust myself to come up with anything worthwhile to contribute back. I figured given that Github itself (a Microsoft company) is developed on Rails that there might be better people out there to potentially help with something like this so I wanted to create a feature request so any discussion around the topic at least had somewhere to live :)

**Comment by Chuxel** [comment]
I assume you closed because you found the three variations that exist for it.  Let us know if there's anything we should change!
