### ISSUE TITLE
Java extension no longer supports Java 8, update Azure Functions to JDK 11?

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#459]
It appears that Eclipse and by extension the Java VS Code extension no longer supports JDK 8. So the following error appears:

![image](https://user-images.githubusercontent.com/312252/89090534-53848d00-d358-11ea-90fb-48b02cc872fd.png)

I'm thinking we should probably remove `azure-functions-java-8` or update it to JDK 11 even though that is in preview.  Thoughts?

//cc: @anthonychu @TsuyoshiUshio

**Comment by anthonychu** [comment]
@TsuyoshiUshio Is VS Code currently broken for Java 8 function apps?

/cc @apawast

**Comment by anthonychu** [comment]
My read on [this issue](https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-663382692) is that the _extension_ now requires Java 11, but can be configured to work with Java 8 projects. A Java 8 Functions devcontainer with this pre-configured would actually be useful for helping customers get up and running.

**Comment by Chuxel** [comment]
>My read on this issue is that the extension now requires Java 11, but can be configured to work with Java 8 projects. A Java 8 Functions devcontainer with this pre-configured would actually be useful for helping customers get up and running.

@anthonychu @TsuyoshiUshio @apawast Got it. Quick ping here since this is "endgame" week for the next VS Code release. Should I assume that the image referenced in this definition will get updated to include the Java 11 runtime as well, or should we tactically remove it for this release?

**Comment by TsuyoshiUshio** [comment]
I think we should keep Java 8 and add Java 11. I already has the image. We support both.

**Comment by anthonychu** [comment]
Yes we should have devcontainers for both Java 8 and Java 11. I think the problem here is the latest version of the VS Code Java extension now runs on Java 11, which is missing from the image. Both Java 8 and 11 need to be in the image and there needs to be config in devcontainer.json to set [`java.configuration.runtimes` and `java.home`](https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-663382692).

**Comment by TsuyoshiUshio** [comment]
Thank you, @anthonychu , I'll reproduce it and fix it.

**Comment by TsuyoshiUshio** [comment]
Hi @anthonychu and @Chuxel , 
I create a quick fix PR. I tested it and make sure it works on Java8 function app. 
I'm on call now, so I'll create java 11 PR soon.

**Comment by amamounelsayed** [comment]
Hey @anthonychu Just wondering are we going to,
- Have one image that support java 8 and java 11? Then we need to rename the current container to just java-container.
- Have one image support java 8, and different image support java 11? -- In this case I believe java 8 image should show plugin warning in the UI because it is java 8. Then it is up to the user to use the java 11 or live with java 8 and see the warning.

Note java 8 image is working, this is just a warning.

**Comment by anthonychu** [comment]
> Note java 8 image is working, this is just a warning.

@amamounelsayed Yes it's true that the image itself is working, but this is not a warning. The Java language server is not working so there is no intellisense, refactorings, etc unless Java 11 is also installed and configured as in #468. I recommend fixing this as Java 8 in Functions is going to be supported in the foreseeable future and customers should be able to create an devcontainer environment that is fully working.

> Have one image that support java 8 and java 11? Then we need to rename the current container to just java-container.

I think a single image could work, but keep in mind there are customers who are already using the `3.0-java8-core-tools` tag. This tag should continue to point to an image that has Java 8 as the default so it's not breaking.

**Comment by TsuyoshiUshio** [comment]
Hi @Chuxel , @anthonychu , and @amamounelsayed 

## PR for Java 11
I create a PR for the Java 11 Functions.  
It works, however, The Azure Functions extension for VSCode haven't supported Java 11 yet. (It is planned at the end of this month.) However, we don't need to change anything after the release. 

## Java 8 strategies

We might need to decide how to handle java 8 on DevContainers.  I'm happy to follow you guys strategies. 

・Java 8 is not supported for Java extension (REDHAT) anymore. We need to Java11+ for using Intellisense for example.
・If we want to enable Java8 with Java extension, we need to include Java 11 SDK on the Docker image and change the configuration. 
・Currently, `3.0-java8-core-tools` is already used by customers. Not break This.
・`3.0-java8-core-tools` image is used for devcontainer and CI.  

According to the condition, and our conversation, we have several strategies 

| Num | Title | Description | Pros | Cons | Comment |
| --- | ---- | --------------| -------- | ---------| -------|
| 1 | Update Dockerfile on this repo for Java 8 | Keep the `3.0-java8-core-tools` image and add Java 11 SDK in this repo's Dockerfile or vise-versa with workaround Anthony mentioned | Easy to fix | Need Build time, increase the size of image | [Sample PR](https://github.com/microsoft/vscode-dev-containers/pull/468) |
| 2 | Create new image that has both Java 11 and Java 8 | On the Azure Functions Docker repo, we create an image that has both Java 8 and Java 11. This repo refer it and add configuration on devcontainer.json | Clean design, Java 8 customer experience is great | Need to update CI pipeline with Dockerfile on Azure Functions Docker repo. CI user doesn't use it | N/A |
| 3 | Leave the Java 8 as is | Keep as is to encourage users to use Java 11 | No work required or just update Readme. Encourage people to move Java 11 | Majority of the Java user on Azure Functions are using Java 8. They might confuse and introduce bad experience.  | N/A |
| 4 | Remove Java 8 | Remove Java 8 from this repo. Keep `3.0-java8-core-tools` for current users. | Remove the workload. Encourage people to use Java 11 | Majority of the Java user on Azure Functions are using Java 8. Azure Functions officially support Java 8 |  N/A |

I already create a PR for 1. However, it also has cons. Which would you guys prefer or any other good ideas?  I prefer 2. Could you share you guys opinion, please?

**Comment by Chuxel** [comment]
//cc: @chrmarti FYI, we'll want to include this in the release just as a heads up.

@Chuxel , @anthonychu , @amamounelsayed - Number 2 actually seems like a reasonable way to go.  For other definitions we're starting to use an arg called ${VARIANT} to allow developers to pick a version rather that having more than one where the Dockerfile in the definition is otherwise the same.  Given the situation, having JDK 8 and 11 in the same one would have the same net effect.

**Comment by Chuxel** [comment]
@TsuyoshiUshio Whoops - Looks like the PR merge closed this. LMK if you want to keep it open while you work on number 2 above.
