### ISSUE TITLE
.NETCore image with Linux SQL Server

### ISSUE THREAD

**Issue by warrenbuckley** [microsoft/vscode-dev-containers#489]
Is it possible to have a pre configured example/image for .NETCore & a Linux SQL Server. So I can add the .devcontainers folder into my project nice & quickly please

**Comment by Chuxel** [comment]
Thanks for the request! Certainly possible to do, and happy to take a look at a PR that does it if you want to contribute one!

**Comment by warrenbuckley** [comment]
I wish I knew docker more to understand what I need to do to contribute one.

**Comment by warrenbuckley** [comment]
As VS CodeSpaces with a Windows host seems to have SQL Server

https://docs.microsoft.com/en-us/visualstudio/codespaces/reference/configuring-windows#microsoft-sql-server

Is it possible for GitHub CodeSpaces to support Windows hosts too that would allow the same scenario @Chuxel

**Comment by warrenbuckley** [comment]
I am closing this as I got the email from Microsoft/GitHub that VS CodeSpaces is being moved into GitHub only and that the Windows environment will be coming too at some point.

**Comment by dzsquared** [comment]
Hi @warrenbuckley - I created a devcontainer defintion that covers .NET Core and SQL Server in the linked PR #632.  If you you have a chance to try it out I would love your feedback.  thanks!
