### ISSUE TITLE
Python Interactive does not work in Python 3 Anaconda dev container

### ISSUE THREAD

**Issue by isvoboda** [microsoft/vscode-dev-containers#50]
- VSCode Version: 1.35.0-insider (snap)
- Local OS Version: Arch Linux
- Name of Dev Container Definition with Issue: Python 3 Anaconda (https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3-anaconda)

Steps to Reproduce:

1. Follow the Readme.md
2. Run the Interactive Python - get stuck starting jupyter-server

I am not sure if the problem is related to vscode-python only or to vscode-dev-containers as well (it works without remote).

I report the issue in vscode-python as well [#5676 Python Interactive does not work in Remote - Containers](https://github.com/microsoft/vscode-python/issues/5676#issue-445665137)

**Comment by Chuxel** [comment]
@isvoboda As discussed on that thread and the related https://github.com/microsoft/vscode-remote-release/issues/376, this may be some sort of regression and does not appear to be related to the dev container itself on the surface.  Let's continue the conversation in these other two issues.
