### ISSUE TITLE
For Node/Mongo docker compose container, please add line to open port

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-dev-containers#504]
Since this is a web/db compose solution, opening a port to access the web makes sense but I don't see it in the files created in the .devcontainer folder. 

I would like to see the port so I can change it in case that is easier than changing the source code to use your port. 

@chrmarti fyi

**Comment by Chuxel** [comment]
Good catch.  `forwardPorts` should be commented out in devcontianer.json like the main node definition.

**Comment by Chuxel** [comment]
Resolved - should go in the next release.
