### ISSUE TITLE
Default shell is now /bin/sh for all dev container definitions

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#51]
A recent update had VS Code respect the default shell that the OS sets.  An unfortunate side effect of this is that VS Code now uses `/bin/sh` as the shell since the SHELL env var is not set.  Containers like `kubernetes-helm` rely on `.bashrc` which will fail with normal `sh`.

To avoid this problem, I propose we update all dockerfiles in dev container definitions to include:

`ENV SHELL /bin/bash`

@chrmarti Does this make sense to you as well?

The alternative would be to inject a linux terminal setting into the remote settings.json file.

We can also tweak the dev container definitions to work with `sh`, but I think that people will typically want `bash`, so it strikes me these dev container definitions should follow suit.

**Comment by chrmarti** [comment]
Unfortunate, but makes sense. We want the container to be prepared for development (not just deployment, like they usually are).

**Comment by dcrouch79** [comment]
Now the default shell has been set to `/bin/bash` the following errors/warnings appear in the output log during startup:

```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
mesg: ttyname failed: Inappropriate ioctl for device
```

Not sure how significant this is though, as everything still seems to work ok.
