### ISSUE TITLE
Use latest Git in common-debian

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-dev-containers#511]
Since this is meant for developers, it's important to use the latest version of Git always. The `common-debian.sh` script currently installs the latest Git from the distribution's repository, which almost always is not the latest version of it.

According to [official Git docs](https://git-scm.com/download/linux), for installing Git on Ubuntu you can use the official PPA:

```bash
add-apt-repository --update ppa:git-core/ppa
apt-get install git
```

**Comment by Tohaker** [comment]
I'm facing this problem with my `typescript-node` devcontainer.
Could a solution be to use the `<version>-buster` variants of the `node` image? The version of git in the buster repo is far more recent than that in stretch, which is the default for node containers.

I'd be willing to raise a PR to update the variants in `definition-manifest.json` to be
```
"variants": ["14", "12", "10", "14-buster", "12-buster", "10-buster"]
```
But I'm not sure what the policy is on having multiple variants of the same version.

**Comment by Chuxel** [comment]
@Tohaker The Node.js folks have taken a more conservative stance that other images on when they move to buster, but it might just make sense to pin to buster at this point.  I'll PR that.

@felipecrs The PPA approach is for Ubuntu. We do have a build script that can be referenced to get latest, but I don't think we want to add this to each and every image as it materially adds to the overall size.

**Comment by felipecrs** [comment]
@Chuxel at least for Ubuntu so? I don't see how it would take more space since it replaces the Git installed by the distro sources.

**Comment by Chuxel** [comment]
@felipecrs Layers do not collapse, so the old version will still be in the set of layers and thus the total image size. If we didn't install git that would be one thing, but something like buildpack-deps has it already. Very few images here actually use Ubuntu - and really all the base docker ones are Debian as well.

I think it's reasonable to keep this as an optional update for those looking for rather than forcing everyone to take it. The version in the distro is going to have the most mileage on it.  What features are you specifically looking for that would be later than what is in Buster?

**Comment by felipecrs** [comment]
@Chuxel I see, now I understand since some base images already come preinstalled with Git (but I still wonder how much developers care about image sizes and such things, since this is aimed for developers and not production).

For example, git from ubuntu 18.04 is v2.17.1, which does not have the `git restore` (quite useful) command introduced in v2.23 (I think). But we're already in Git 2.27 and many changes were introduced, and as I said, as developers it's important to ensure the latest version of Git.

We can put this in `debian-common.sh` (the PPA), which would only run if the OS is Ubuntu and the user enabled the `UPGRADE_PACKAGES`, how about that?

**Comment by Chuxel** [comment]
This one seems to be recommended by Git team directly - though it's still not officially supported by Ubuntu. I could see it getting added as an "opt-in" flag for people that want features over stability with a fall back to git from source in that case.

**Comment by felipecrs** [comment]
I don't think this is relevant. Just because Canonical choose not to include a given version of Git in their repositories (probably because they do not have time for testing each new version) do not mean that it's not official.

**Comment by Chuxel** [comment]
> Do you think that the latest stable version of Git is not stable enough?

This is the reason that distributions are not evergreen and instead use versions - new features drive bugs. The distro is saying "we know this works with everything else you'll get from apt."  Opting into it sounds good to me.  In places where we pre-build, we could investigate the impact of doing it by default.

**Comment by felipecrs** [comment]
Despite that, developers (I'm speaking for myself, but I believe others do as well) prefer to use the latest version of Git in their personal and development platforms, just because to have a new feature is more important than this stability that I'm not aware of (I'm saying this because I don't know a use case where the git from the distro repo works more stable than the official latest git).

**Comment by Chuxel** [comment]
Happy to leave the issue open for upvoting about changing the default behavior and getting the option there in the near term.

@Tohaker Forgot to mention that the latest 10/12/14 images are buster.  There's also `-stretch` varieties where needed.

**Comment by Chuxel** [comment]
I think we can modify the git-from-src-debian.sh script to use a PPA if latest is selected and we're on Ubuntu, otherwise it will build from scratch.

**Comment by Chuxel** [comment]
This update was included in the ARM64 PR that was merged a bit ago!
