### ISSUE TITLE
How to use GitHub CLI?

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-dev-containers#513]
I see that a [new script was added](https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/github-debian.sh) to install GitHub CLI in the container.

However, after installing: 

1. I'm not able to log in by normal means because `xdg-open` is not available under the container. 
   Solutions (sorted by the best to the worst in my opinion): 
     - https://github.com/cli/cli/issues/1074 and https://github.com/microsoft/vscode-pull-request-github/issues/1923
     - automatically copy `~/.config/gh/hosts.yml` from the host to the container
     - https://github.com/microsoft/vscode-remote-release/issues/3251
     - https://github.com/cli/cli/issues/297

2. Features that require `xdg-open` does not work, such as `gh repo view --web` or `gh pr view --web`.
    Solution: https://github.com/microsoft/vscode-remote-release/issues/3251

**Comment by Chuxel** [comment]
This will be resolved in the next version of the CLI as described here: https://github.com/cli/cli/pull/1445  

We're queuing this up for when the fix comes out soon.

**Comment by Chuxel** [comment]
Forgot to report back here - an option to sign in without xdg-open landed in version 1.0.0 of the CLI, so this should be resolved.
