### ISSUE TITLE
[Tracking] Image support, deprecation / EOL dates

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#532]
The following are release dates and EOL / end of support dates for languages / OS's with pre-built images. After runtime or OS support for a given image has ended, we will stop building images for that version. We also typically only release images for "LTS" or "stable" releases of runtimes/OS's. Others can be built from `.devcontaiiner/base.Dockerfile` available in the definition source code in this repository. 

Releases typically happen monthly on the same release cadence as VS Code and include the most recent changes from the upstream base image or runtime version including security updates (e.g. the latest OS updates and the latest point release of a runtime or platform). You can see the current schedule for the VS Code release in a pinned "Iteration Plan" issue at the [VS Code repository](https://github.com/microsoft/vscode/issues). We may update earlier if a critical need or bug is discovered. 

Dev container images are also versioned independent of the runtime. To avoid unexpected breaks, we recommend pinning to the latest major version of an image release to pick up security and feature updates without breaking changes. This image version number is a prefix to the variant or runtime version. e.g. `mcr.microsoft.com/vscode/devcontainers/typescript-node:0-14` where `0` is the major version number of the dev container image. This happens automatically when using the **Add Development Container Configuration Files...** command in the Remote - Containers extension or GitHub Codespaces. 

To make pinning to a version easier if you wish to do so, recent versions of images include a `devcontainer-info` command that will output information about the image in use including version information and a link to a file with additional information on contents.

> Note that in some cases, we may have to end support earlier than the stated date  below if there are fundamental OS requirements that force it or if the primary extension(s) supporting it have dropped support. In these cases, there would no longer be a functioning VS Code story. Our expectation is that this should be rare given typical GA to EOL timelines and is something we strive to avoid.

| Language  / OS | Version | Release | EOL / End of Support | Image |
|-----------|---------|---------|-----|-----|
| <strike>[Alpine](https://alpinelinux.org/releases/e)</strike> | <strike>3.10</strike> | <strike>June 19th, 2019</strike> | <strike>May 1st, 2021</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/base:alpine-3.10`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/alpine)</strike> |
| <strike>[Alpine](https://alpinelinux.org/releases/)</strike> | <strike>3.11</strike> | <strike>Dec 19th, 2019</strike> | <strike>Nov 1st, 2021</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/base:alpine-3.11`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/alpine)</strike> |
| <strike>[Alpine](https://alpinelinux.org/releases/)</strike> | <strike>3.12</strike> | <strike>May 29th, 2020</strike> | <strike>May 1st, 2022</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/base:alpine-3.12`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/alpine)</strike> |
| [Alpine](https://alpinelinux.org/releases/) | 3.13 | Jan 14th, 2021 | Nov 1st, 2022  | [`mcr.microsoft.com/vscode/devcontainers/base:alpine-3.13`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/alpine) |
| [Alpine](https://alpinelinux.org/releases/) | 3.14 | June 15th, 2021 | May 1st, 2023  |  [`mcr.microsoft.com/vscode/devcontainers/base:alpine-3.14`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/alpine) |
| [Alpine](https://alpinelinux.org/releases/) | 3.15 | Nov 24th, 2021 | Nov 1st, 2023  | [`mcr.microsoft.com/vscode/devcontainers/base:alpine-3.15`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/alpine) |
| [Alpine](https://alpinelinux.org/releases/) | 3.16 | May 23rd, 2022 | May 23rd, 2024 | [`mcr.microsoft.com/vscode/devcontainers/base:alpine-3.16`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/alpine) |
| [Alpine](https://alpinelinux.org/releases/) | 3.17 | Dec 2022 (Est) | |  |
| <strike>[Debian (and C++)](https://endoflife.software/operating-systems/linux/debian)</strike> | <strike>9 / Stretch</strike> | <strike>June 17, 2017</strike> | <strike>Jan, 2022 (EOL Jan 2020)</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/base:stretch`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/debian)<br />[`mcr.microsoft.com/vscode/devcontainers/cpp:stretch`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/cpp)<br /> [`mcr.microsoft.com/vscode/devcontainers/universal:stretch`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/codespaces-linux-stretch)</strike> |
| [Debian (and C++)](https://endoflife.software/operating-systems/linux/debian) | 10 / Buster | July 6, 2019 | Jan, 2024 (Est - EOL Jan 2022) | [`mcr.microsoft.com/vscode/devcontainers/base:buster`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/debian)<br />[`mcr.microsoft.com/vscode/devcontainers/cpp:buster`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/cpp) |
| [Debian (and C++)](https://endoflife.software/operating-systems/linux/debian) | 11 / Bullseye | August 14, 2021 | Jan, 2026 (Est - EOL Jan 2024) | [`mcr.microsoft.com/vscode/devcontainers/base:bullseye`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/debian)<br />[`mcr.microsoft.com/vscode/devcontainers/cpp:bullseye`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/cpp)  |
| [Debian (and C++)](https://endoflife.software/operating-systems/linux/debian) | 12 / Bookworm | July/August 2023 (Est) | | |
| <strike>[.NET (Core)](https://endoflife.software/programming-languages/server-side-scripting/dotnet-core)</strike> | <strike>2.1</strike> | <strike>May 30th, 2018</strike> | <strike>Aug 21st, 2021</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/dotnetcore:2.1`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnet)<br />[`mcr.microsoft.com/vscode/devcontainers/dotnet:2.1`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnet)</strike> |
| [.NET (Core)](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) | 3.1 | Dec 3rd, 2019 | Dec 3rd, 2022  | [`mcr.microsoft.com/vscode/devcontainers/dotnetcore:3.1`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnet)<br /> [`mcr.microsoft.com/vscode/devcontainers/dotnet:3.1`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnet) |
| <strike>[.NET](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)</strike> | <strike>5.0</strike> | <strike>Nov, 2020</strike> |  <strike>May 10, 2022</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/dotnet:5.0`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnet)</strike> |
| [.NET](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) | 6.0 | Nov, 2021 (Est) | Feb 2024 (Est) | [`mcr.microsoft.com/vscode/devcontainers/dotnet:6.0`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnet) |
| [.NET](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) | 7.0 | Nov, 2022 (Est) | | |
| <strike>[Go](https://golang.org/doc/devel/release.html)</strike> | <strike>1.14</strike> | <strike>Feb 25th, 2020</strike> | <strike>Feb 2021</strike> |  <strike>[`mcr.microsoft.com/vscode/devcontainers/go:1.14`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/go)</strike> |
| <strike>[Go](https://golang.org/doc/devel/release.html)</strike> | <strike>1.15</strike> | <strike>Nov 8th, 2020</strike> | <strike>Aug 2021</strike> |  <strike>[`mcr.microsoft.com/vscode/devcontainers/go:1.15`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/go)</strike> |
| <strike>[Go](https://golang.org/doc/devel/release.html)</strike> | <strike>1.16</strike> | <strike>Feb 2021</strike> | <strike> March 2022 </strike>  | <strike>[`mcr.microsoft.com/vscode/devcontainers/go:1.16`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/go)</strike>  |
| <strike>[Go](https://golang.org/doc/devel/release.html)</strike> | <strike>1.17</strike> | <strike>Aug 2021</strike> | <strike>Aug 2022</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/go:1.17`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/go)</strike> |
| [Go](https://golang.org/doc/devel/release.html) | 1.18 | March 2022 | March 2023 | [`mcr.microsoft.com/vscode/devcontainers/go:1.18`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/go)<br /> [`mcr.microsoft.com/vscode/devcontainers/go:1`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/go) |
| [Go](https://golang.org/doc/devel/release.html) | 1.19 | August 2022 | August 2023 | [`mcr.microsoft.com/vscode/devcontainers/go:1.19`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/go)<br /> [`mcr.microsoft.com/vscode/devcontainers/go:1`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/go) |
| [Go](https://golang.org/doc/devel/release.html) | 1.20 | March 2023 (Est) | | |
| [Java](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) | 8 | March 2014 | December 2030 | [`mcr.microsoft.com/vscode/devcontainers/java:8`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/java-8) |
| [Java](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) | 11 | Sept 2018 | Sept 2026 | [`mcr.microsoft.com/vscode/devcontainers/java:11`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/java) |
| <strike>[Java](https://www.oracle.com/java/technologies/java-se-support-roadmap.html)</strike> | <strike>14</strike> | <strike>March 2020</strike> | <strike>Sept 2020</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/java:14`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/java)</strike> |
| <strike>[Java](https://www.oracle.com/java/technologies/java-se-support-roadmap.html)</strike> | <strike>15</strike> | <strike>Sept 2020 | <strike>March 2021  | <strike>[`mcr.microsoft.com/vscode/devcontainers/java:15`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/java)</strike> |
| <strike>[Java](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) </strike>| <strike>16</strike> | <strike>March 2021</strike> | <strike>Sept 2021</strike>  | <strike>[`mcr.microsoft.com/vscode/devcontainers/java:16`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/java)</strike> |
| [Java](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) | 17 | Sept 2021 | Sept 2029  |  [`mcr.microsoft.com/vscode/devcontainers/java:17`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/java) |
| <strike>[Node.js](https://endoflife.software/programming-languages/server-side-scripting/nodejs)</strike> | <strike>10</strike> | <strike>April 24, 2018</strike> | <strike>April, 2021</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/javascript-node:10`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/javascript-node)<br /> [`mcr.microsoft.com/vscode/devcontainers/typescript-node:10`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/typescript-node)</strike> |
| <strike>[Node.js](https://endoflife.software/programming-languages/server-side-scripting/nodejs)</strike> | <strike>12</strike> | <strike>April 23, 2019</strike> | <strike>April, 2022</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/javascript-node:12`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/typescript-node)<br /> [`mcr.microsoft.com/vscode/devcontainers/typescript-node:12`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/typescript-node)</strike> |
| [Node.js](https://endoflife.software/programming-languages/server-side-scripting/nodejs) | 14 | April, 2020 |  April, 2023 | [`mcr.microsoft.com/vscode/devcontainers/javascript-node:14`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/javascript-node)<br /> [`mcr.microsoft.com/vscode/devcontainers/typescript-node:14`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/typescript-node) |
| [Node.js](https://endoflife.software/programming-languages/server-side-scripting/nodejs) | 16 | April 20, 2021 | April, 2024  | [`mcr.microsoft.com/vscode/devcontainers/javascript-node:16`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/javascript-node)<br /> [`mcr.microsoft.com/vscode/devcontainers/typescript-node:16`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/typescript-node)  |
| [Node.js](https://endoflife.software/programming-languages/server-side-scripting/nodejs) | 18 | April, 2022 |  April, 2025 | [`mcr.microsoft.com/vscode/devcontainers/javascript-node:18`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/javascript-node)<br /> [`mcr.microsoft.com/vscode/devcontainers/typescript-node:18`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/typescript-node)  |
| [Node.js](https://endoflife.software/programming-languages/server-side-scripting/nodejs) | 20 | April, 2023 (Est) |  |  |
| <strike>[PHP](https://endoflife.software/programming-languages/server-side-scripting/php)</strike> | <strike>7.3</strike> | <strike>Dec 6th, 2018</strike> | <strike>Dec 6th, 2021 (EOL Dec 6th, 2020)</strike>  | <strike>[`mcr.microsoft.com/vscode/devcontainers/php:7.3`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/php)</strike> |
| [PHP](https://endoflife.software/programming-languages/server-side-scripting/php) | 7.4 | Nov 28th, 2019 | Nov 28th, 2022 (EOL Nov/Dec 2021) | [`mcr.microsoft.com/vscode/devcontainers/php:7.4`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/php) |
| [PHP](https://endoflife.software/programming-languages/server-side-scripting/php) | 8.0 |  Nov 26th, 2020 | Oct 26th, 2023 (EOL Nov 26th, 2022)  |  [`mcr.microsoft.com/vscode/devcontainers/php:8.0`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/php) | 
| [PHP](https://endoflife.software/programming-languages/server-side-scripting/php) | 8.1 |  Nov 25th, 2021 | Oct 25th, 2024 (EOL Nov 26th, 2023) | [`mcr.microsoft.com/vscode/devcontainers/php:8.1`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/php) | 
| [PHP](https://endoflife.software/programming-languages/server-side-scripting/php) | 8.2 |  Nov 2022 (Est) | | | 
| <strike>[Python](https://devguide.python.org/#status-of-python-branches)</strike> | <strike>3.6</strike> | <strike>Dec 23rd, 2016</strike> | <strike>Dec 23rd, 2021</strike> |  <strike>[`mcr.microsoft.com/vscode/devcontainers/python:3.6`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3)</strike> |
| [Python](https://devguide.python.org/#status-of-python-branches) | 3.7 | June 27th, 2018 | June 27th, 2023 | [`mcr.microsoft.com/vscode/devcontainers/python:3.7`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3) |
| [Python](https://devguide.python.org/#status-of-python-branches) | 3.8 | Oct 10th, 2019 | Oct 10th, 2024 | [`mcr.microsoft.com/vscode/devcontainers/python:3.8`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3) |
| [Python](https://devguide.python.org/#status-of-python-branches) | 3.9 | Oct 5th, 2020 | Oct 5th, 2025 (Est) | [`mcr.microsoft.com/vscode/devcontainers/python:3.9`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3) |
| [Python](https://devguide.python.org/#status-of-python-branches) | 3.10 | Oct 5th, 2021 | Oct 5th, 2026 (Est) | [`mcr.microsoft.com/vscode/devcontainers/python:3.10`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3) |
| [Python](https://devguide.python.org/#status-of-python-branches) | 3.11 | Oct, 2022 (Est) | |  |
| <strike>[Ruby](https://www.ruby-lang.org/en/downloads/branches/)</strike> | <strike>2.5</strike> | <strike>Dec 25th, 2017</strike> | <strike>March 2021</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/ruby:2.5`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/ruby)</strike> |
| <strike>[Ruby](https://www.ruby-lang.org/en/downloads/branches/)</strike> | <strike>2.6</strike> | <strike>Dec 25th, 2018</strike> | <strike>March 2022</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/ruby:2.6`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/ruby)</strike>  |
| [Ruby](https://www.ruby-lang.org/en/downloads/branches/) | 2.7 | Dec 25th, 2019 | March 2023 (Est) | [`mcr.microsoft.com/vscode/devcontainers/ruby:2.7`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/ruby)  |
| [Ruby](https://www.ruby-lang.org/en/downloads/branches/) | 3.0 | Dec 25th, 2020 | March 2024 (Est) | [`mcr.microsoft.com/vscode/devcontainers/ruby:3.0`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/ruby)  |  |
| [Ruby](https://www.ruby-lang.org/en/downloads/branches/) | 3.1 | Dec 25th, 2021 | March 2025 (Est) | [`mcr.microsoft.com/vscode/devcontainers/ruby:3.1`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/ruby)  |
| [Ruby](https://www.ruby-lang.org/en/downloads/branches/) | 3.2 | Dec 25th, 2022 | | |
| [Ubuntu](https://wiki.ubuntu.com/Releases) (and C++)  | 18.04 LTS / Bionic | April 26, 2018 | April, 2028 (EOL April, 2023) | [`mcr.microsoft.com/vscode/devcontainers/base:bionic`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/ubuntu)<br />[`mcr.microsoft.com/vscode/devcontainers/cpp:bionic`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/cpp) |
| [Ubuntu](https://wiki.ubuntu.com/Releases) (and C++)  | 20.04 LTS / Focal | April, 2020 | April, 2030 (EOL April, 2025) | [`mcr.microsoft.com/vscode/devcontainers/base:focal`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/ubuntu)<br />[`mcr.microsoft.com/vscode/devcontainers/cpp:focal`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/cpp)<br /> [`mcr.microsoft.com/vscode/devcontainers/universal:focal`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/codespaces-linux) |
| <strike>[Ubuntu](https://wiki.ubuntu.com/Releases) (and C++)</strike>  | <strike>21.04 / Hirsute</strike> | <strike>April, 2021</strike> | <strike>Jan, 2022</strike> | <strike>[`mcr.microsoft.com/vscode/devcontainers/base:hirsute`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/debian)<br />[`mcr.microsoft.com/vscode/devcontainers/cpp:hirsute`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/cpp)</strike> |
| [Ubuntu](https://wiki.ubuntu.com/Releases) (and C++)  | 22.04 LTS | April, 2022 | April, 2032 (EOL April, 2027) | [`mcr.microsoft.com/vscode/devcontainers/base:jammy`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/ubuntu)<br />[`mcr.microsoft.com/vscode/devcontainers/cpp:jammy`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/cpp) |  
| [Ubuntu](https://wiki.ubuntu.com/Releases) (and C++)  | 24.04 LTS | April, 2024 (Est) |  |  |  

Rust ([`mcr.microsoft.com/vscode/devcontainers/rust`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/rust)), Anaconda ([`mcr.microsoft.com/vscode/devcontainers/anaconda`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3-anaconda)), and Miniconda ([`mcr.microsoft.com/vscode/devcontainers/miniconda`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3-miniconda)), and Jekyll ([`mcr.microsoft.com/vscode/devcontainers/jekyll`](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/jekyll)) have an ongoing release schedule, so we are continually releasing the latest stable version. The Jekyll image also includes the `github-pages` gem for Jekyll 3.x.

**Comment by samruddhikhandale** [comment]
We're starting to migrate contents of this repo to the [devcontainers org](https://github.com/devcontainers), as part of the work on the [open dev container specification](https://containers.dev).

We'll now be publishing images from [devcontainers/images](https://github.com/devcontainers/images). Closing this in favor of https://github.com/devcontainers/images/issues/90.

For more details, you can review the [announcement issue](https://github.com/microsoft/vscode-dev-containers/issues/1589).
