### ISSUE TITLE
Use Ubuntu rather than Debian as the default and recommended image

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-dev-containers#535]
This is a follow-up of https://github.com/microsoft/vscode-dev-containers/issues/533, since the discussion there moved from Python to an OS choice.

This implies not using the official language images as the base image (such as `library/node`), since most of them do not get precompiled with Ubuntu (and why would they, since containers, in general, are not faced for human interaction = development).

If you are interested in this topic, please make sure you read https://github.com/microsoft/vscode-dev-containers/issues/533 at least until where this new Issue was created.

**Comment by felipecrs** [comment]
Replying to https://github.com/microsoft/vscode-dev-containers/issues/533#issuecomment-685294559:

> Node includes yarn for similar reasons. Most of these originate from the buildpack-deps base image which itself is not intended as a deployment image.

It's true that those images are not intended for deployment, but I say that those images are also not intended for development. They're intended for build cycles, continuous integration, wherever a human is not needed.

> There's also a huge value if you are doing container deployment in using the same base for development that you do for deployment.

I can be very wrong, but I can't think of a single reason why doing this would be beneficial. In the end, the developers would still have to develop the `Dockerfile` for the deployment version and test it. Working inside of "the same" image does not exempt any work. And it's not possible at all to have the same image, because the development image would need to have `docker` installed and the deployment image not. Again, this for me makes no sense.

> The idea is to start from a known, solid base, then add rather than reinvent from the ground up. No image can fit all needs, which is why we're also trying to get things in a reusable form for custom solutions.

Interesting. In my opinion, a known and solid base would be `ubuntu`. 😀

I imagine a day where we can have any kind of combination between language stacks on images, and have them prebuilt automatically and programmatically, just by setting what scripts from the library to run.

Something like:

```
mcr.microsoft.com/vscode/devcontainers/base:ubuntu
mcr.microsoft.com/vscode/devcontainers/base:ubuntu-node
mcr.microsoft.com/vscode/devcontainers/base:ubuntu-python
mcr.microsoft.com/vscode/devcontainers/base:ubuntu-node-python
mcr.microsoft.com/vscode/devcontainers/base:ubuntu-docker-java-node
```

Always relying on a solid base image for general purpose, which can be either `ubuntu` or `debian`, but not the language's official images.

> Of curiosity, if you assume for a moment that we would not want to use PPAs that are not official - what advantage does Ubuntu provide over Debian for you?

Well, this is a hard discussion. My main argument is: why not Ubuntu? 

Ubuntu is far more popular than Debian, **even for development**. Developers/humans, in general, prefer to work with an OS they know already.

The fundamental difference between Ubuntu and Debian is that Ubuntu focuses on being practical when Debian focuses on being totally free and open source. One of the things that makes this very clear is the PPA.

**Comment by Chuxel** [comment]
There's always a Debian vs Ubuntu vs CentOS vs Fedora argument which is why I'd like to get to some specifics on what Ubuntu provides that Debian does not. We've opted to follow the Debian/Ubuntu path for a wide variety of reasons and the topic here does not seem to be about that (though it also comes up). In terms of what comparable recent releases of Ubnutu and Debian provide, Ubuntu adds:

1.  PPAs
2. ????

Really, the question is not about Ubuntu vs Debian, but instead whether there is sufficient benefits to moving away from heavily used Docker base images intended for build and run. The downside of moving away from Docker base images each image is  no longer in the same OSS ecosystem as millions of other Docker users as things around the image change. "Going it alone" always comes with risks.  We'll be relying on the comparatively modest number of contributors here instead.  (When an Ubuntu variation exists, happy to include it.) 

In terms of the build - a concrete example of a benefit for Docker is using the well known builder pattern:

```Dockerfile
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:12 AS development

# Build steps go here
FROM development as builder
WORKDIR /app
COPY src/ *.json ./
RUN yarn install \
    && yarn compile \
    #  Just install prod dependencies
    && yarn install --prod

# Actual production environment setup goes here
FROM node:12-slim AS production
WORKDIR /app
COPY --from=builder /app/out/ ./out/
COPY --from=builder /app/node_modules/ ./node_modules/
COPY --from=builder /app/package.json .
EXPOSE 3000
ENTRYPOINT [ "/bin/bash", "-c" ]
CMD [ "npm start" ]
```

If your dev stage matches your prod stage's base, you will have fewer unexpected issues.

**Comment by felipecrs** [comment]
I doubt a Node developer would prefer to use the `node` base image (and thus having to rebuild the entire container if he just quick need to switch the version for testing) rather than another one with `nvm` installed.

**Comment by felipecrs** [comment]
> In terms of what comparable recent releases of Ubnutu and Debian provide, Ubuntu adds:
> 
> 1. PPAs
> 2. ????

More packages available to install is a quite reasonable advantage, don't you think? Not only PPA, but Ubuntu's repositories often offers more packages as well.

Compared to Debian, it also offers more recent versions of the packages.

Another compelling reason is: VSCode Remote Containers and Codespaces are pushing hard the concept of `dotfiles` for personalization. Since Ubuntu is the most popular OS, the chances are that the user's dotfiles were made for running in Ubuntu. Switching to Ubuntu would enable an easier transition for the `dotfiles`, or with fewer tweaks at least.

**Comment by Chuxel** [comment]
As an update here, we're talking with the Oryx team about getting an Ubuntu flavor of their image so we can base codespaces-linux (aka "kitchen sink") on it going forward.

I'll be adding the distro into the README on each definition so we are able to give people visibility to which ones are on Ubuntu, Debian, Alpine, or perhaps "other" at some point. C++ now has Ubuntu flavors as well. Other definitions will be tied to their base images for the reasons described above for the time being.

/cc: @bamurtaugh @burkeholland @2percentsilk

**Comment by felipecrs** [comment]
> Other definitions will be tied to their base images for the reasons described above for the time being.

Makes sense and I also agree with it, contradicting my previous opinion.

I just thought of another reason why Ubuntu can be a better choice: 

- For most of the applications, one of the main targets is Ubuntu Linux, mainly because of its popularity. I believe we can say that there are more chances to find packaged targeting Ubuntu (or at least with precompiled binaries distributed) rather than Debian.
- Also, Ubuntu can run any package made for Debian, but the vice-versa is not true. This means that indeed there are more packages available when using Ubuntu.

**Comment by felipecrs** [comment]
Yes!

**Comment by arash-bizcover** [comment]
Debian if fucking dead from a long time 
a simple example is sqlite latest version is not supported (crafted for debian repos)
Same with many many other apps
