### ISSUE TITLE
Add man-db to Debian common package list

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-dev-containers#539]
`man-db` isn't included in the Docker node images:

> https://github.com/nodejs/docker-node/issues/209#issuecomment-234426404
>
> You'll probably find that `man` is not installed in a majority of the official Docker images, particularly ones that build off the official debian image. Presumably the rationale is that Docker containers are a form of app encapsulation and not something you typically log into and use interactively.

Since a dev container is used interactively, it would be nice if `man-db` was installed out of the box. `git --help` doesn't work without it, among other things.

**Comment by Chuxel** [comment]
Thanks for the feedback! Yes, historically this has been excluded to keep image sizes down. However, I do find myself wishing it was there as well and it looks like it's about a 6mb, so this is a reasonable request. We can do that I think.

**Comment by Chuxel** [comment]
Updated!

**Comment by aaronadamsCA** [comment]
Thanks! (Thanks also for the new `javascript-node:12-buster` - between that and this, I no longer need my own Dockerfile at all. Loving the continued improvements to the developer experience.)
