### ISSUE TITLE
Support updating npm

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-dev-containers#541]
I'm using `javascript-node:12-buster` and updating NPM doesn't work as I'd expect.

```text
$ npm -v
6.14.6
$ which npm
/usr/local/bin/npm
$ npm i -g npm
/usr/local/share/npm-global/bin/npm -> /usr/local/share/npm-global/lib/node_modules/npm/bin/npm-cli.js
/usr/local/share/npm-global/bin/npx -> /usr/local/share/npm-global/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.14.8
added 434 packages from 885 contributors in 10.338s
$ npm -v
6.14.6
$ /usr/local/share/npm-global/bin/npm -v
6.14.8
```

**Comment by Chuxel** [comment]
Hmm sounds like the PATH has npm-global too late. Will take a look.

**Comment by Chuxel** [comment]
Should be resolved in the next release!

**Comment by aaronadamsCA** [comment]
FYI only, the new solution installs a new `npm` but leaves the old one in place too. Since the new one comes earlier in `PATH`, new terminal sessions do pick it up, but existing terminal sessions continue to reference the old one:

```sh
$ npm -v
6.14.6
$ which npm
/usr/local/bin/npm
$ npm i -g npm
/usr/local/share/npm-global/bin/npm -> /usr/local/share/npm-global/lib/node_modules/npm/bin/npm-cli.js
/usr/local/share/npm-global/bin/npx -> /usr/local/share/npm-global/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.14.8
added 434 packages from 885 contributors in 10.338s
$ npm -v
6.14.6
$ /usr/local/share/npm-global/bin/npm -v
6.14.8
$ which npm
/usr/local/share/npm-global/bin/npm
```

This could confuse users, obviously, since `which` is "lying".

Works fine on terminal restart, so I'm good with this, just wanted to note the odd behaviour. Thanks!
