### ISSUE TITLE
Dockerfile preamble breaks [Choice] conventional syntax

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-dev-containers#542]
E.g., for the Go definition the preamble is inserted as the second line which breaks the convention that the `[Choice]` line needs to immediately be followed by the `ARG` line:
```Dockerfile
# [Choice] Go version: 1, 1.15, 1.14
# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.140.0/containers/go/.devcontainer/base.Dockerfile
ARG VARIANT="1"
FROM mcr.microsoft.com/vscode/devcontainers/go:0-${VARIANT}
```

**Comment by chrmarti** [comment]
Just saw that some `base.Dockerfile`s also have the `[Choice`] and `[Option]` annotations. Do you expect these to eventually run through the UI pickers too? (My assumption so for was that only the `Dockerfile`s would get there.)

**Comment by Chuxel** [comment]
I’d have to figure out how to determine if there was a choice with a regex since all of that is automated. Will have to see tomorrow.
