### ISSUE TITLE
Debian 11 (Bullseye)

### ISSUE THREAD

**Issue by Luit** [microsoft/vscode-dev-containers#544]
Currently the variants available for the Debian devcontainers are Stretch and Buster. Since I'm normally using Bullseye some tools I'm used to are more up-to-date locally than in a Buster devcontainer. (most notably `git` and `less`)

I've already tried one of my devcontainers in a custom image derived from the official ones. It seems all that needs to be changed is the set of allowed VARIANT values, as `buildpack-deps:bullseye-curl` is readily available.

**Comment by Chuxel** [comment]
Thanks for raising the issue - Looking at the release dates for Bullseye, it looks like the first freeze isn't until Jan 2021, with a release I'm guessing in the June/July timeframe given history.  We've seen pretty good compatibility across releases (at one point even Debian 8 was working too), but without a freeze, the distro could be flakey. So we tend not to build these until they're at least nearing a stable release.

That said, the full `base.Dockerfile` used to build the image is in this repo and can be referenced with bullseye as a `VARIANT`.  Would that work near term?

Specifically, grab the `.devcontainer` folder [from here]( https://github.com/microsoft/vscode-dev-containers/tree/master/containers/debian/.devcontainer) and then update `.devcontainer/devcontainer.json` as follows:

```json
"build": {
	"dockerfile": "base.Dockerfile",
	"args": { "VARIANT": "bullseye" }
}
```

The `base.Dockerfile` is what ends up in the image.

**Comment by Chuxel** [comment]
This was actually implemented just before GA of Bullseye.

**Comment by neogomez** [comment]
But my machine freezed in buster 🤣🤣🤣. I'm annoying...
