### ISSUE TITLE
Proposal: Default devcontainer.json to non-root "remoteUser"

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#552]
Currently the contents of this repository default to using "root". While this is fine given the scenario, it doesn't work well when using Linux as the host and some tools throw warnings and errors when running as root.

The upside of doing this is that, with sudo being present, using the containers will feel more like using a local Linux machine or mac. We can leave the actual container running as "root" (rather than setting `USER` in a Dockerfile or via `containerUser` in devcontainer.json) to avoid any bootstrapping challenges. It will allow people to `FROM` the image and install software in the way you would with other base images.

//cc: @chrmarti @lostintangent @matthewisabel @nikmd23 @bamurtaugh @burkeholland for input - to see if there's anything I'm missing.

**Comment by chrmarti** [comment]
Sounds good. I think for production the recommendation is to run as non-root too, so we don't really move away from what projects want to deploy later. (Having alignment between DevContainers and production containers helps avoid breakage due to differences between the two.)

**Comment by Chuxel** [comment]
@chrmarti Yeah exactly - it also feels a bit foreign if you're not already knee deep in working with containers. Even small things like your home folder being `/root` instead of `/home/<username>`.

We could flip the image itself to a non-root user instead (`USER ${USERNAME}`) but I worry a bit about people extending `FROM` the image hitting different behaviors than you'd see from other "base" images you'd grab off the net. This seemed like a good middle ground in that regard.  Different ENTRYPOINT scripts that require root access can also fire and run without sudo. I know we got this feedback more than we expected before the "remoteUser" property was added.

We can then just invert the comment - tell people to comment it out if they want to run as root.

**Comment by nguyenyou** [comment]
I'm waiting for this..

**Comment by Chuxel** [comment]
Yeah I've found a few community contributed definitions that seem to either be missing a non-root user (e.g. Puppet) or have an issue. I think the thing to do here will be to move to non-root users, and raise issues on those leaving them as-is for now rather than waiting.

**Comment by Chuxel** [comment]
Merged!
