### ISSUE TITLE
"code" alias for "code-insiders" not created with Fish and ZSH shells (Codespaces)

### ISSUE THREAD

**Issue by mchelen-gov** [microsoft/vscode-dev-containers#557]
- VSCode Version: Version: 1.49.0-insider
- Name of Dev Container Definition with Issue: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/codespaces-linux

Steps to Reproduce:

1. Start default Codespaces container
1. Open terminal
1. Works: `code foo.txt`
1. Switch shells: `zsh`
1. Doesn't work: `code foo.txt`
1. Works: `code-insiders foo.txt`

**Comment by Chuxel** [comment]
Thanks for raising it!  For zsh it's there, but appears to resolve differently than in bash, so it will need tweaks.  For fish it is not, so we can look into adding it.
