### ISSUE TITLE
Adopt the new 'settings' attribute in devcontainer.json

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-dev-containers#56]
pls see https://github.com/microsoft/vscode-remote-release/issues/409

We should simplify the existing container definitions to use this attribute (once the extension is published with the feature)

**Comment by Chuxel** [comment]
👍 On it - first pass of updates done.  Doing some testing, then will publish.  Also adding comments to all of the devcontainer.json files that don't need it to raise visibility to it.

**Comment by Chuxel** [comment]
Partially blocked by https://github.com/microsoft/vscode-remote-release/issues/435

**Comment by Chuxel** [comment]
Resolved with https://github.com/microsoft/vscode-dev-containers/pull/58
