### ISSUE TITLE
Swift 5.3 container definition not available

### ISSUE THREAD

**Issue by prabh-62** [microsoft/vscode-dev-containers#562]
## System Info
- VSCode Version: `1.49.0`
- Local OS Version: `Microsoft Windows 10 Pro 2004 (10.0.19041 N/A Build 19041)`
- Name of Dev Container Definition with Issue: `Swift`

## Steps to Reproduce:
1. In VS Code, try to open any folder in container 
2. Choose `Swift` and then try to select `5.3` version.
![swift_5 3_vscode](https://user-images.githubusercontent.com/13006107/93399819-4fe78f80-f84c-11ea-9fe2-4a1db7630bd4.png)

*****
[Swift 5.3 Announcement Blog](https://swift.org/blog/swift-5-3-released/)

**Comment by Chuxel** [comment]
@prabh-62 Thanks for raising the issue! We can add it once it is [available upsteam](https://hub.docker.com/_/swift).

**Comment by Chuxel** [comment]
Updated! Near term you can just set `"VARIANT":"5.3"` in devcontainer.json
