### ISSUE TITLE
Properly document the Dockerfile requirements for the scripts

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-dev-containers#563]
For example, `node-debian.sh` seems to require:

```Dockerfile
ARG NODE_VERSION="lts/*"
ENV NVM_DIR=/usr/local/share/nvm
ENV NVM_SYMLINK_CURRENT=true \
  PATH=${NVM_DIR}/current/bin:${PATH}
```

In order to work properly. 

At least until we have https://github.com/microsoft/vscode-remote-release/issues/3593, otherwise the scripts would take care of it by themselves.

**Comment by Chuxel** [comment]
@felipecrs Yep, agreed - Had this on the list here: #560. Can reuse this as the specific item for docs.

**Comment by Chuxel** [comment]
This is complete. Scripts will also reference the location of the doc for the script.

**Comment by felipecrs** [comment]
The new docs are very nice. It's very clear now how to use those scripts. :-D

Thank you @Chuxel!
