### ISSUE TITLE
.NET 5 - Missing DevContainer Configuration File

### ISSUE THREAD

**Issue by prabh-62** [microsoft/vscode-dev-containers#567]
## System Info
- VSCode Version: `1.49.1`
- Local OS Version: `Microsoft Windows 10 Pro 2004 (10.0.19041 N/A Build 19041)`
- Name of Dev Container Definition: `C#`

## Steps to Reproduce:
1. In VS Code, try to open any folder in container 
2. Choose `C#` and then try to select `5.0` version.
![net31_devcontainer](https://user-images.githubusercontent.com/13006107/93671287-ad0f5b00-fa6f-11ea-9c83-118523640032.png)

*****
[.NET 5 docker images](https://hub.docker.com/_/microsoft-dotnet-core)

**Comment by Chuxel** [comment]
We typically only add LTS versions of releases and .NET 5 is not LTS. That said, happy to take a PR on it.

**Comment by prabh-62** [comment]
@Chuxel since, .NET 5 is not branded as .NET Core ([Source](https://docs.microsoft.com/en-us/dotnet/core/dotnet-five))

<img width="625" alt="containers_dotnetcore" src="https://user-images.githubusercontent.com/13006107/95657325-02281500-0ae2-11eb-826f-0e2b7d2e0386.png">

Should there be a separate entry for `C# (.NET)` ?

**Comment by grufffta** [comment]
@prabh-62 this may help, it's still work in progress - I haven't tested the docker part yet and it also installs go and nodejs/typescript which you may not want. I'm planning to make these optional soon.

https://github.com/grufffta/vscode-dev-containers/tree/feature/dotnet-5-devcontainer/containers/dotnet-5

@Chuxel would be happy to do a PR for this when it is finished.

Thanks

**Comment by Chuxel** [comment]
Resolved with #648
