### ISSUE TITLE
Merge ENV statements to reduce amount of layers

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-dev-containers#571]
If we see for example the [documentation about the Node script](https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/docs/node.md), it says:

```Dockerfile
ENV NVM_DIR="/usr/local/share/nvm"
ENV NVM_SYMLINK_CURRENT=true \
    PATH=${NVM_DIR}/current/bin:${PATH}
```

But it could be simplified to:

```Dockerfile
ENV NVM_DIR="/usr/local/share/nvm" \
    NVM_SYMLINK_CURRENT=true \
    PATH=${NVM_DIR}/current/bin:${PATH}
```

In order to reduce the amount of the layers in the Docker image.

This could possibly be applied to all the Dockerfiles and the scripts docs.

**Comment by Chuxel** [comment]
@felipecrs This doesn't work because NVM_DIR is used in the path, and therefore is not defined.

**Comment by felipecrs** [comment]
You're totally right, I tested before and I thought that it worked in the same `ENV` statement, but now I tested again and it does not work.

![image](https://user-images.githubusercontent.com/29582865/93810346-5dfa2f00-fc03-11ea-959a-02c558e492bb.png)

Sorry for the confusion.
