### ISSUE TITLE
codespaces-linux won't run docker-in-docker

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/vscode-dev-containers#589]
- VSCode Version: 1.50.0-insider
- Local OS Version: Windows 10
- Name of Dev Container Definition with Issue: codespaces-linux with a few added tools:
[custom.devcontainer.zip](https://github.com/microsoft/vscode-dev-containers/files/5304261/custom.devcontainer.zip)
- Cloned from: https://github.com/microsoft/vscode-dev-containers/tree/baee53e329f84d2de4bda861dfb231a90088d3b5

Steps to Reproduce:

1. I copied the current codespaces-linux to my own repo and ran it.
2. run `docker build .` fails with:

```
codespace ➜ ~/workspace/CodeToCloud-Source/content-api (temp ✗) $ docker build .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

When I remove the `.devcontainer` folder from my repo and start the default `GitHub Codespaces (Default)` it succeeds to run docker-in-docker, but has an older version of `gh`, indicating to me that it didn't run the latest image.

**Comment by jessehouwing** [comment]
It looks like re-running this from the vscode terminal

```
SOURCE_SOCKET=${2:-"/var/run/docker-host.sock"}
TARGET_SOCKET=${3:-"/var/run/docker.sock"}
sudo touch "${SOURCE_SOCKET}"
sudo ln -s "${SOURCE_SOCKET}" "${TARGET_SOCKET}"
```

fixes the container.

**Comment by Chuxel** [comment]
@jessehouwing Are you in codespaces or Remote - Containers?

**Comment by jessehouwing** [comment]
Code spaces.

**Comment by jessehouwing** [comment]
Running the container locally on Windows 10 2004 fails too with the same error.

**Comment by Chuxel** [comment]
I think I see the bug.  Update `Dockerfile` as follows:

```Dockerfile
ARG INSTALL_DOCKER="false"
COPY library-scripts/docker-debian.sh /tmp/scripts/
RUN if [ "${INSTALL_DOCKER}" = "true" ]; then \
        rm -f /usr/local/share/docker-init.sh \
        && bash /tmp/scripts/docker-debian.sh "true" "/var/run/docker-host.sock" "/var/run/docker.sock" "${USERNAME}"; \
    fi \
    && rm -rf /tmp/scripts && apt-get clean -y
```
The script skips adding the docker-init.sh script in if it's already there, and it would be in the image.  Will update.

**Comment by jessehouwing** [comment]
Confirming [this update](https://github.com/microsoft/vscode-dev-containers/issues/589#issuecomment-701402485) does the trick.
