### ISSUE TITLE
DockerHub page has bad link to `dotnetcore` images

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode-dev-containers#591]
On https://hub.docker.com/_/microsoft-vscode-devcontainers I see this text:

> mcr.microsoft.com/vscode/devcontainers/dotnetcore - 3.1, 2.1 (Details)

The `Details` link goes to https://github.com/microsoft/vscode-dev-containers/tree/master/containers/go

Notice it is `go` instead of `dotnetcore`.
Please fix the link on docker hub.

**Comment by Chuxel** [comment]
Fixed in MCR, will deploy shortly!
