### ISSUE TITLE
All node.js configurations fails with: Certificate has expired

### ISSUE THREAD

**Issue by madsd** [microsoft/vscode-dev-containers#597]
- VSCode Version: 1.50.0-insider
- Local OS Version: Windows 10 20H2
- Name of Dev Container Definition with Issue: javascript-*

Steps to Reproduce:

1. Create devcontainer - fail in pulling image FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:${VARIANT}

error pulling image configuration: Get https://westeurope.data.mcr.microsoft.com/42012bb2682a4d76ba7fa17a9d9a9162-qb2vm9uiex//docker/registr
y/v2/blobs/sha256/74/742892642b9f0125c048b4093f0c3a85c64d7e1407b3a37a74c0d96ce3de1a94/data?P1=1601903924&P2=1&P3=1&P4=0EaN0jE%2FSR%2FOHjqVp%
2FsOhnNyivFnVpSu%2BpGUs%2FxfCEY%3D&se=2020-10-05T13%3A18%3A44Z&sig=S69lCTKgiwOlYijdtydZTSPrqhUd67KT4FiyfEIGXYI%3D&sp=r&sr=b&sv=2016-05-31&re
gid=42012bb2682a4d76ba7fa17a9d9a9162: x509: certificate has expired or is not yet valid

**Comment by Chuxel** [comment]
@madsd Is this in Remote - Containers or Codespaces? Generally I've seen this happen when the system clock is wrong.  One problem that Docker Desktop seems to have is it slowly drifts the time while the laptop is asleep and this can happen.  It's a well known bug that goes away and then comes back in Docker Desktop... must be hard for them to finally fix.

Typically restarting Docker (or your machine) solves it if that is the problem.  If that's not it, then this is a MCR issue in west West Europe specifically or something with caching in your network. It does not repro where I am which would hit East US.

**Comment by madsd** [comment]
It was - all good again. Thank you for the hint, and now hopefully others can quickly find a resolution until a general fix is available.
