### ISSUE TITLE
docker-from-docker: Debug "Docker .NET Core Launch" inside devcontainer fails

### ISSUE THREAD

**Issue by CurlyFire** [microsoft/vscode-dev-containers#598]
**- VSCode Version**:1.49.3
**- Local OS Version**:Ubuntu 20.04.1 LTS (Focal Fossa)
**- Name of Dev Container Definition with Issue**:C# Sample

**Error message from VSCode :** 
The pipe program 'docker' exited unexpectedly with code 126.

**Output from debug console :** 
Starting: "docker" exec -i vscoderemotetrydotnetcore-dev /remote_debugger/vsdbg --interpreter=vscode
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/remote_debugger/vsdbg\": stat /remote_debugger/vsdbg: no such file or directory": unknown

**Steps to Reproduce:**
https://github.com/CurlyFire/vscode-remote-try-dotnetcore contains steps 1 through 5 below:

1. Fork the remote sample https://github.com/microsoft/vscode-remote-try-dotnetcore
2. Clone repository in container volume
3. Enable root access to Docker in the container from instructions located at https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-from-docker
4. Add docker extension (ms-azuretools.vscode-docker) to devcontainer
5. Add docker files to workspace... (using docker extension)
6. Start debug "Docker .NET Core Launch"
7. Crash

EDIT : I have investigated further, and the "Docker .NET Core Launch" depends on the task "docker-run: debug".  When I check the output of this task, I see that it executes this command to start the container:

> docker run -dt -P --name "vscoderemotetrydotnetcore-dev" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "ASPNETCORE_ENVIRONMENT=Development" --label "com.microsoft.created-by=visual-studio-code" -v "/workspaces/vscode-remote-try-dotnetcore:/app:rw" -v "/workspaces/vscode-remote-try-dotnetcore:/src:rw" **-v "/root/.vsdbg:/remote_debugger:ro"** -v "/root/.nuget/packages:/root/.nuget/packages:ro" -v "/root/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro" "vscoderemotetrydotnetcore:dev" <

The problem seems to stem from the fact that it volume mounts vsdebugger from the /root/.vsdbg.  However, I am logged in as a different user.  The .vsdbg folder exists for my user, but not for the root user.  I am not sure when the vsdbg folder is created, but it's probably from the docker extension.

Am I supposed to setup the dev container to run under my user to make sure it finds the vsdbg files ?

**Comment by Chuxel** [comment]
Hmmm. Unfortunately this appears to be a problem with the Docker extension. Fundamentally bind mounts (which is what this is) use the host's paths in docker-from-docker as described here: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-from-docker#using-bind-mounts-when-working-with-docker-inside-the-container

Since the extension is doing this, it would need to provide a way for you to specify an alternate path. 

Please raise it in that repository so they can take a look.

**Comment by CurlyFire** [comment]
@Chuxel, Thanks for the quick reply, I will raise this issue in the docker extension repository.

**Comment by nickspiers** [comment]
@CurlyFire Did you find any decent workaround for this? I can't find your issue in the docker extension repository or any similar issue. I was thinking I could add volume mounts to the devcontainer for all the root mounts needed, but I was hoping for a better solution.
Thanks

**Comment by EinarasGar** [comment]
For anyone who is having the same issue, I have found a workaround. It is not ideal, but it works
Basically you have to copy debugger files to your host machine to that location. In my case, I am using net core image with vscode user set up by default
I gave the user docker group as described here https://github.com/microsoft/vscode-dev-containers/tree/main/containers/docker-from-docker#enabling-non-root-access-to-docker-in-the-container
Then when I try to launch debugger, it tries to copy files from `/home/vscode/.vsdbg`
So I copied debugger from the container `docker cp 73b7aa53dfa5:/home/vscode/.vsdbg /home/vscode/.vsdbg`
And then it works. 

Wish this was fixed though.
