### ISSUE TITLE
Verify dapr definitions still working as expected, use pre-built images / refresh if needed

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#620]
There are two Dapr definitions that have not been updated in a while:

- [Dapr Node 12](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dapr-typescript-node-12)
- [Dapr .NET 3.1](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dapr-dotnetcore-3.1)

These definitions do not use pre-built images and therefore can have longer build times that could be cut down by using `mcr.microsoft.com/vscode/devcontainers/javascript-node:12` and `mcr.microsoft.com/vscode/devcontainers/dotnetcore:3.1` respectively. There were also some initial issues with Codespaces that should be resolved, but it would be good to verify.

With that in mind, it's probably worth looking through these and make sure they're still in good shape.

/cc: @philliphoff who contributed the definitions

**Comment by philliphoff** [comment]
@Chuxel It's on my list of things to do.

**Comment by Chuxel** [comment]
@philliphoff Thanks! Appreciate it!
