### ISSUE TITLE
running in a dockerized miniconda 3 environment, ERROR not found

### ISSUE THREAD

**Issue by MosheVai** [microsoft/vscode-dev-containers#657]
I am trying to run my code inside a miniconda3 docker runtime,
I saw in [here](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/python-3-miniconda)  that the following is the public image name:

> mcr.microsoft.com/vscode/devcontainers/minconda (or minconda:3)

I tried  to do it both in the `Dockerfile` and in the `docker-compose.yml`

```docker-compose.yml
version: "3"
services:
  conda_runtime:
    container_name: conda_runtime
    image: mcr.microsoft.com/vscode/devcontainers/minconda:3
    restart: unless-stopped
```

```Dockerfile
FROM mcr.microsoft.com/vscode/devcontainers/minconda:3
```

However I get the same error:

```
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: mcr.microsoft.com/vscode/devcontainers/minconda:3 not found
```

**Comment by Chuxel** [comment]
You have a typo.  Should be `miniconda`.
