### ISSUE TITLE
Problem with python dev-container definitions

### ISSUE THREAD

**Issue by kmehant** [microsoft/vscode-dev-containers#66]
- VSCode Version: **1.34.0**
- Local OS Version: **MacOS Mojave**
- Name of Dev Container Definition with Issue: `python-3` `python-2`

Steps to Reproduce:
1. After opening the definition in the container, the shell points to `/workspaces/vscode-dev-containers/containers/python-3`
2. Seems like `python-3` as workspace containing the `test-project`. 
3. The new workspace directory created does not stay in the **dev-container folder** rather it is in the **root directory** of the container.
4. Looks like line **12** and **18** quite conflicting with respect to normal docker behavior as `WORKDIR` changes the current directory to **workspace**
5. Let's say **workspace** which is in the root directory as my actual workspace then I have to add the **workspace** folder to my actual **vs code workspace** in order to work. This seems like two workspaces created. 
6. There is another **serious** issue as when I click the debug button that debugs the test code as mentioned in the `launch.json` file. So I have to update the `program` attribute with respect to my actual workspace which resides in the root directory.

Possible solution:
1. As of now, the python modules are being installed **globally**. (as no python env are used) so it's better to remove lines **11, 12, 18** as they seem to be not required
2. We will add the `requirements.txt` files to the  `/workspaces/vscode-dev-containers/containers/python-3`  and then check and finally pip install modules.
3. If needed then better to add custom workspace in this directory `/workspaces/vscode-dev-containers/containers/python-3` For that we might need to pass the `workspaceFolder` value as an environment variable which we can use to create the workspace.

https://github.com/microsoft/vscode-dev-containers/blob/236e43a8fd25d9cc781fbee544f77856dd79f27d/containers/python-3/.devcontainer/Dockerfile#L11-L19

**Comment by kmehant** [comment]
@Chuxel Would like to contribute to this.

**Comment by Chuxel** [comment]
> After opening the definition in the container, the shell points to /workspaces/vscode-dev-containers/containers/python-3

The reason the path is as you see it is actually to get **git** to work.  The container mount goes up to the root of the cloned git repository when one is detected.  If you do not do this, mounting a sub-folder of a git repository will prevent you from doing source control operations (since to the container it just looks like a folder).

> Seems like python-3 as workspace containing the test-project.
> The new workspace directory created does not stay in the dev-container folder rather it is in the root directory of the container.
> The new workspace directory created does not stay in the dev-container folder rather it is in the root directory of the container.
Looks like line 12 and 18 quite conflicting with respect to normal docker behavior as WORKDIR changes the current directory to workspace
> Let's say workspace which is in the root directory as my actual workspace then I have to add the workspace folder to my actual vs code workspace in order to work. This seems like two workspaces created.

The `WORKDIR` problem is really not a major problem since the point VS Code connects to can be anything. The purpose for it is actually to get the `requirements.txt` file into the container so the requirements are added **before** the project file mount actually happens.  We could possibly clean up the folder afterwards.

>As of now, the python modules are being installed globally. (as no python env are used) so it's better to remove lines 11, 12, 18 as they seem to be not required
> We will add the requirements.txt files to the /workspaces/vscode-dev-containers/containers/python-3 and then check and finally pip install modules.
> If needed then better to add custom workspace in this directory /workspaces/vscode-dev-containers/containers/python-3 For that we might need to pass the workspaceFolder value as an environment variable which we can use to create the workspace.

I described the purpose of the `requirements.txt` code in #67, but it is clear this is causing confusion.  The goal is to get the requirements from the actual requirements.txt in the user's project added to the container... which isn't present here. The file that exists now is for the test project.  We can discuss whether we think this is the right thing in the other issue.

> There is another serious issue as when I click the debug button that debugs the test code as mentioned in the launch.json file. So I have to update the program attribute with respect to my actual workspace which resides in the root directory.

Note sure what you mean here.  Are you getting an error?

**Comment by kmehant** [comment]
>The reason the path is as you see it is actually to get git to work. The container mount goes up to the root of the cloned git repository when one is detected. If you do not do this, mounting a sub-folder of a git repository will prevent you from doing source control operations (since to the container it just looks like a folder).

True! I agree with this. seems not an issue.

>The WORKDIR problem is really not a major problem since the point VS Code connects to can be anything. The purpose for it is actually to get the requirements.txt file into the container so the requirements are added before the project file mount actually happens. We could possibly clean up the folder afterward.

And here I think we are making two workspaces one would be the directory in which we have the **.devcontainer** folder and other is the folder **workspace** made in the root directory of the terminal. So it's better to rm the **workspace** after the job is done as it might cause some confusion to devs.

> Not sure what you mean here. Are you getting an error? 

So as I have mentioned above it seems we are creating two workspaces. So if anyone starts to work on the one present in the root directory then that will be an issue when we try to use a debugger as it points to the other workspace as launch.json is so configured. So we have to change the launch.json so it points it to the workspace in the root directory. That might be an easy fix but not to everyone 😃 

So the best way would be to remove workspace directory which is created by the Dockerfile just after installing the python modules would do the job. So will be left with a single workspace.

**Comment by Chuxel** [comment]
I think the other comments beyond `requirements.txt.temp` here were addressed, so let's consolidate the remaining discussion in #67 where that discussion is happening.
