### ISSUE TITLE
Add support for C# .Net 5.0 remote container

### ISSUE THREAD

**Issue by danbcd** [microsoft/vscode-dev-containers#667]
Right now, when we select the Remote-Containers: Add Development Container Configuration Files when we select C# (.Net core), we only have versions 3.1 (default) and 2.1, 5.0 is not available.

It would be nice to have C# .Net 5.0 remote container available.

**Comment by Chuxel** [comment]
Good news! This is already resolved and will be in the next release.  See https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnet
