### ISSUE TITLE
Remove Oh My Bash in favor of a custom PS1

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#674]
Currently we are using Oh My Bash for the default prompt in dev containers that use the common-debian.sh script (partly due to Bash It not having any license). While this works well, there are challenges that people are hitting where they've customized their shell prompt and Oh My Bash is overriding it.  Unlike Oh My Zsh!, Oh My Bash is not ubiquitous so this can be counter intuitive. It may be better to instead create a custom prompt that matches the UX we currently have, but not use Oh My Bash to do it. 

Anyone that then wants to use Oh My Bash or Bash It could install these on their own.

We can replace this with a PS1 script that mimics the current default shell behavior.

//cc: @jkeech given #670 is an example of this problem. @matthewisabel I think encountered a similar problem with his dotfiles.

**Comment by burkeholland** [comment]
This was confusing for me because I thought it was zsh. And I could not figure out why, despite my setting it to bash in the config file, it was defaulting to zsh. But I also have never heard of oh-my-bash.

I think this is going to catch people off guard. I'd expect to see a normal, non-customized bash prompt.

**Comment by Chuxel** [comment]
@burkeholland Yeah, the surprising part is it seems to be hijacking customization. That's too bad since it adds other value as well.  But I agree that the way it is now is probably more trouble than it is worth.

**Comment by Chuxel** [comment]
A PR is up to remove switch to a PS1 script instead of Oh My Bash. Once it is no longer in images, you can install it using your `dotfiles` or in a Dockerfile as follows:

From dotfiles / a terminal window:
```bash
rm -rf ~/.oh-my-bash
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
```

In a Dockerfile:
```bash
ARG USERNAME=vscode
RUN su $USERNAME -c 'rm -rf $HOME/.oh-my-bash && bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"'
```
