### ISSUE TITLE
tslint is deprecated and should not be included in typescript-node

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-dev-containers#687]
Tslint has been deprecated and replaced by eslint. The tslint extension inclusion should be remove from the TypeScript Node dev container configuration

https://github.com/microsoft/vscode-dev-containers/blob/3d59f9fe37edb68f78874620f33dac5a62ef2b93/containers/typescript-node/.devcontainer/devcontainer.json#L17

**Comment by Chuxel** [comment]
Resolved with #688
