### ISSUE TITLE
Feature Request: Add Azure CLI to php

### ISSUE THREAD

**Issue by litan1106** [microsoft/vscode-dev-containers#694]
Please add the Azure CLI to php docker image

https://github.com/microsoft/vscode-dev-containers/blob/master/containers/php/.devcontainer/base.Dockerfile

**Comment by Chuxel** [comment]
Hey @litan1106 The Azure CLI is surprisingly large so we won't likely be adding it into base images by default.  There's a simple script you can use to install it in your own Dockerfile.

https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/docs/azcli.md

That meet your needs?

**Comment by litan1106** [comment]
> Hey @litan1106 The Azure CLI is surprisingly large so we won't likely be adding it into base images by default. There's a simple script you can use to install it in your own Dockerfile.
> 
> https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/docs/azcli.md
> 
> That meet your needs?
> 
> EDIT: We're discussing a way to add arbitrary scripts in this issue: #615.

I saw the Azure CLI script in the dotnet base image that was why I requested it on the php base image too.

https://github.com/microsoft/vscode-dev-containers/blob/master/containers/dotnet/.devcontainer/base.Dockerfile#L28

**Comment by Chuxel** [comment]
It's not actually in the pre built image but is an option in the Dockerfile. This pre dates the reusable scripts.
