### ISSUE TITLE
Xdebug version 3.0...  doesn't work in php Dev Container 

### ISSUE THREAD

**Issue by vinser** [microsoft/vscode-dev-containers#695]
- VSCode Version: 1.52.0
- Local OS Version: Windows 10 Pro 20H2 build 19042.630
- Name of Dev Container Definition with Issue: vscode-dev-containers/containers/php/

Steps to Reproduce: 
1. Start apache2ctl start
2. Set breakpoint and launch Xdebug (f5)
3. Open localhost:8080. Debugger will not catch breakpoint.

Workaround:
1. Use [base.Dockerfile](https://github.com/microsoft/vscode-dev-containers/blob/master/containers/php/.devcontainer/base.Dockerfile)
2. Replace code:

`# Install xdebug
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && rm -rf /tmp/pear`

with something like this:

`# Install xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug \
    && echo "xdebug.mode = debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.start_with_request = yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_host = host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.discover_client_host = false" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_port = 9003" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.log = /var/www/html/xdebug.log" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
`

3. Don't forget to change port 9000 to 9003 in launch.json 

It works for me. 

It will be nice to see mcr.microsoft.com/vscode/devcontainers/php container update.

Edit12/26/2020: 
On Dec 22 Felix Becker fixed his PHP-Debug extension to work with xdebug 3. So it's time to  fix php devcontainers! :)

**Comment by vinser** [comment]
On Dec 22 Felix Becker fixed his PHP-Debug extension to work with xdebug 3. So it's time to fix php devcontainers! :)

**Comment by Chuxel** [comment]
This update would also apply to the codespaces-linux definition.

**Comment by Chuxel** [comment]
This should be resolved in master! It will go out next release.  Thanks!
