### ISSUE TITLE
Docker in docker cannot access files in local workspace folder

### ISSUE THREAD

**Issue by apoorvmote** [microsoft/vscode-dev-containers#700]
- VSCode Version: 1.52.1
- Local OS Version: WSL2 Ubuntu 20.04
- Name of Dev Container Definition with Issue: Docker in docker

Steps to Reproduce:

1. Remote container: Add development container configuration files
2. Select docker in docker
3. I have only updated dockerfile to install `nodejs` at then end and installed `npm i -g aws-cdk`
4. In my cdk project I run `cdk diff` and I get following error
5. `> error: Could not read from file: /asset-input/lambda-fns/01-test/get-item/index.ts`
6. I reopen project in WSL 2 with Ubuntu 20.04 and without changing any code, everything runs properly. But docker client cannot access files only from docker dev container.

**Comment by Chuxel** [comment]
This is explained here: https://github.com/microsoft/vscode-dev-containers/blob/master/containers/docker-from-docker/README.md#using-bind-mounts-when-working-with-docker-inside-the-container

This is docker-from-docker, not docker in docker.

**Comment by apoorvmote** [comment]
Sorry I only changed the name of dev container from `docker from docker` to `myContainter` but all the settings were kept default. 

This is my `devcontainer.json`

```json
{
	"name": "Docker from Docker",
	"dockerFile": "Dockerfile",
	"runArgs": ["--init"],
	"mounts": [ "source=/var/run/docker.sock,target=/var/run/docker-host.sock,type=bind" ],
	"overrideCommand": false,
	
	// Use this environment variable if you need to bind mount your local source code into a new container.
	"remoteEnv": {
		"LOCAL_WORKSPACE_FOLDER": "${localWorkspaceFolder}"
	},

	// Set *default* container specific settings.json values on container create.
	"settings": { 
		"terminal.integrated.shell.linux": "/bin/bash"
	},

	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"ms-azuretools.vscode-docker"
	],
	
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "docker --version",

	// Comment out connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "vscode"
}
```

**Comment by Chuxel** [comment]
I don't know what the AWS CDK expects here, but if it is firing docker statements itself that do the volume mounts instead of you, it would not work in this configuration. The volume mount has to reference the `${LOCAL_WORKSPACE_FOLDER}` env var as described in the README.

There is a full "docker-in-docker" script that is getting worked on in this PR that would run docker actually inside the container to avoid that: https://github.com/microsoft/vscode-dev-containers/pull/702

**Comment by apoorvmote** [comment]
So my use case is to compile and build lambda function source code to deploy with CDK. 

One way it can be done is with building inside a container to match production environment. I recently found the other way of building lambda funtion with `esbuild`. [esbuild](https://esbuild.github.io/) is written in golang and it builds insanely faster. I wrote blog post on [how to compile and build typescript lambda with cdk and esbuild](https://apoorv.blog/posts/build-aws-lambda-function-typescript-cdk.html). It lacks building inside container with near production environment but it makes up by building 100's of lambda functions within seconds. 

SO THE ISSUE IS NOT RESOLVED. But I am closing this issue because I no longer need this.

**Comment by Chuxel** [comment]
@apoorvmote Yep, this is exactly why we're also creating the docker-in-docker container. It adds a bit of overhead on macOS and Windows, but it gives you more complete control.

Good news is we merged the in docker-in-docker container today.  See if this one works for your scenario:  https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-in-docker

**Comment by apoorvmote** [comment]
@Chuxel Thanks for notifying me Chuck!!

I did run docker in docker and it works perfectly. 

So I no longer use docker to compile and build lambda function from this issue. But I do use docker to run lambda locally with SAM Cli and iterate lambda function quicker with local invoke. And it works perfectly. 

And you are right it does take massive ram. I haven't even tried it on my macOS at all. I only use docker with Windows because windows machine has 16 GB RAM and macOS has only 4GB RAM. On windows I cannot get google chrome to cache any website while I am using docker in docker. When I switch to chrome then fresh page load happens every time.

**Comment by Chuxel** [comment]
@apoorvmote Depending on your setup, you may need to give Docker Desktop more RAM.  If you're in Hyper-V mode, it only gets 2GB by default.

**Comment by apoorvmote** [comment]
@Chuxel I am using WSL 2 with Ubuntu 20.04 for Docker Desktop. I have 16GB RAM so 50% is allocated by default to WSL and Docker Desktop I think :thinking:. And all CPU cores are shared between Windows and WSL2. I haven't overriden any WSL settings. 

My motherboard does support upto 32 GB Ram and I bought my computer 2 years ago. I am going to add another 16 GB but cost of 16 RAM today is same as it was 2 years ago. So I will upgrade as the price drops. That should help.

**Comment by apoorvmote** [comment]
@Chuxel I found the culprit. If I am working long time on dev containers then `vmmem` process starts to consume 95% of the ram unnecessary. Easy fix is to reboot the computer and ram usage drops to 50%-60%. 16GB ram is enough. You just need to reboot computer often to fix the issue.
