### ISSUE TITLE
Puppeteer no longer works out-of-the-box in new Ubuntu 20.04-based Default Codespaces

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#706]
Reference: https://github.community/t/feedback-puppeteer-no-longer-works-out-of-the-box-in-new-ubuntu-20-04-based-default-codespaces/153440

In the original Stretch-based image, Puppeteer can be installed and used right out-of-the-box. However with the Default Codespaces “universal” image now based on Ubuntu 20.04, it no longer works by default due to missing dependencies.

This one-liner should fix it based on troubleshooting in the [Puppeteer repo](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix). 

```bash
sudo apt-get update && sudo apt-get install -y --no-install-recommends ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
```

Something about the installed dependencies affected libraries that are in the new image, and adding these appears to take ~77mb in the Codespace. That's low enough compared to the overall image we can look into adding them again.

**Comment by Chuxel** [comment]
//cc: @jkeech @joshspicer for this issue since its for the codespaces image.

**Comment by joshspicer** [comment]
libraries not found with `ldd` 
![image](https://user-images.githubusercontent.com/23246594/103811366-d0641300-502a-11eb-9a4f-0ef9854655df.png)

**Comment by joshspicer** [comment]
minimum list i've been able to find to get my example repo working (https://github.com/joshspicer/puppeteer-example)

```bash
apt-get install  --no-install-recommends libnss3 libnspr4 libatk-bridge2.0-0 libatk1.0-0 libx11-6 libpangocairo-1.0-0 \
                                                libx11-xcb1 libcups2 libxcomposite1 libxdamage1 libxfixes3 libpango-1.0-0 libgbm1 libgtk-3-0
```
