### ISSUE TITLE
Debugging running on path which have https:// twice in url

### ISSUE THREAD

**Issue by anirugu** [microsoft/vscode-dev-containers#709]
- VSCode Version:
- Local OS Version:
- Name of Dev Container Definition with Issue:

Steps to Reproduce:

Create a Blank repos or switch to another directory in existing codespaces. Now when I do dotnet new api it's create the api project. Now when I debug them it's open 'https://https//{longGUIDhere}.apps.codespaces.githubusercontent.com/swagger'

You can see that url have https:// twice in url. I remove the https and correct the url and it's start working. Find the same few weeks ago and find this today.

**Comment by Chuxel** [comment]
@anirugu Thanks for raising!  Please raise this in the Codespaces Beta feedback channel here since this is not specific to the actual container image. 

https://github.community/c/code-to-cloud/codespaces-beta/45
