### ISSUE TITLE
"Docker run" on docker-in-docker container fails

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode-dev-containers#714]
The codespaces universal/kitchensink image provides sanity tests of the form `docker run IMAGE ... ...`.  I caught and can repro docker-in-docker (and subsequently kitchensink) get these permission denied errors from the `docker-init.sh`. They are wrapped in `SudoIf` statements.  Strange because I can spin this up in remote containers just fine, but can repro with a `docker run`.

https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/docker-in-docker-debian.sh#L144-L158

![image](https://user-images.githubusercontent.com/23246594/104051669-7c863500-51b6-11eb-9dc8-e95ff43c50e0.png)

@Chuxel long shot, but have you seen anything like this before?

cc/ https://github.com/microsoft/vssaas-planning/issues/1588

**Comment by jkeech** [comment]
@joshspicer, is it because we need to run the container with `--privileged`?

**Comment by joshspicer** [comment]
Yep 😅.  Swear i'd tried that earlier, I think i'd placed that flag in the wrong order.
