### ISSUE TITLE
ARM builds planned?

### ISSUE THREAD

**Issue by oberbeck** [microsoft/vscode-dev-containers#715]
As apple is pushing their M1 chips, are there ARM builds planned to speed up work done inside `devcontainers` on the latest Macs?

Using these `x86` work but it feels very slow. I recompiled the `typescript-node` using `arm64v8/node` instead of the regular `node` base container and it feels a lot smoother.

**Comment by 2percentsilk** [comment]
Hi @oberbeck.

We've already got an issue tracking this request at #558 and I encourage you to follow along there/upvote it! 

As a note, this request will require a bit of work so we don't have an ETA to share for fulfilling it.

I'm going to close this issue as a duplicate but feel free to re-open if you disagree/have further comments that you don't think belong on #558.
