### ISSUE TITLE
Can't run docker-in-docker when inheriting from linux-universal.

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/vscode-dev-containers#717]
- VSCode Version:
- Local OS Version: Windowr 10
- Name of Dev Container Definition with Issue:

Very similar to: https://github.com/microsoft/vscode-dev-containers/issues/589, new version of the image seems to have re-introduced the same bug.

Create a custom image, inheriting from FROM mcr.microsoft.com/vscode/devcontainers/universal:linux

```
FROM mcr.microsoft.com/vscode/devcontainers/universal:linux

USER codespace

RUN npm install -g @angular/cli 
    
RUN az extension add --name azure-devops \
    && az extension add --name application-insights \
    && az extension add --name portal

ADD Microsoft.PowerShell_profile.ps1 /home/codespace/.config/powershell/Microsoft.PowerShell_profile.ps1
ADD Microsoft.PowerShell_profile.ps1 /home/codespace/.config/powershell/Microsoft.VSCode_profile.ps1
```

Docker complains:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

**Comment by jessehouwing** [comment]
@Chuxel

**Comment by 2percentsilk** [comment]
Hi @jessehouwing, after consulting with Chuck, we think we know the issue here. If you look at 'tmp/dockerd.log` you'll likely see a permissions error. To fix this, you'll need to tweak the runArgs in your devcontainer.json to include `--privileged` and `--init`. You'll also want to remove `mounts` as we've recently updated the universal image to use docker-in-docker and bound mounts should be taken care of for you.

**Comment by jessehouwing** [comment]
That sounds awesome. I'll run more tests tomorrow

**Comment by jessehouwing** [comment]
That indeed fixes it! Thanks for the quick feedback.

With everyone replicating these docker files and devcontainer.jsons in will become more of an issue in the future I guess... things breaking when you rebuild the image... Are you getting any telemetry on those kinds of things?

**Comment by jessehouwing** [comment]
I basically copied over all the new script files into my repo and re-applied our changes.

Only thing we had to Chang on top of this was to oudate the devcontainer.json to use Dockerfile instead if base.Dockerfile.
