### ISSUE TITLE
Specify name and tag when building image

### ISSUE THREAD

**Issue by yosider** [microsoft/vscode-dev-containers#719]
Is it possible to specify name and tag of an image in `devcontainer.json` when building an image from Dockerfile?
I read the official reference but I could not find something like `"build.name"` or `"build.tag"`.
https://code.visualstudio.com/docs/remote/devcontainerjson-reference

**Comment by 2percentsilk** [comment]
Hi there,

This is currently tracked as a feature request for remote containers at microsoft/vscode-remote-release#3650 so I'm going to close this as a duplicate! Please upvote/comment/follow along at the other issue.
