### ISSUE TITLE
Error in Docker-from-Docker documentation

### ISSUE THREAD

**Issue by erinxocon** [microsoft/vscode-dev-containers#726]
**EDIT: I didn't realize that the directions may be only for codespaces which I thought was the new name for devcontainers. I am not using codespaces and am just using dev containers on my local linux machine. If the directions are indeed only for codespaces than I shall close my issue! :pray:**

- VSCode Version:
- Version: 1.53.0-insider
- Commit: 32b28f6f8f9dfe36efad102cc460e14a84ba756a
- Date: 2021-01-19T06:10:13.886Z
- Electron: 11.2.0
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Linux x64 5.4.0-62-generic

- Name of Dev Container Definition with Issue: docker-from-docker

There isn't a problem with the dev container definition per se, however I believe that the definition is doing things to enable non-root docker access inside of a container that the documentation misses.

In this section [here](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-from-docker#enabling-non-root-access-to-docker-in-the-container) we are told that we just have to follow the previous steps in installing the docker-ce-cli and then get the docker group and add our new user to it. The documentation says you can add the following to your Dockerfile to achieve this (also missing a slash in the second to last line):

```Dockerfile
RUN export SOCKET_GID=$(stat -c '%g' /var/run/docker.sock) \
    && if [ "$(cat /etc/group | grep :${SOCKET_GID}:)" = "" ]; then \
        groupadd --gid ${SOCKET_GID} docker-host; \
    fi \
    && if [ "$(id ${NONROOT_USER} | grep -E 'groups=.+\${SOCKET_GID}\(')" = "" ]; then \
        usermod -aG ${SOCKET_GID} ${NONROOT_USER}; \
    fi
```

This step causes any dockerfile to fail as there is no `/var/run/docker.sock` at build time even after the docker cli is installed. It is only present after vscode runs the container. The documentation even talks about you can run `stat -c '%g' /var/run/docker.sock` inside of the container to get the group id that docker is using, but again that only works because you are running it inside of a container that already has the docker socket available to it. 

When you go back to look at the actual dockerfile and devcontainer.json in the repository you can see that it is not doing what the documentation says. I can see that there are parts of the code from the documentation in the library-scripts folder, however it seems like the end container doesn't actually do much at run, but relies on doing `socat` stuff as apart of entryscript. To be clear, standing up the image from this repository works fine and I can access docker inside of it....it's just that the documentation tells you something that isn't possible and says that the method that ends up actually getting used is the [final fallback](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-from-docker#final-fallback-socat).

I was hoping some clarification could be given specifically on the linux platform as this issue doesn't really matter on hosts that run docker in a VM or whatever. Is there a way to query something on the host during build time that I am not aware of? I have gotten scripts to work as a part of the "postCreateCommand" property to add myself to the group returned back by the `stat` call...however the new permissions are not applied to the vscode session or any new shells in the container and in order to get shells inside the container that know about my new usergroup I have to `sudo su - erin` which replaces ONLY the current shell instance with my new one. Clicking on the plus sign however still spawn a shell that looks like whatever the environment looked like when the dev container started. Even stopping the container and starting it again does not act like a relogin so I cannot easily apply my group permissions. I also think the snippet in the documentation is using the wrong group as the group docker-host doesn't exist. It does in your devcontainer definition as I see that you create it in your scripts but again that seems to be something related to the socat stuff and not the "primary" method you have defined.

In the end, I can use the socat method, that works fine and if that's the actual solution that's also ok. I just wanted to get some clarification and see if there was more information about the scripts currently in the documentation, or perhaps I am just missing something! 

Steps to reproduce:

1. Clone git@github.com:erinxocon/hourglass.git and checkout the branch `erin/vscode-devcontainer-dind`
2. Reopen the project in the devcontainer, it will build and should fail with
```
[2021-01-19T19:01:32.186Z] [PID 21940]  ---> Running in d41624eb61c0
[2021-01-19T19:01:32.595Z] [PID 21940] stat: cannot stat '/var/run/docker.sock': No such file or directory
[2021-01-19T19:01:32.601Z] [PID 21940] groupadd: invalid group ID 'docker-host'
```

Please let me know if I am either doing something wrong, or if the documentation needs updating. After I figure out the best method I don't mind updating the docs and submitting an MR.

Cheers!

**Comment by Chuxel** [comment]
Samples have been updated. There also was a regex bug that got fixed as well.  Let us know if you still are hitting issues!

**Comment by erinxocon** [comment]
I can confirm that the changes work! I now have host docker sock access from inside my dev containers! Thanks @Chuxel and team!
