### ISSUE TITLE
Add tini to docker-debian.sh so the users don't have to use --init in their devcontainer.json

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode-dev-containers#738]
The title says all.

**Comment by felipecrs** [comment]
I can PR it if you accept.

**Comment by 2percentsilk** [comment]
We're trying to minimize dependencies in our definitions and this addition will add a dependency to images that currently use Docker/Moby.

While it's not common, we also don't want to stop users from using other init systems.

Feel free to re-open if you feel strongly.

**Comment by felipecrs** [comment]
This doesn't stop anyone from using other init systems, as they can customize the ENTRYPOINT as they would want to. Also, `tini` has 23.5KB of size, so this doesn't add any weight to the container (remember that it simplifies the devcontainer.json for everyone).
