### ISSUE TITLE
Should the Docker * configs be in the 'Core' category?

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-dev-containers#750]
The Docker configs below have the `category` `Core` and the `Platform``Any`. They will therefore be recommended always as a 'Core'/primary recommendation. I suggest remove the `Core` category from these configs.

![image](https://user-images.githubusercontent.com/172399/107847743-722b0c80-6dee-11eb-9923-c0a87bf48d71.png)

**Comment by Chuxel** [comment]
@egamma These are actually fairly frequently used and referenced, so they're core, but I agree not as core as the language based ones. If we remove "Core" will they still appear, just lower in the list or would they only appear in "Show All Definitions"?  If they're lower, I agree we can remove.

**Comment by egamma** [comment]
@Chuxel just for your reference this is now the full list that is shown for the repository `https://github.com/microsoft/vscode-remote-try-node` (when the .devcontainer folder is removed).

<img width="603" alt="image" src="https://user-images.githubusercontent.com/172399/108239275-01675580-714a-11eb-9caa-ea5b16c880e4.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/172399/108239368-1ba13380-714a-11eb-863b-07ac662d955f.png">

They still appear a bit prominent for me.

**Comment by Chuxel** [comment]
Okay removed the Core category but left the "any" type.
