### ISSUE TITLE
Yarn signature issue in dotnet core 3.1 but not 5.0

### ISSUE THREAD

**Issue by andreujuanc** [microsoft/vscode-dev-containers#752]
- VSCode Version: 1.53.2
- Local OS Version: WSL2 (latest updates, stable)
- Name of Dev Container Definition with Issue: dotnetcore

Steps to Reproduce:

1. build with variant: "3.1" fails
2. build with variant: "5.0" works

This is the error:

```
[2021-02-17T14:35:29.461Z] [PID 20496] Err:4 https://dl.yarnpkg.com/debian stable InRelease
  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packagi
ng <yarn@dan.cx>
```

The images for 3.1 (and maybe others?) must be rebuilt with the newest keys as per https://github.com/yarnpkg/yarn/issues/7866

**Comment by andreujuanc** [comment]
Fixed by:

```diff
ARG VARIANT="3.1"
FROM mcr.microsoft.com/vscode/devcontainers/dotnetcore:0-${VARIANT}
+RUN sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
```

not sure if the keyserver is the properone. but it works.

**Comment by Chuxel** [comment]
@andreujuanc Just to verify, are you using Remote - Containers or Codespaces?

Assuming Remote - Containers, check to see if you have the latest versions of the images locally.  You may be running off an older locally cached version.

```bash
docker pull mcr.microsoft.com/vscode/devcontainers/dotnetcore:0-3.1
```

Or we can demonstrate this working just using docker run:

```bash
docker run -it --rm --pull always mcr.microsoft.com/vscode/devcontainers/dotnetcore:0-3.1 apt-get update
```

**Comment by andreujuanc** [comment]
Looks like I updated 5.0 but somehow I missed 3.1
Thanks. Pulling the image again fixed it.
