### ISSUE TITLE
The dotnet-mssql dev container SQL Server tools script outputs an error with `set -echo`

### ISSUE THREAD

**Issue by dslatkin** [microsoft/vscode-dev-containers#754]
- VSCode Version: 1.53.2
- Local OS Version: Windows 10 (Windows_NT x64 10.0.19042)
- Name of Dev Container Definition with Issue: dotnet-mssql

Steps to Reproduce:

1. Open VS Code and add the `dotnet-mssql` starter files
2. Reopen the folder in the container (building container image in process)
3. The script at `.devcontainer/mssql/installSQLtools.sh` line 2, `set -echo` outputs an error (see screenshot)

![err](https://user-images.githubusercontent.com/9263640/108308000-d1c54700-7163-11eb-967b-578d14ab2dc4.png)

**Comment by bamurtaugh** [comment]
I'm able to repro this.

When I modified it to `set echo on` or `set echo`, I didn't see the error anymore:

![image](https://user-images.githubusercontent.com/25310137/111008895-008ba300-8347-11eb-846f-720b417736e3.png)

Thoughts @chuxel?

**Comment by Chuxel** [comment]
@dzsquared ?
