### ISSUE TITLE
Add manpages, manpages-posix to C++ and kitchen sink, possibly other images

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#764]
We've had requests to add a few more manpages into these images.

- `manpages` and `manpages-dev` we should just be able to add to common-debian.sh
- However, `manpages-posix` and `manpages-posix-dev` are not in the "free" sources for Debian (though they are available by default in Ubuntu). We'd also need to [add non-free sources to include them](https://www.xmodulo.com/install-nonfree-packages-debian.html). On the surface this does not bother me for a general purpose dev image, but we'd likely want to have it as a script option for those using it themselves. 

This adds 6mb to the uncompressed image. The zipped image that is downloaded will be much smaller so it shouldn't significantly impact aquisition time.

//cc @2percentsilk @joshspicer @jkeech

**Comment by joshspicer** [comment]
https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/common-debian.sh
