### ISSUE TITLE
Dapr with C# should use docker-compose version '3.7'

### ISSUE THREAD

**Issue by ankur198** [microsoft/vscode-dev-containers#774]
init command in docker-compose file is introduced in version 3.7. It is currently set to version 3.4

**Comment by Chuxel** [comment]
@philliphoff - Does this make sense?

**Comment by philliphoff** [comment]
@Chuxel Yes, makes sense.  I've got some PR feedback from you to respond to as soon as I get the chance; I'll update the Compose versions in the templates as part of that.

**Comment by philliphoff** [comment]
This should be resolved with #765.
