### ISSUE TITLE
oh-my-bash removal warning not displayed as expected.

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode-dev-containers#775]
I have [this in my dotfiles as my .bashrc](https://github.com/joshspicer/dotfiles/blob/master/.bashrc).  Specifically, the `source` line at the end causes the following in a (right now, dev) codespace.

![image](https://user-images.githubusercontent.com/23246594/109909729-969f3980-7c74-11eb-895a-f0bb4753a5e9.png)

I was suuuper confused until I saw #674 !

**Expected behavior:**  Displays removal warning of oh-my-bash.
**Actual behavior:** Show error opening the file and cds me to `/bin` (??)

**Comment by joshspicer** [comment]
@Chuxel

**Comment by joshspicer** [comment]
changing the script to this worked for me on a codespaces

![image](https://user-images.githubusercontent.com/23246594/109910220-9f443f80-7c75-11eb-9e24-3e97752aa807.png)

There's a whole lotta discussion on how _best_ to set the cwd like we want.  Not sure if this is necessarily better, but seems better in my specific (codespaces) case!

**Comment by jkeech** [comment]
Is there a reason why we need to change the working directory instead of just running `cat` from the absolute path?

**Comment by joshspicer** [comment]
This change was in the `common-debian.sh` which initially made me think this was done for compatibility, however I can't think of an example where this file would not be  at `$HOME/.oh-my-bash/README.md`

**Comment by Chuxel** [comment]
Ah, yeah, that's a bug -- I actually fixed that but I must not have staged the change.

I tend to use `cd $(dirname $0)` or if I want the full path, `FULL_PATH="$(cd "$(dirname $0)" && pwd)"`
