### ISSUE TITLE
Not publishing MCR images?

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-dev-containers#780]
It looks to me like there hasn't been a version-tagged release to MCR since `0.157.0`:

https://hub.docker.com/_/microsoft-vscode-devcontainers

Some example links from that page:

- https://mcr.microsoft.com/v2/vscode/devcontainers/base/tags/list
- https://mcr.microsoft.com/v2/vscode/devcontainers/javascript-node/tags/list

Was there a change in how to access version-tagged images, or is something broken? (Sorry if it's been reported or mentioned, I looked around and didn't see anything.)

**Comment by Chuxel** [comment]
Yes - We decoupled the version release from the image updates.  You'll see version 0.200 and up is there.  This corresponds to a value in definition-manifest.json.  If you reference `0-` you'll still get the latest.  The READMEs have been updated to reflect this as has DockerHub, but it is a shift so thanks for raising it. 👍

**Comment by aaronadamsCA** [comment]
Thanks @Chuxel, I did not understand that (and I had read the docs!) but I've also been following the project for a while, thanks for describing the change. I will look at `definition-manifest.json` going forward!

FWIW I explicitly version our dev containers so that everyone uses the exact same one. Makes it a lot easier to rule out the container as a suspect whenever one developer (usually me...) starts having problems nobody else can reproduce. Glad I can continue to do so!
