### ISSUE TITLE
Add vcpkg to cpp image definitions

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/vscode-dev-containers#781]
[vcpkg](https://github.com/microsoft/vcpkg) is a cross-platform package manager for C++. The GitHub repository has over 12k stars, and the team [recently released support for registries](https://devblogs.microsoft.com/cppblog/registries-bring-your-own-libraries-to-vcpkg/).

I think adding vcpkg to the cpp devcontainer definition could help with onboarding and adoption.

**Comment by dnastrain** [comment]
@bderusha  and @dnastrain are working on this issue.
