### ISSUE TITLE
kubernetes-helm container installs an old version of kubectl

### ISSUE THREAD

**Issue by Stanpol** [microsoft/vscode-dev-containers#79]
- VSCode Version: 1.36.0-insider
- Local OS Version: MacOS 10.14.4
- Name of Dev Container Definition with Issue: kubernetes-helm

Steps to Reproduce:

1. Copy this directory https://github.com/microsoft/vscode-dev-containers/tree/master/containers/kubernetes-helm/.devcontainer
2. Open it in VS Code
3. `kubectl version` results with
```Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}```

This is an old version which has some bugs like this [SIGSEGV](https://github.com/kubernetes/kubernetes/issues/61712 ) one. The latest stable version should be v1.14.3.

This is due to this way of installation:
https://github.com/microsoft/vscode-dev-containers/blob/2002d518b4162cb39fb4585e7a43db824094064d/containers/kubernetes-helm/.devcontainer/Dockerfile#L25:L28 

Probably better to install kubectl following the instructions on the official website:
https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-linux

With a new Dockerfile old documentation should be updated as well:
https://github.com/microsoft/vscode-dev-containers/blob/master/containers/kubernetes-helm/README.md

**Comment by Chuxel** [comment]
This is actually installing kubectl using the official instructions - here https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-using-native-package-management

But it looks like their package updates are lagging.

We can rev it to use the curl approach instead.  Just not as easy to upgrade later.
