### ISSUE TITLE
Codespaces bash prompt doesn't display correct branch

### ISSUE THREAD

**Issue by jkeech** [microsoft/vscode-dev-containers#793]
Reported in https://github.com/github/feedback/discussions/3563

The Codespaces bash prompt includes the name of the current branch. This is currently calculated via `git describe --contains --all HEAD` which finds all branches/tags that point to the HEAD commit. A better approach to look at the current checked out ref might be `git rev-parse --abbrev-ref HEAD`.

@chuxel, @joshspicer are you aware of any downsides of switching to the rev-parse command for the prompt?

https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/common-debian.sh#L257

**Comment by jkeech** [comment]
I think the detached head state is the biggest issue. So perhaps we could check if rev-parse returns `HEAD` and then fallback to the `git describe --contains` command in that case. Thoughts?

**Comment by joshspicer** [comment]
i've never seen `git describe` before, would have assumed it was using rev-parse anyway.  So doing the revparse, then git describe makes sense to me!

**Comment by Chuxel** [comment]
Yeah I agree that showing the tag is not ideal here so switching to `rev-parse` makes sense.
