### ISSUE TITLE
Whitespace changes in newly checked out repo no Linux

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-dev-containers#80]
![image](https://user-images.githubusercontent.com/9205389/59420311-f680ed00-8dcc-11e9-9e62-37b680436d4a.png)

I guess these are old CRLFs. .jar should probably be excluded from LF.

**Comment by Chuxel** [comment]
@chrmarti Most of these should be LF, so it's unclear why that's happening.  A jar is also binary, so it shouldn't be getting line ending converted because of text=auto.  

What version of Git are you on?

**Comment by chrmarti** [comment]
This is Git 2.7.4. I'll look into updating the image which is based on Ubuntu 16.04.

The changes disappeared after I first removed and then added `.gitattributes` back. 🤔

**Comment by chrmarti** [comment]
Doesn't repro with Git 2.20.1. Thanks!
