### ISSUE TITLE
python-3-miniforge devcontainer (compatible with existing python-3-miniconda devcontainer)

### ISSUE THREAD

**Issue by eitsupi** [microsoft/vscode-dev-containers#802]
Last year, the Anaconda repository became fee-based for large commercial organizations.
That's one of the reasons that some people want to use conda-forge instead of the Anaconda repository.
https://www.anaconda.com/blog/anaconda-commercial-edition-faq

There is a project called miniforge that provides a conda installer that assumes the use of conda-forge, and also provides Docker images.
It would be useful for those who want to use conda-forge to have a devcontainer with miniforge installed instead of miniconda.
https://github.com/conda-forge/miniforge
https://github.com/conda-forge/miniforge-images

For reference, miniforge is used in the Docker images provided by the Jupyter Project. (https://github.com/jupyter/docker-stacks/pull/1189)
https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile

**Comment by shimwell** [comment]
Just to add that we are also keen on a miniforge container

@Asureda @jordifradera

**Comment by hadim** [comment]
That would be very nice to have miniforge supported here and more specifically mambaforge!

**Comment by hadim** [comment]
I built a dev container config based on the Micromamba docker image in case it can be useful here: https://github.com/datamol-org/datamol/tree/main/.devcontainer

**Comment by eitsupi** [comment]
Closing in favor of the Dev Container Feature `ghcr.io/rocker-org/devcontainer-features/miniforge`.
