### ISSUE TITLE
VS Code cannot open a new ZSH profile terminal till the sleep command is done

### ISSUE THREAD

**Issue by kosalanuwan** [microsoft/vscode-dev-containers#806]
The fixes done for the `common-debian.sh` via PR https://github.com/microsoft/vscode-dev-containers/pull/785 causing the VS Code Terminal not to open a new ZSH till the `sleep` command is done.

https://github.com/microsoft/vscode-dev-containers/blob/e2b3c095dd6811d447aee6c9b75d801566c4f358/script-library/common-debian.sh#L210-L229

![image](https://user-images.githubusercontent.com/958227/113499100-fff2c080-9530-11eb-8ac5-63f81d25a2c0.png)

- VSCode Version: 1.55.0
- Commit: c185983a683d14c396952dd432459097bc7f757f
- Date: 2021-03-30T16:01:05.981Z
- Electron: 11.3.0
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Darwin x64 20.4.0
- Local OS Version: macOS Big Sur 11.3 Beta (20E5224a)
- Name of Dev Container Definition with Issue: azure-functions-dotnet-3.1

Steps to Reproduce:

1. Set `INSTALL_ZSH: "true"` in `devcontainer.json` or `docker-compose.yml` or `Dockerfile` to ensure ZSH is installed.
2. Uncomment the ZSH install code, this will download the `/script-library/common-debian.sh` from `master` branch.
   https://github.com/microsoft/vscode-dev-containers/blob/e2b3c095dd6811d447aee6c9b75d801566c4f358/containers/azure-functions-dotnetcore-3.1/.devcontainer/Dockerfile#L13-L20
3. With VSCode, rebuild and open in Remote - Container.
4. Once VSCode opens in Remote - Container, try to open Terminal in VSCode and Select ZSH profile.
5. Note the awkward `cat` profile with some numbers till it prints `sleep ...` text on the Terminal.

**Comment by Chuxel** [comment]
Confirmed this is a bug - some sort of zsh incompatibility with POSIX syntax.

**Comment by Chuxel** [comment]
Fix is to replace
```
     (sleep 10s; touch "$HOME/.config/vscode-dev-containers/first-run-notice-already-displayed") & >/dev/null 2>&1 
     disown %+ 
```

with 

```bash
    ((sleep 10s; touch "$HOME/.config/vscode-dev-containers/first-run-notice-already-displayed") &)
```

in `/etc/zsh/zshrc` (eg using `sudo nano /etc/zsh/zshrc`)

Will queue up a PR to resolve in images.
