### ISSUE TITLE
Linux shell defined in *devcontainer.json* will be not applied

### ISSUE THREAD

**Issue by kirillsafin** [microsoft/vscode-dev-containers#838]
- VSCode Version: 1.55.2
- Local OS Version: Debian GNU/Linux bullseye/sid
- Name of Dev Container Definition with Issue: debian:testing-slim

Steps to Reproduce:

1. In VS Code on my device I use zsh as `terminal.integrated.shell.linux`,
2. Create devcontainer.json. for running container
2. Change the autocreated `"terminal.integrated.shell.linux": "zsh"` to `"terminal.integrated.shell.linux": "bash",`,
3. After attaching to container and opening terminal I get the message **The terminal process failed to launch: Path to shell executable "zsh" does not exist.**

I have already tryied to restart the container and reopen vs code. But it seems that this setting will not overwritten on attaching to container.

**Comment by Chuxel** [comment]
@kirillsafin The base Debian image likely does not have zsh installed.  If it does, try adding the full path: /usr/bin/zsh or /bin/zsh

**Comment by kirillsafin** [comment]
> @kirillsafin The base Debian image likely does not have zsh installed. If it does, try adding the full path: `/usr/bin/zsh` or `/bin/zsh`. Most definitions in this repository run `common-debian.sh` from the `script-library` which includes zsh and Oh My Zsh! installation options.

That's true, I guess there are not so much images which have zsh installed. I meant that in my VS Code settings on my physical device I have set the default linux shell to zsh `"terminal.integrated.shell.linux": "zsh"`. If I select **Remote-Containers: Add Development Container Configuration Files ...** from Command Palette there will be **devcontainer.json** created. Also the setting ``"terminal.integrated.shell.linux":` will be set and the value will be taken from my global settings for vs code, so the line `"terminal.integrated.shell.linux": "zsh"` will be automatically generated in **devcontainer.json**.
I thought I can change it for example to `"terminal.integrated.shell.linux": "bash"` (because I know debian image has bash installed, If it would be alpine based image or so I would set it to `sh`), but after clicking on  *attach to container* vs code window appears running inside the attached container and it seems to me like it ignores this `"terminal.integrated.shell.linux": "bash"` line inside **devcontainer.json** and applies my global settings. For example the defined extensions inside **devcontainer.json** will be applied, so I thought I can override or add some settings within **devcontainer.json** which will be applied to vs code instance running in the container

**Comment by Chuxel** [comment]
@kirillsafin It turns out that there's been an update to these properties in favor of a new `terminal.integrated.profile.linux` property.

e.g.

```
  "terminal.integrated.profiles.linux": {
    "zsh": {
      "path": "/usr/bin/zsh"
    }
  },
  "terminal.integrated.defaultProfile.linux": "zsh"
```

However this is causing some unexpected results, so we'll likely switch the default back and determine a migration plan tracked here https://github.com/microsoft/vscode/issues/123157

**Comment by kirillsafin** [comment]
I am not sure, if I expressed right my self.
So actually I don't need zsh in the containers. It is completely enough to use the default shell of the container for example to check some env variables or install additional packages in the container or something like this.

So here are the vs code settings on my physical device (because I use as default shell on my physical device zsh):
```js
...
 "terminal.integrated.shell.linux": "zsh",
....
```
and here are the settings from my devcontainer.json
```js
// Set *default* container specific settings.json values on container create.
  "settings": {
    "terminal.integrated.shell.linux": "bash",
    "terminal.integrated.profiles.linux": {
      "bash (container default)": {
        "path": "/usr/bin/bash",
        "overrideName": true
      }
    }
  },
```
I have also tried without `"terminal.integrated.profiles.linux"` and with `"terminal.integrated.shell.linux": "/usr/bin/bash
",`

**Comment by Tyriar** [comment]
@kirillsafin  In the recovery build we'll fix this up by prioritizing shell over defaultProfile for now https://github.com/microsoft/vscode/issues/123159

For your example there you would also need this to set the profile as the default:

```json
"terminal.integrated.defaultProfile.linux": "bash (container default)"
```

**Comment by kirillsafin** [comment]
Ok thank you!

**Comment by Chuxel** [comment]
This should be resolved with the latest definitions as well!  Closing. Thanks for raising it!
