### ISSUE TITLE
`docker-in-docker-debian.sh` library script hardcoded to use `amd64`

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-dev-containers#840]
- VSCode Version: N/A
- Local OS Version: N/A
- Name of Dev Container Definition with Issue:

[script-library/docker-in-docker-debian.sh](https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/docker-in-docker-debian.sh)

The script [hardcodes](https://github.com/microsoft/vscode-dev-containers/blob/8f50194b218fddadf93673a0b214c77bf4fe401b/script-library/docker-in-docker-debian.sh#L74) use of the `amd64` packages for installing Docker.  It should, at a minimum, allow the script user to optionally specify a different architecture (e.g. `arm64`), which would allow use of the script on Dev Container hosts such as the M1 Mac.  It would be even better if the script detected the architecture of the running container and chose the appropriate version.

ddcc1

**Comment by Chuxel** [comment]
The script has been updated!
