### ISSUE TITLE
[upstream] Cannot access noVNC from the web using Codespaces

### ISSUE THREAD

**Issue by sarisia** [microsoft/vscode-dev-containers#854]
[`script-library/docs/desktop-lite.md`](https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/docs/desktop-lite.md) has a guide for running `noVNC` in devcontainer, but it won't work due to the
lack of a step.

In `Usage` section, before accessing the published port in step `4`, we need to "Right click the port -> Make Public" that port
or we'll get HTTP 308 for `wss://` access and cannot establish WebSocket connection:

> 4. Once you've started the container / codespace, you'll be able to use a browser on port 6080 from anywhere or connect a VNC viewer to port 5901 when accessing the codespace from VS Code.

![image](https://user-images.githubusercontent.com/33576079/117297354-12a24180-aeb1-11eb-8d5f-1e47655655dd.png)

It's better to have this step noted to avoid confusion.

**Comment by Chuxel** [comment]
@sarisia I assume you're seeing this in Codespaces?  If so, that's actually a Codespaces bug.

**Comment by sarisia** [comment]
Oh sorry I forgot to note that.

Yes, it happens in GitHub Codespaces.

**Comment by Chuxel** [comment]
This should now be resolved in production for Codespaces as well!

**Comment by sarisia** [comment]
Confirmed WebSocket is now working without "Make Public" the port! Thank you!
