### ISSUE TITLE
SSL connection could not be established

### ISSUE THREAD

**Issue by ericfeunekes** [microsoft/vscode-dev-containers#883]
- VSCode Version: 1.56.2
- Local OS Version: Windows 10 Enterprise 1909 (OS Build 18363.1556)
- Name of Dev Container Definition with Issue: azure-functions-python-3

Steps to Reproduce:

I followed the steps [in the git repo for this dev container](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/azure-functions-python-3#using-this-definition). 
1. Starting with a blank folder
2. Created the config files for the devcontainer using VSCode remote extension
3. Opened the devcontainer
4.  F1 > Create function project (followed steps to [test the definition](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/azure-functions-python-3#testing-the-definition))
5. Once the function project is created, press F5 to debug.

I get the following output: 

```
Found Python version 3.8.9 (python3).

Azure Functions Core Tools
Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
Function Runtime Version: 3.0.15417.0

[2021-06-04T20:49:49.315Z] A host error has occurred during startup operation 'eb0ca931-baf1-44ed-b157-59c45ea1272e'.
[2021-06-04T20:49:49.316Z] System.Net.Http: The SSL connection could not be established, see inner exception. System.Private.CoreLib: The remote certificate is invalid according to the validation procedure.
Value cannot be null. (Parameter 'provider')
```

**Comment by Chuxel** [comment]
@anthonychu @TsuyoshiUshio ?

**Comment by TsuyoshiUshio** [comment]
Hi @ericfeunekes 
I tried to reproduced however, I couldn't (it works).    The core-tools image is nightly updated. It could possible we had a bug in the past.  Could you check the version? For the more investigation, F5 = `.venv/bin/activate && func host start`  in this case, we can find the Core tools and Azure Functions Host runtime version that helps us to investigate more.  `func host start --verbose` might give us more information. 

```
Azure Functions Core Tools
Core Tools Version:       3.0.3568 Commit hash: e30a0ede85fd498199c28ad699ab2548593f759b  (64-bit)
Function Runtime Version: 3.0.15828.0
Functions:
        HttpTrigger1: [GET,POST] http://localhost:7071/api/HttpTrigger1
```

**Comment by ericfeunekes** [comment]
You're right @TsuyoshiUshio, looks like it resolved itself.
