### ISSUE TITLE
Build fails when fetching moby package from packages.microsoft.com

### ISSUE THREAD

**Issue by Pytal** [microsoft/vscode-dev-containers#897]
- VSCode Version: 1.57.0
- Local OS Version: Windows 10 21H1
- Name of Dev Container Definition with Issue: Any Dev Container which uses the [`docker-debian.sh`](https://github.com/microsoft/vscode-dev-containers/blob/f08b87ecf279468bf6e647a08d8efe4cdc178068/script-library/docker-debian.sh#L70-L72) or [`docker-in-docker-debian.sh`](https://github.com/microsoft/vscode-dev-containers/blob/f08b87ecf279468bf6e647a08d8efe4cdc178068/script-library/docker-in-docker-debian.sh#L74-L76) scripts

Steps to Reproduce:

1. Start a dev container which runs either the [`docker-debian.sh`](https://github.com/microsoft/vscode-dev-containers/blob/f08b87ecf279468bf6e647a08d8efe4cdc178068/script-library/docker-debian.sh#L70-L72) or [`docker-in-docker-debian.sh`](https://github.com/microsoft/vscode-dev-containers/blob/f08b87ecf279468bf6e647a08d8efe4cdc178068/script-library/docker-in-docker-debian.sh#L74-L76) script

**Comment by Pytal** [comment]
Closing as the issue has been fixed

**Comment by Pytal** [comment]
Reopening as fetching moby packages from https://packages.microsoft.com/repos is failing again.

**Comment by Chuxel** [comment]
Yes, it looks like upstream there's a problem that's been reported. This is not specific to these images as it's been reported for people just using the feed locally as well: https://github.com/Azure/azure-cli/issues/18514

The IP issue has been resolved, but now GPG key failures are being reeported.

**Comment by Chuxel** [comment]
This appears to be fixed.
