### ISSUE TITLE
Add --init to all definitions

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#917]
For the most part, containers that come from this repository are intended to run long enough that having an init process that cleans up "zombie processes" is useful. For performance reasons, systemd or other init systems are not used by default. As a result, it's likely a good idea for us to have the built-in "tini" init process enabled via `"runArgs" : [ "--init" ]` or in the Docker Compose file.

**Comment by joshspicer** [comment]
for features, would we just want to include the arg automatically when the CLI builds the image?

**Comment by Chuxel** [comment]
@chrmarti I assume you didn't wire up "--init" into `features.json` yet, correct?  We certainly could.
