### ISSUE TITLE
Support for Windows Containers

### ISSUE THREAD

**Issue by dumbnose** [microsoft/vscode-dev-containers#927]
Windows containers require mounts to use Windows format, but with backslashes changed to forward slashes. You can override the workspacemount to get around this. But, the 'vscode' mount that gets created does not seem to be able to be overridden. 

Please add first class support for Windows containers for the extension.

**Comment by Chuxel** [comment]
Do you mean containers running **on** Windows or support for container images that run Windows **inside** the container?

Remote - Containers and Codespaces do not support Windows Containers at all.  You can upvote that request here if that is what you are talking about:  https://github.com/microsoft/vscode-remote-release/issues/445

**Comment by Chuxel** [comment]
Closing in favor of microsoft/vscode-remote-release#445
