### ISSUE TITLE
Determine approach to inject variables when using scripts

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#928]
Right now scripts in the script library set certain environment variables using `/etc/bashrc` and `/etc/zsh/zshrc`. While this works, it is only sourced in interactive terminals and not available to straight `sh` which is often used during OS startup.

`PATH` is the primary one that is a challenge since this needs to be modified and is set by default in /etc/environment for ubuntu-based images. It is also reset in `/etc/profile` on debian-based images for login shells, but the Remote - Containers / Codespaces extensions have code to resolve this particular issue. //cc @chrmarti on this part.

**Comment by chrmarti** [comment]
Note that my testing showed that `/etc/environment` is not used when using `docker exec`. We are now using `/etc/environment` to get the container's environment variables into sshd (and these are already applied when using `docker exec`). So variables only present in `/etc/environment` would be missing in VS Code from what I saw (there could be differences between distros, not sure).

**Comment by Chuxel** [comment]
@chrmarti 😭Doh. Hmmm. We'll have to figure out how to update environment variables in the lego blocks experience.  We could do #915 but the current Codespaces default of `none` for `userEnvProbe` is problematic.

**Comment by Chuxel** [comment]
@chrmarti Actually what specifically does that affect in Remote - Containers (if anything)? Or are you just highlighting that calling `docker exec` wouldn't get it? I guess it could get added to multiple spots if needed. 

Otherwise we may need to inject ENV values in the Dockerfile programmatically for lego blocks (#615) which I know we wanted to ignore.

**Comment by chrmarti** [comment]
We use `docker exec` when we access the container, including starting the VS Code Server. So the `/etc/environment` variables won't be available in VS Code tasks, launches and terminals.

We could add a `"containerEnv"` equivalent to the features.json and inject these with `ENV` in the features Dockerfile. Would that help?

**Comment by Chuxel** [comment]
> We could add a "containerEnv" equivalent to the features.json and inject these with ENV in the features Dockerfile. Would that help?

@chrmarti  Yes that would be perfect!

**Comment by Chuxel** [comment]
Closing this given we appear to have a direction here.
