### ISSUE TITLE
To set .env in devcontainer.json.

### ISSUE THREAD

**Issue by PONzu-0529** [microsoft/vscode-dev-containers#934]
I want to be able to set .env in devcontainer.json.

I'm using Docker Desktop in Windows.
Docker Desktop version 3.4.0 or later, seamlessly move to Docker Compose V2.
In Docker Compose V2, when run the docker-compose, if you do not use --env-file, it seems to read .env in the directory where the command is ran.
My running environment is as follows:
In this case, docker-compose is ran under the "project" directory, so it crashes with the error of missing .env.
In order to use Docker Compose V2, I would like to be able to set .env in the devcontainer.json.

I'm sorry I'm not good at English.
Please let me know if there is a solution.

```
project
│
├ .devcontainer
│    ├ devcontainer.json
│    ├ docker-compose.yml
│    └ .env
│
├ config, public, src...
```

**Comment by Chuxel** [comment]
You should be able to use `env_file: .env` in the compose case.

See https://code.visualstudio.com/docs/remote/containers-advanced#_option-2-use-an-env-file

If you'd like a feature request to cause something else to happen, please raise an issue at https://github.com/microsoft/vscode-remote-release

**Comment by PONzu-0529** [comment]
Thank you for your answer, and I'm sorry I made a mistake in raising an issue.
Some questions remain, so I asked them again at the following URL: https://github.com/microsoft/vscode-remote-release/issues/5324
I'm sorry for bothering you, but I appreciate your cooperation.

**Comment by luis-gmonkey** [comment]
I managed to hack around this issue adding a `"initializeCommand": "cp .env .devcontainer/.env"` to my `devcontainer.json` file.
