### ISSUE TITLE
Python Extension can't find pip

### ISSUE THREAD

**Issue by jyooru** [microsoft/vscode-dev-containers#938]
- VSCode Version: 1.57.1 507ce72a4466fbb27b715c3722558bb15afa9f48 x64
- Local OS Version: Pop!\_Os 21.04
- Name of Dev Container Definition with Issue: [python-3](https://github.com/microsoft/vscode-dev-containers/blob/v0.177.0/containers/python-3/.devcontainer/Dockerfile)

Steps to Reproduce:

1. Have pytest enabled in config:
   ```json
   "python.testing.pytestEnabled": true,
   ```
1. Open Devcontainer
1. Prompt appears, press yes:
   ![image](https://user-images.githubusercontent.com/63786778/124896747-0ce7ea00-e021-11eb-9cd2-08f7337c5fee.png)
1. Following error appears:
   ![image](https://user-images.githubusercontent.com/63786778/124896852-238e4100-e021-11eb-9a23-7e433f6b33c7.png)

This does not occur when running outside of the devcontainer.

**Comment by Chuxel** [comment]
@jyooru pytest is not in the images, so this is expected. See https://github.com/microsoft/vscode-dev-containers/pull/353

The python extension needs it to be installed as a part of the project rather than as a global pipx-based utility.

**Comment by jyooru** [comment]
@Chuxel the issue is not related to the fact that pytest is not preinstalled - this is just how I have come across this issue.

> 4. Following error appears:
   ![image](https://user-images.githubusercontent.com/63786778/124896852-238e4100-e021-11eb-9a23-7e433f6b33c7.png)

The issue is that the Python Extension can not find pip.
