### ISSUE TITLE
Update the node version in the typescript-node images?

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-dev-containers#941]
- Clone VS Code into a dev container volume, now you can also do this from the badge in the README
![image](https://user-images.githubusercontent.com/172399/125201422-5d548700-e26f-11eb-90de-685678f2c007.png)

- Try to run yarn/yarn watch in the VS Code terminal. You get warned about an out of date node version.

```
node ➜ /workspaces/vscode (main) $ yarn
yarn install v1.22.5
$ node build/npm/preinstall.js
*** Please use node.js versions >=14 and <=17.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
node ➜ /workspaces/vscode (main) $ node --version
v12.21.0
node ➜ /workspaces/vscode (main) $ 
```

**Comment by Chuxel** [comment]
There's images for 10 (tho deprecated), 12, 14, and 16. It's just VS Code that is on 12 right now. 

Go to 14 or 16?

**Comment by egamma** [comment]
@joaomoreno what do you recommend?

**Comment by egamma** [comment]
see also https://github.com/microsoft/vscode/issues/128408

**Comment by Chuxel** [comment]
The build system was overwriting this from 14 to 12 based on the variant set in the definition-manifest.json file.  I've updated that and triggered a build.

**Comment by Chuxel** [comment]
Base image is now updated.
