### ISSUE TITLE
Use Docker-in-Docker with Node.ls image

### ISSUE THREAD

**Issue by anchpop** [microsoft/vscode-dev-containers#956]
- VSCode Version: Codespaces
- Local OS Version: Chrome (MacOS)
- Name of Dev Container Definition with Issue: javascript-node

I thought it was working yesterday, but I must be misremembering. I have a workflow that depends on node, and docker-in-docker is nice to have too. Docker-in-docker actually works in the default devcontainer (what you get when you have no .devcontainer folder), so it's unintuitive that it stops working in other containers. Any idea what to do?

**Comment by Chuxel** [comment]
For custom containers, follow these directions: https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/docker-in-docker.md
