### ISSUE TITLE
Rust dev container setting `"terminal.integrated.shell.linux"`

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-dev-containers#957]
https://github.com/microsoft/vscode-dev-containers/blob/09f0ea6fa7d823ad091c77b61bb8458f3d82568a/containers/rust/.devcontainer/devcontainer.json#L14

VS Code says that `"terminal.integrated.shell.linux"` is deprecated.

**Comment by Chuxel** [comment]
Ack - This came back after a PR was merged.  Thanks!  Removed.
