### ISSUE TITLE
Go containers has analysis tools missing (dlv-dap)

### ISSUE THREAD

**Issue by Luit** [microsoft/vscode-dev-containers#984]
- VSCode Version: 1.59.0
- Local OS Version: Windows 10 Home 21H1
- Name of Dev Container Definition with Issue: go

Steps to Reproduce:

1. Start vscode-remote-try-go
2. Notice "Analysis Tools Missing" at the bottom, complaining about a missing `dlv-dap`.

**Comment by Chuxel** [comment]
@hyangah Are there some tweaks like this that we should make to the dev container image given Go extension updates?

**Comment by Luit** [comment]
I guess [go-debian.sh's GO_TOOLS](https://github.com/microsoft/vscode-dev-containers/blob/ed5ba90b3439908fa362989dd24d0cefcd7be854/script-library/go-debian.sh#L153) needs the new Go extension dependency.

**Comment by hyangah** [comment]
Sorry that I forgot to keep you posted. Yes, dlv-dap is currently marked as a required tool.
That is the default debug adapter (actually delve built from the master) in the latest vscode-go release.
I hope to consolidate it with `dlv`, then we will need another adjustment.
