### ISSUE TITLE
Go container node install has bad conditional, is also unable to install node lts version

### ISSUE THREAD

**Issue by cbbm142** [microsoft/vscode-dev-containers#987]
- VSCode Version: 1.59.0
- Local OS Version: 10.0.19043
- Name of Dev Container Definition with Issue: Go

Steps to Reproduce:

1. Build container with no version of node specified and you receive this error
` => ERROR [2/2] RUN if [ "none" = "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install none 2>&1"; fi                                                                                                                                                0.9s
------
 > [2/2] RUN if [ "none" = "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install none 2>&1"; fi:
#5 0.915 Version 'none' not found - try `nvm ls-remote` to browse available versions.`

2. If you fix the conditional and attempt a lts, you recieve this error
` => ERROR [2/2] RUN if [ "lts" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install lts 2>&1"; fi                                                                                                                                                 0.7s
------
 > [2/2] RUN if [ "lts" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install lts 2>&1"; fi:
#5 0.641 Version 'lts' not found - try `nvm ls-remote` to browse available versions.`

**Comment by Chuxel** [comment]
Ack! Yeah, `lts` should be `lts/*` which works in that comment. That removes the need to do the condition.   This needs to be done in a number of spots I think.

**Comment by Chuxel** [comment]
Workaround:

1. Specify a version other than `lts` when prompted.
2. Update `args` in `devcontainer.json` to `"NODE_VERSION": "lts/*"`
3. Rebuild / create the container
