### ISSUE TITLE
Add rustfmt and clippy to Rust dev container

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-dev-containers#99]
Add [rustfmt](https://github.com/rust-lang/rustfmt) and [https://github.com/rust-lang/rust-clippy](https://github.com/rust-lang/rust-clippy) to the dev container would be great (and maybe the latter set up for `tasks.json`?).

Adding rustfmt also makes having `editor.formatOnSave` very useful to have, but I don't know if flipping those kinds of settings on in `devcontainer.json` by default is desired.

**Comment by Chuxel** [comment]
Resolved by #114 by you! Thanks!!!
