### ISSUE TITLE
Add docker image platform def

### ISSUE THREAD

**Issue by qsliu2017** [microsoft/vscode-dev-containers#995]
I'm using MacBook M1, and sometimes I need to develop in x86-64 environment. To do so, I usually start an x86-64 container locally. Can you add a definition to specify the platform of the devcontainer?

Relates to: Remote - Containers

**Comment by fabiopicchi** [comment]
Has this been added? Can't find it in the docs.

**Comment by qsliu2017** [comment]
> Has this been added? Can't find it in the docs.

Hi @fabiopicchi.

I'm doing this by specifying the digest of the platform.

For instance, see https://github.com/qsliu2017/Staff-Training/blob/54e16cbd79b69ca7480620c9eb3dbc17f11ee996/docker-compose.yml#L5

**Comment by fabiopicchi** [comment]
Sorry, I don't have access to that repo :/

But I found this feature in docker's documentation. In a Dockerfile you can actually do:
```FROM --platform linux/amd64 debian:stable```
