### ISSUE TITLE
Integrated terminal takes many seconds to re-draw when repository has hundres of branches.

### ISSUE THREAD

**Issue by janitorr** [microsoft/vscode-dev-containers#999]
Hello,
I love using dev containers but one particular repository has made me frustrate immensely and made it difficult for me to get my colleagues to use shared container instead building their own environment. If this does not belong to this repository please direct me to correct way.

Every time I type a command to the integrated terminal it responds immediately but then locks for 2-10 seconds to redraw the prompt.
It took me a while to figure this out but it seems like the culprit is in the .bashrc where it defines how to show the active git branch on the prompt, it seems to take a long time with our repository that has over 400 branches.

Here is the definition causing my issues:
```
`# Codespaces bash prompt theme
__bash_prompt() {
    local userpart='`export XIT=$? \
        && [ ! -z "${GITHUB_USER}" ] && echo -n "\[\033[0;32m\]@${GITHUB_USER} " || echo -n "\[\033[0;32m\]\u " \
        && [ "$XIT" -ne "0" ] && echo -n "\[\033[1;31m\]➜" || echo -n "\[\033[0m\]➜"`'
    local gitbranch='`\
        export BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null); \
        if [ "${BRANCH}" != "" ]; then \
            echo -n "\[\033[0;36m\](\[\033[1;31m\]${BRANCH}" \
            && if git ls-files --error-unmatch -m --directory --no-empty-directory -o --exclude-standard ":/*" > /dev/null 2>&1; then \
                    echo -n " \[\033[1;33m\]✗"; \
               fi \
            && echo -n "\[\033[0;36m\]) "; \
        fi`'
    local lightblue='\[\033[1;34m\]'
    local removecolor='\[\033[0m\]'
    PS1="${userpart} ${lightblue}\w ${removecolor}\$ "
    unset -f __bash_prompt
}
__bash_prompt`
```

So I removed the ${gitbranch} part of the PS1 line and now the prompt is always snappy and does not hang.

Now, I´m not bash wizard enough to modify the script that gets the branch so I just had to remove it, and I´d hate to tell my colleagues that they need to modify this to get the container working without terminal lag.

I do understand that 400+ branches is not normal and I´m going to have to tell them to delete their feature branches after merges but maybe this is something worth taking to account for other people trying to adopt dev containers for monolithic repos?

Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042
Container: https://github.com/microsoft/vscode-dev-containers/tree/v0.177.0/containers/typescript-node

**Comment by Chuxel** [comment]
Let's merge this in with #986.
